apiVersion: v1
data:
  BUNNY_CDN_TOKEN: ENC[AES256_GCM,data:sbpDLMoZwfu6TdezZWQ7CUlILCEfAdsDfOFbvEXvNqnT+xucFiEGVohBdV7KqtZx,iv:riwkyVdxULVHOELaP3KDGaTktMZ8qwY6J2nC1qjacIU=,tag:hKfTUmprs/bxmuBTwpCGaw==,type:str]
  DB_NAME: ENC[AES256_GCM,data:3WdCjdkuAynEeUti9t5Z6Q==,iv:iWQ8goS7jfwKoQC2E0QrY98u67aFmrmGV7XMcF8Syqw=,tag:cfN2nJ7k4awYoi9MHIKcPg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:2EHDOVpONzeThzaZQix1UUdkgGw=,iv:9iEeZhNdSAT25hfI7Suzo+OHIuGX0nnp6kJfOfT+z58=,tag:pxb84RFiFwfwymD1HQTGdA==,type:str]
  DB_USER: ENC[AES256_GCM,data:D9JxdEy7wmC7kzNb7q3/eXbrQoI=,iv:ipT+671QoPz1RXFKgRwP1G8PeCWhWx2UIEX8HGnLqFQ=,tag:LTAq0ph0yO9/pq7FnKkSLA==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:GGk9x2o74uKQsMnep+yPhVrG43JPs5D+,iv:PQY8HGiO19isfZmiyz4jHi6Bglhe8AbhQQAAO65607E=,tag:4MP4mlwmbdyvRNu//qrnqQ==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:J4i3LC/RWRxS4KM20BhNZYCtRhI=,iv:TC7KYepjMUQuJ38CmZRmZxVbV13/8x8WZU7XpTjZNLI=,tag:SXYNI5OWcA9TG+DK+4WA0g==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:f7uKEsAWMjsHa/g3zCzaoQ==,iv:nKTRue8frCvk5T3rkkTYvuZfWGTrlReawBo7tvufUD4=,tag:ynv5er1kB8UF7AQn3v0S1Q==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:6UWiYZjYSqzpHctdu3uebrDCASlYg3BiT4nRoUHqJjNmzJYiSS+s3bujMYyFjlOv7YKT2zZhqtc3i1JFjbv+I+sMoAw=,iv:jnOuaS8TpY3ch5yErb+aLlzfW1+DY4oq1idGJof1Hio=,tag:OK084JyQK/BSkGsOQD8QKA==,type:str]
  DJANGO_INTERNAL_TOKEN: ENC[AES256_GCM,data:60ror3tv9NxUfW54XBSDxnQNfvNJG7Ej4V4sedCkDG3K3NGQS+Dh1aQLzU3ckVf3yN1mu8P+nqMFmm7jQgVpGYH4Cv5vQPNpd90rADhsFJVgi3QvWOcExQ==,iv:ydKIY598kbueKHtSiQFElPsLn6F4EJcyZD0LCMU2Q0M=,tag:+5ABliJJcUmUGnDNBP1RVw==,type:str]
  EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:6nxztWwBtnK5pXS4nEkvRykcCCZr9RQfv2Ty1A==,iv:UlmwsxQl/CorAmnCTNQLu/pMq3DMVF9lxF4RrVn38r0=,tag:PHTinhfRHFpiIAk+pHvDWQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: caas-dev-secrets
  namespace: dev
sops:
  lastmodified: "2026-01-17T15:42:44Z"
  mac: ENC[AES256_GCM,data:A+4Rjl1T5ob+75ihLbwiphAPer6dXanfnMofpoppMoGkpLzqzTLWaK76xBdP2lJnj21KhuMuqioQtOYUzRZttceqCeOfipmvuAimLzaakcd1R/V3FVyBFvX+sRyLQp3BuxG9HwcyVXwnQwepnIUOoA1VWqsSa/1BDzSvZUiWYMY=,iv:yORQwkr6tNZ57aZVUImKBCbFCxDvsdcLaEjF1o/gJlU=,tag:AlAjw62GUc3WpgnJzWWrWw==,type:str]
  pgp:
    - created_at: "2026-01-17T15:42:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAprOKutkkmpyL61I8f56cGUYj4glBRP/vbQOaDWQFdyJs
        smR4Xzrz0Pq/FiR5vEldOVnmZ4wv5EgQmU/3yOdByj8YC0CY/OEdzMFAxsH1WnV6
        eULXHwTQkrmhTVef/H1HRIEptOC4TMIofJSugDDwGwAmyilYPD69ngAvjZcmyVa+
        p46k9GmZS+xunMqsEvitWc7oJTTRkzWx1oiKFGGzJMF6+ehIpfGS1BIIWqrBAsYd
        jr0aLzmhUqpKVC0q1EJUoxKQH3PeMWC22CD4UGzu8n4MguB4xdcQK16zAZTmuyGV
        Ts86ThuUBpAWZ+Tw8iae98MsfBwhhd7UFlnp5iTJy2iKePpRYTUhHLlro829rEF3
        4DGP239OtLDxlIt7+WWT//0IbHTvVp+2n35yB1i3xh/hH6q3UykcOTQY60E5i353
        bcdpQXxjxS7QOuLEa2vOnFny7O9W5Bt7TwPI1bBg8If+WkNY5sccuS4Obuq9jXxu
        6CNYXEaw+ec3Ra5pa13aK+cxgwJi3nwUi/GRVgGxugrfMEbM9Nqc9J/LB6Rju0qX
        evUKIBR/74f3JoU3RtHLEHAmLlMjmF6waglb7h5wxYeCA7gEg/8SNrbavASSIj3/
        qi0SYGHJvlQzUbLwVbQuVOCqwM47d8bxaw4z8/D4TxAd+Js/KZkxgsFmqv59JGnU
        aAEJAhB1T7s0lVy2bjCEzW6gLvIm16L8nVmtNYevTYPEmCw81MTyc+58djg6YSKX
        H4dvRn4aC1SMWH/2II/cjg4UTbiTHneg+xPpaAavTPyVdhmMKmUWXMT4HkASKY6w
        TQ2I0dkPReij
        =FvSp
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
