apiVersion: v1
data:
    DB_NAME: ENC[AES256_GCM,data:IjtGrpGHEiToyXlDdV3o9A==,iv:ikM89akRc6BIs2sFHu4VREm6obee/REMCts+65mpAY0=,tag:HSJoYsSf2jaB4Ug0LvWkhQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:CL7QAyN1XFbOa5AH/ADwS2KcVwA=,iv:e+HJ6ekoVVnrDrVc1VMrJi122QxNNRYYqXpIKyiguYo=,tag:1EBC6qRzWhnVnIPwvoWltw==,type:str]
    DB_USER: ENC[AES256_GCM,data:tHh3APJ50r3cPBgz/gA6rNhtJHA=,iv:m0himrWWus61rNXuxpmEkUCY2n/8YJQrunubboEeNwY=,tag:ENtwvxR3eSbTe6nRKgyYXA==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:5hvvONDPmawv2aluW5K6H+DEy4xPqT7Z,iv:O8kthwCfwXJ7w6Tx6wZs52Nswq45/WMOwpVZOZHoLaA=,tag:cUA5jK0oc49Eb/etOG7Tig==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:On07bXt3f84JyNo/RAVF57v84Fo=,iv:UMxjFErI99W1haK8+OYpxg3KIe9tsdhjI1AtJuL/h+M=,tag:t14+NgPXuPNCaCl4+EkKrQ==,type:str]
    MINIO_USERNAME: ENC[AES256_GCM,data:gnygeVf6vBvz0IxKu/jR8A==,iv:gHsRAw5KGr2x+snIDSKeJKeWQguxcLMf0zGVny6pd2I=,tag:9voXGUr6o/h5G0lYh15Dvg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:ZHLFJFT2P4L6/HdM+/MbfG+eR7XMt3pbG7O9VahjZiQzDkbmCkqwej62U6h57guQA+3waLPTp845HS+NicIf1/hbdWA=,iv:Vy442b8vO4IqqhWsVL5pHMJmlwCQb+48PBcOtD+oQL4=,tag:RZGfVMXWv49SU9Dqjf377A==,type:str]
    BUNNY_CDN_TOKEN: ENC[AES256_GCM,data:Bf8pnRUqvOVSLf5jxWiyoEjX4wIxfoR0Uivy8FdgWfRyK3GH9FGhflx/nIct6IQl,iv:25w+BhhZiiVUrPGdNflTC+5aWrXmWGn5pGo4k7fgsBg=,tag:uuv4evkiG1La4hHJLZ/Zsg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: caas-dev-secrets
    namespace: dev
sops:
    lastmodified: "2025-12-20T20:42:23Z"
    mac: ENC[AES256_GCM,data:yQ9k128xWcDDuuWSjl0bvJiNatkDKzUl1vODnIms9tTYsSQF8Vyx/DM22nVxp3a9FhkVj8lxwW44MFXr33gXZInJkp7NrSv1tQIY8Py+egea0vm90ydbGtjVViPgshUeAjokl12XXwVkeRU/Vh9t3VSNDxXqAymgEN8xNvxQHvY=,iv:kbxAPM+dGcHnv7c+VSEDrBV5tBYzkwVJ3Xm0afCiLDU=,tag:YIwIFOWbjTdi3pSzzUmGDw==,type:str]
    pgp:
        - created_at: "2025-12-20T20:42:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ//fbD0gDq2HYjWDcuDHEBY1pdEzr0ZD/KXHX+NK4/gylNz
            Bp5wbP8SyOVhMJKVcEbbg4AGtlDbDk0DfG9AL3KaAxNIuIwvKIJIezp9Ik3tsObZ
            xvjjwNwLwklBHHy9aFphf/V9fKkV7UTthT/dpy9n3P7WOrPf46sWje0pieO7xlIR
            ApWmLDAuTpyCeor/s8a5rjUlCnXIvrb0pTw8KuWDxTs7ZGN/Y2efV4Hf/xXqIFL+
            oOP9oYa4PxWYjH/l6+UAZiFdyEhznQDG0nFpSrILYkruIhgLMESI/JzAToFeMRxh
            QboFYWXg4K1hSeKT8ajoVo9pmPCPhD3DTspgGceLODb4Os61pnKiGH6QlUHWemDM
            UjzhnI5VsDI0FhGfx/IDOFEuCalG8d/wbYSz+d8ztfyK+EStEBDlTRIbT51aDCXx
            GCGtA58Ds4qV1yU3ipqB3fawCMeLFm5VrDZYqphD6CsRzeYoHWM6mo2vuuDJUzzH
            YKN+Ew3npiL3RmqMr0t/lp0bezqSHO3aUMZShY5zt5VPDpMf+OJd/+TnBFYNIPcc
            +NvabySDMNs01Lo/yjDjp5ca1hPapxEdt/+rol0KCv8Na75puc+cF2+YFDby8zcx
            Xx02hX/9W7t/VMssgF78cQVM3/LCH9UQ9q84Qgh4sRPgqRRSLLhKsWPauL3Rc9/U
            aAEJAhCwvcGdDsWebtdwztvqiu5ArHB2TRssYQw2vJGRjggGpvzpJg3ZrR3DZyAM
            TbVZt82DQHjCqbWxrBew2ONK4V0YcHv7L+r4IVtVEUqD/YkXQg/q8auED6D3ht2E
            tiDP7D1HdMps
            =oy9g
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
