apiVersion: v1
data:
  BUNNY_CDN_TOKEN: ENC[AES256_GCM,data:TarlfiJyTmpcwUEXI4nekJlTRvOEgqPKRs2/4SZXLVIt+/6klUTiRfR/DvHKRR5a,iv:vEor5GSmQ2M0GnLSliAo+4JEwPgttnzXJLdKHPOH1yc=,tag:HXTwsyTSIAjRId8UG74Y/Q==,type:str]
  DB_NAME: ENC[AES256_GCM,data:oISjuU1VsI1sNRPxs9rb6w==,iv:+La0nvHV/c07iPRkNDS6Y2hhNQ1amswaEtYUmEwIrGs=,tag:ooN1l+z/1uywWNh1TqF6zw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:lnRbgukyRjBthLkJiwDuSZSQbpE=,iv:Y1pHGuIK4FkCp2X0V545VRTsfIE74LelG7plkPXqKQ4=,tag:Gnd/c2kP995pyelwJqDioA==,type:str]
  DB_USER: ENC[AES256_GCM,data:euYQReDvhnDxv12pB4bC/hClO5M=,iv:2z9xP7JSNxcJpL2b2IoGIuOFEPyG2KZ840rzq+I5wEQ=,tag:mt/PXSZExRpiFInOZQEzSQ==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:Iq4ax7mm+l9xQtkGqx6sFAKytjwiLClN,iv:5BkXUxIZ7exBjCytg9hrjmqvheOdl7Y8BtThtYnHLWw=,tag:R8pKNlBKeno3YW9Hw4Q3Zw==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:sPWlhgeZmN+PLIQ+jkrlgDvq1WU=,iv:+E136aPTB3Chq9QaQdbzyjYDsDb6RsINvdoFUozJnVU=,tag:7PsFTOP68mhp60dAn1cw5g==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:Bdyhg0MZEzvM1WXpyVbKEA==,iv:mL3RYY0XLSJn2irJB8LXLbjOGJzjbWqYqpSs2a7Cin0=,tag:gKTYe9S1Z1JZ4jVZyPHTlg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:KZ/I9XT/P2K9yxa2TcsG0HJbE9lkoh5XR/M10t410Rus4AVXBlZjQSzz28OXUQZzYhbd3aru+I0Tc083fHa+B53XM+0=,iv:4sv0B0ETUEP+1C5tFlY5bfa3lBVwvBhd9tfu30BiFgQ=,tag:nUixRLRdPU8If1m7Cdh1eQ==,type:str]
  DJANGO_INTERNAL_TOKEN: ENC[AES256_GCM,data:EhPErobGNE0Jj7Q8GBVJ+MiQYcmp2809GBZaCaOl5CpSPjI9ni4+qrax+ZfRGaM9w8KYcYpsiEgzXQWTz+lMHeLgpUgoTjwWvam32iICPgZtthDXNJeCeg==,iv:SS4f9/yMu2NHsUcywvHk24aqlSBL01QRBTjeR13cr8Q=,tag:ET2x/vMNhK0O2psoKDuiLg==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: caas-dev-secrets
  namespace: dev
sops:
  lastmodified: "2025-12-23T20:09:36Z"
  mac: ENC[AES256_GCM,data:BDvN/5FK3Vj2IirfRPYpe0cjmKMnYMjeFSDvvrAx57ADo/omBjIYgRnKiHu3hNgk0rS+u99fdlL9hj02ZdtD9c535IKt3jYnX/FX/v4fW4VOkp67YQc8+0miFvS4QOPflfZQpU9NJMJ0KvujjDlkaBEyaH0Rfim2VhJOlXG80kI=,iv:Rxo62xV7i8rxkJ0T5fO7HFQUJ+nhl8+q/sHEd66pWb4=,tag:9OWEvYuBYw0xoOLnsPkyLw==,type:str]
  pgp:
    - created_at: "2025-12-23T20:09:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//fJ3V3WImHgWttkQ3oQABjAnI1OSbmSNvzqsvzRmCBXtC
        aIOMEdCrAuP3BtN+twNWNx8t24/5cZ1V2YlOm92HLgT3qHl3OWbPEW4bwiGAvzoV
        o9fXYsPi1XM3Ck2d7e5/zClI8i2ukaWsbaRVWxYrX3vli5909RoCQWE8Yvqg/8Ab
        VTlKl3OWdjujSdD1Pbt22CDl4igakcZ5McRF9OIj7FtBZnnwMgssBPmEJ42KQi0o
        hE8r8NzVjPGBrnUDGjtr5oY6EWbDf+HgyOfw3CQ6Oy/biK79PUpmA6TVCAQHYyvg
        n4OoyCKlTr62jHr5le+q3OE8MslBAFIhQZd355H8ulFf6/71jo685oFK+FzUFafn
        9iYrxRDqU2m8LKSOd4BGoepRGY03jimgTuXl/wY3HEG0GKpL4L5FrMdYKPm0Esis
        f1Lw8mykzyPP9Sy1z9n1b1FfqWsW65KJocLkP52rjRMHjL71dEfHPEmO+rExMjE3
        u1FmtcY0RJ1sOrToQbI6gvmS2ECjbWJOHUOPrU6m15cu1SGXccpnksiOHBcs3ld4
        cXqKCAh+3hP0BHG7wf1BbsQYqtE3oObtxDeSifjm/8d15iO1Am55sAMzw1A9R1Nu
        hScshbYUnQMyQv8AX1j/aV3Szsgqxj6mLPOJLUaa/1vghXPUJ/aywLsTx9R3cN7U
        aAEJAhBE3KiJnbs/U9RGIJZxwqilYXSWkKItCNGNJl/4qNt9n80wKsM5Ch3FUSTy
        ekaekE1V1DVMIvrl+c5xO6itGq/qOifrQ36uYG5IPTS08d+M9927GK+TWwKFWiEL
        wjilpSnDYe3w
        =vEaw
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
