apiVersion: v1
data:
    DJANGO_URL_PREFIX: ENC[AES256_GCM,data:cDQyJvfai9U4xhgME7Fb295NR51GzXv5ln6YZ2qbZQVJHr+IPHnXLynQwW8=,iv:VqM0j3FXkbPlwzbAvhKWaYaqpvLfVRafht1JM/pDojA=,tag:rhwAF6e4NOK0lEU67rWDDg==,type:str]
    DJANGO_INTERNAL_TOKEN: ENC[AES256_GCM,data:D081NHRg4zubagvnpJ/BOS/EroBnUzAl0gZuFFwfE7nE+3HKHHatf9e5GC2VqbvaAcJ/4YY9n2Bf42hH3caME7NaplcDsvgwO0FwSDFIsVVacaI+w+odzg==,iv:GjmYmdtuaAkWblaGp0TXh70qqPAKiIgrPbFpw+cknsQ=,tag:Kn3Lefeo68zdIRBNs8Cygw==,type:str]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:L594ezBUgsbeZX8JdHI7qA==,iv:BXoIp6qgVZRIu1TrVQZDiGKx05k6W/RvWgsqsCpuErw=,tag:QOcs0UIa968+O0fINwFKDg==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:ucdzWBqiCPcljUh7unVt8k3ZxZJ2u8OCNCN+yz7SDzcmGig51lREVS7RRGTFiUGk,iv:IZWSUbG00r9Vp1AHf1HYvqYz1aJ2gTejN7CkW1DgWkU=,tag:bcbsNHzwS3ygGBvJRhRDLw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:/ey5I8cr/doQ4mYplYJgOSMcYrk=,iv:+gszeQKhoSUWwJVzLxgIOneOR6iGng9QmzwWUQDvFVk=,tag:direWuyvNUC2iRqUrkCSBQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: transcoding-secrets
    namespace: dev
sops:
    lastmodified: "2025-12-19T21:00:06Z"
    mac: ENC[AES256_GCM,data:xnYeHu/UETRLwmWpe/bPSrSVSn0T/gnxWtHDngvoLkzBDvaIdrWBzERAPQrovY4x7MP4nSkE6qU+hTaYP/xobakCiW1PVoXF8SYWfpo543bWrNyz9S2VcSM7b+OIzjnfcd/KX1fXgEwwTeO897LfsACINCJND4MLygjiSd6ffAM=,iv:EjbPOVS1cOq3fYhv3VDDfW6Xaj7iHcO84MYx6JfJ32s=,tag:k7Ksa2domhjF71gLkAOflw==,type:str]
    pgp:
        - created_at: "2025-12-19T21:00:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ/9Fy72ozGafwiKGMLBjT1UpU9KipdhPUANIfT5uWfe5Xx6
            dGTbRFI8deZK5ZoT3dxtw+Ehn9Y2Evj3XZJidtHa2Hv0cE0izTES/JgfLnZHOUgG
            9KF7eEPotSp8Ml0xdpAIeR9GtNfU2V/4jKXFbs/+K397s69do61wI0XzVNz91lwa
            LVipDTCYeBbU0kpHYYn5Bijq6KRNJCNIF/BIzMJ6ulhX7s4qqfdH1P6zC0kfMzsD
            otx9okPb7vu5Jp+HGa9SvsJoE8YjHoI1iWr3WSoyl1jAjfHT9n3PaWF7cAUeiCVZ
            juUtuBMG0MjJyVElIrXzrSvNM9HB01pGCXdzMoPc69COlyRC8aWHcE6D/AGJbtpB
            cETnVh4ipIe4gSBBAP8IDC6oJLCEiuVyd4dePotT6ZGhxoULMr+gS8HNMzhpjWXC
            DEbfcVeLvhIod7RQMGB6iKKi2o8mIArXWUakWDcI8yYoEoWm6Dv5iUiltfbzInoj
            frqLNejsjfyisyFCsRKDUSA/dcDspqGfBClg+AVdrZqMeqm8f+3GFDlAfrPQ9dJ+
            OACpttWJCreolv2wlC6E0OatobmLZ+p7Y2C9QXuf3vqwA89gUnIi2lSOIx21lq60
            cjA/f6hseg26Dc9PAWTlesuzXiChDPh5mZVA+y50GvnoNNxWlQ59Fsbz3nPRySrU
            ZgEJAhC3Avt11TmRrMyR8Ey23doBT5s0wWN+lJf/RC7rw3MnmqlGa6IdAmIDNMVb
            bPL/sNQOxcOjOmF1J8EDQOLsP6HRQ5hPf8J8G+wqvYgwmbGXqrG0D+5JRzKqwN40
            a7ZwsbEDEA==
            =JCeN
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
