apiVersion: v1
data:
  DJANGO_URL_PREFIX: ENC[AES256_GCM,data:nDY9DHDflP3tqaFE+lV4gsDyC3u/wlAAI+7Q3s1mCWjq/TMsAbazL42RWi4=,iv:JTUzm+mSHFws1yI2NgGMjBMyN3EIL8XSp03WJwuzVjY=,tag:eCF0kff4JvMSTpZhjIeyNQ==,type:str]
  DJANGO_INTERNAL_TOKEN: ENC[AES256_GCM,data:sh92rHOkISq2oUfUIxzy58O0/+QMuJlwdNw5ewQIEfDWIiL7INext80eALqiJDZ7Am83AZIOgwYtAP8g5ZuC0ZZmu/ODIpQhmTsh16ASez6Kj5ZAgcInGw==,iv:UMKyCemKLjcJukZpoX09Fu8XNun3t0V0Y6JfPwhPTMg=,tag:O8zj0/HoHdVdwMn6luBdBw==,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:AnY4uJNCLEa1r8VjEbSXGg==,iv:MDDKbcRQ1jL5vH5aaPXVPdPjgkNtsDoXNjob81bWztg=,tag:aKsmVmx1MjUaJqO/mtu/eA==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:ZnBXJxo+aqy0Ys7Dz0BZfsxmWXRZtRpdNLPj1iA4yeR/Z4Xfb51hjI2/3AQ9vXwetsfywJIGumA=,iv:R0g8/gAGV1enYUSmDPVsQdnY28J5ioRhLh2Z39Kolu4=,tag:yVpj8OcZ8fBESfc2bnKzPw==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:3PVZDuGtTEvDNI1q0Dk/Te/MS4A=,iv:HuCeNJrPR/+FFfMzC0eWhMmkx4gvcWomi0beabhmLtY=,tag:u4ENZYK17zzplHTHkprUJA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: transcoding-secrets
  namespace: dev
sops:
  lastmodified: "2025-12-20T08:57:14Z"
  mac: ENC[AES256_GCM,data:Ck/Sth7pJ603sPCCBL0kKH8rp/ZP/dUBUgpUdpMQk+jt2RbntoT33Gt0v6KjEDV8IqnIvtvooSt+UjJhkooQorKbwFxQ3CSVknQ+u7KC67ADNOUcZPdlHj1wUiHo+BG4RfcH9mqc13nH/zaHjxXLT6gHGiGnP7v9a6ZD8hAVIHo=,iv:rZjjscgeNPNoadvhf0oSRlL2SUi4Uk69+HPmGNVlnt4=,tag:GDzKgmj31qlf20JUTm/RJw==,type:str]
  pgp:
    - created_at: "2025-12-20T08:57:14Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//R8Co6jqKkFDuPrKzsPKnrs+nuG2bqS7JtTErdnemMnFp
        MGzDAszOrpjNBMJxIAcmYknaYi27roXM7lWvcwpMxJBohKLx5uOXUNHPSxgD9wrw
        VHAtu6vG1nr7zVrGXFvbWO3CyY0C3tSY0/Deg7FfmMBrXJr+/TxmKSw+X8VB/4wF
        2PgN/0RX/HMn7YMWnBf2exnjNNDD6oATnOq96DaxcCREVjAxQQLJIOkrlCnYZUU1
        eRDHFf7Z/yE7+IaUtkdjfcTyJA1qKfPkftwLlhUopUPxwnKZRs3zGGR7kMLxaFDm
        iaMWgAzhp0SCQHi90rC1E0ugZix2UXdzf/QXTEyKb0476lpchUYpDLJScJqnLKNb
        dVgSHovjM7uQovjHXvPYtnkZis+sKGEg2PPLrh7AjzsydRQAWbGGTvN6ULm/dwZq
        PWjnddE/BwUea92kohKw3U2/gn217bo+AZ0O7in5jb5aIbrEg8sMbBgNZNDwxnXq
        3RrffTlO51dB82JLbh4b/nr8J3+mxvyOBfYeWwg+A2TjGLsjR0gdTdT823UGXSHH
        spORJy3mpsk5d2IyxKWAGvATloxfB4vTi3TQ/ObXGn2CAS67TUHg9CU8kAF8uq3R
        D4Df6kCA6tkN9R53Tn/FoCbSS8icOnHU1ViIIoLzrUhwDx0cF7ldSkaPJ0Kio0PU
        ZgEJAhBqZurK/DOGm+R7j0Sp5B/2Cz52D3KoZXGJiZtPFclU4XxAdKpzl8Gh9GjJ
        WzUs05A/G3SBTMxdKIbYbsJ/dz/KPbVG6nW+0URK0Q4za+MINBBP7okUb1IFN7TZ
        YLich06iJA==
        =Bejx
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
