apiVersion: v1
data:
  DJANGO_URL_PREFIX: ENC[AES256_GCM,data:6NF4mcgz/jYbFvai5vC73HOOtHuH01hUGGDsepDmTwfm0Wt/zuR1GyH6N4E=,iv:0hpqpl89RKiZAXAQ1BHNeZfA0VCbEz2pKJYn1iNcMko=,tag:qnw44NOPy8UVY2FuaQkEHA==,type:str]
  DJANGO_INTERNAL_TOKEN: ENC[AES256_GCM,data:KgYQfkVBImsFKwyGhaMTQ3n2FT68gEzvLqdEM5EdxHOqUhWaH/S4QrUfOX3gDvNKzoYWEOlOrSF6MYQ2IkXSxaB+qqex919Yi/Zk+qqJZCsqRDgfxoxJVQ==,iv:To+tALxTPlHZ5RHeFnfNtbGPwHH7h3E1hxtGuEN9zxY=,tag:hWm8CuXb0L9TmN/Ra+QGuA==,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:L0aizGlPaWJuNiNEMPDMjg==,iv:PvLSXeH9CvijdbgyNRHSOHJbmY14X7DGSLN80RwVqTc=,tag:/uwnlYhxnlVlMyedrAq9Ew==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:J2yhCdUZ3cwpAWayYPc4Tjl3BLebFZxpvCnpz5PPKEtVmoFcjHVIRH00q5+kG0JlN3KuUtBP5xQlpIrJaTeuXw==,iv:0JKZjBg12VdizFSxVS2amJfowneCidufLEBnrog7gXU=,tag:e4glRfNhGuC4XcEQj5Sx6Q==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:br19zjMaeNoiO9h4QlFsyqE7lrQ=,iv:Qbuykv8gMKMrU9FucsAQHGZ6GJyDQmP3GTYsRoj3h20=,tag:SSB6u8JBdWhSdBHGrIB1Ug==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: transcoding-secrets
  namespace: dev
sops:
  lastmodified: "2025-12-20T09:10:41Z"
  mac: ENC[AES256_GCM,data:lbCZfMBTg1AYe4cDG8P2ZVRKlxURjicZxHKsU2GXWCulgRXDuChO9JCYuRR/eeW0xsJjzg+yLLklghHGp1XdSHWnJw1IZo31yxUTTetr1orHd7XxsORmo92Efl+uKuMkeCjXuE8V3Hns6taIFh1yTPhBTP4Fma7BYAT6JqbB+Zs=,iv:d96xaKCdZ0vQi/vMk7upwVLnOe/xZ9fzTBRWl4GMebo=,tag:cIzHaZqDKL48u7Df2xcc/A==,type:str]
  pgp:
    - created_at: "2025-12-20T09:10:41Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//ap8kEUvwDEJWPwIeluPUDghuGStC5OXGJgnEj5JiFVst
        tAMUlA2btZU7EAnq/aTMohvakhlI8P3iGLGDuYvirO72ZFEYAXtb7ehzdbXyYp2r
        oAgHCRFKJnQQZ5HeqEZIH2pFRZR+xNbydV4h+6zErZzvBjxwX/BnAOMHpWlLxcbm
        YE77+Z3xYQSxevJ1M4CYFYyWh9qt/qqrxicmHvNTz3fTLYiR22Ltn1SLG+J59lgP
        SUrA25BUiZeAZhZX66bcsDQnBU5i0ldq6BXBWjf3DTItdzi/kv2UFtCMRXT2UFnt
        1E+Tpqofo3uOU2tKZFgiCgrwXwke5n0LT6pnPgC9ugsAwU48AaXpF2ZMrCCQE5Pw
        y6ayzi1jlyg+DlTWN2SnICXTyWmPXeArRd4I2Yg+fk3rCPC9WcT3glFY/m+gk8ry
        YD9SFZlfNcbeHXVjrLuggZK0kyDI3oHies76Ig/uF78szWmgMj3mMYhVBHUbVIWT
        IvKiKbfXhp2uALLJiQ0E6dp/7RQ6+Oxfr7RVknt84t91UBEISOguYgCLHy0CCesJ
        DiWoCVrHqVKVwAgsic61Pdcdbwis33BlcMhm+pkaFD2xOt598jLNDpmykJyfomtO
        2k36ehO4iNuhHD/CoZQTth2Z/cgd0Cg0Xil1rT483qMueT7T/j/yetEgep9BEivU
        aAEJAhBg0f7lvQLdtDPqFDHd7chUX5xMehY0YyUOr2AiahKNSDNIOkKWtZsqir7k
        Iqaqdvd32/7orMLPzcShIeAHO2fTUORn3RFuEcmHZQeW3/NNzaC1ojVy7jzTkq0F
        nJsP9Iy2YUT9
        =9eRd
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
