apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: percona-xtradb
  namespace: mysql
spec:
  interval: 5m
  dependsOn:
    - name: percona-operator
    - name: openebs
      namespace: storage
  chart:
    spec:
      chart: pxc-db
      version: "1.*" # or whatever version you want
      sourceRef:
        kind: HelmRepository
        name: percona-charts
        namespace: flux-system
  values:
    tls:
      enabled: true
    pxc:
      size: 3
      clusterSecretName: percona-xtradb-secrets
      persistence:
        enabled: true
        storageClass: "openebs-hostpath"
      configuration: |
        [mysqld]
        pxc_strict_mode=PERMISSIVE
    backup:
      enabled: true
      storages:
        minio:
          type: s3
          s3:
            bucket: pxc-backups
            region: us-east-1
            endpointUrl: http://myminio-hl.minio-tenant.svc.cluster.local:9000
            credentialsSecret: percona-minio-secrets
            insecureSkipTLSVerify: true # Cilium encryption
      schedule:
        - name: hourly
          schedule: "0 0 * * *"
          keep: 7
          storageName: minio
    users:
      - name: grafanaUser
        dbs:
          - grafana
        grants:
          - SELECT
          - INSERT
          - UPDATE
          - DELETE
          - CREATE
          - DROP
          - INDEX
          - ALTER
        passwordSecretRef:
          name: grafana-mysql-secrets
          key: database-password
      - name: Ranging8739 # muzbuild
        dbs:
          - muzbuild_db
        grants:
          - SELECT
          - INSERT
          - UPDATE
          - DELETE
          - CREATE
          - DROP
          - INDEX
          - ALTER
          - REFERENCES
        passwordSecretRef:
          name: muzbuild-mysql-secrets
          key: database-password
      - name: knoll6686 # caas
        dbs:
          - caas_db
        grants:
          - SELECT
          - INSERT
          - UPDATE
          - DELETE
          - CREATE
          - DROP
          - INDEX
          - ALTER
          - REFERENCES
        passwordSecretRef:
          name: caas-mysql-secrets
          key: database-password
      - name: Cathedral6737 # caas dev
        dbs:
          - caas_db_dev
        grants:
          - SELECT
          - INSERT
          - UPDATE
          - DELETE
          - CREATE
          - DROP
          - INDEX
          - ALTER
          - REFERENCES
        passwordSecretRef:
          name: caas-mysql-dev-secrets
          key: database-password
