apiVersion: v1
kind: Service
metadata:
  name: qirtaas-backend
  namespace: default
spec:
  selector:
    app: qirtaas-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
