apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  interval: 5m
  chart:
    spec:
      chart: tenant
      version: "7.1.*"
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
  values:
    tenant:
      pools:
        - servers: 4
          name: hot-pool-encrypted
          volumesPerServer: 1
          storageClassName: "hcloud-volumes-encrypted"
          size: 30Gi
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: v1.min.io/tenant
                        operator: In
                        values:
                          - myminio
                      - key: v1.min.io/pool
                        operator: In
                        values:
                          - hot-pool
                  topologyKey: "kubernetes.io/hostname"
      certificate:
        requestAutoCert: false
      configuration:
        name: custom-minio-user
      configSecret:
        name: custom-minio-user
        existingSecret: true
