apiVersion: batch/v1
kind: Job
metadata:
  name: caas-db-migration
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: caas-db-migration
          envFrom:
            - configMapRef:
                name: caas-config
            - secretRef:
                name: caas-secrets
      imagePullSecrets:
        - name: ghcr-secrets
