apiVersion: batch/v1
kind: Job
metadata:
  name: caas-db-migration
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: caas-db-migration
      imagePullSecrets:
        - name: ghcr-secrets
