apiVersion: batch/v1
kind: Job
metadata:
  name: qirtaas-db-migration
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: qirtaas-db-migration
          image: ghcr.io/alrimaal/qirtaas-backend:ephemeral
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: qirtaas-secrets
