# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas-frontend
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: caas-frontend
  template:
    metadata:
      labels:
        app: caas-frontend
    spec:
      containers:
        - name: caas-frontend
          image: ghcr.io/alrimaal/caas-frontend:0.0.83 # {"$imagepolicy": "default:caas-frontend"}
          imagePullPolicy: Always
          ports:
            - containerPort: 6021
      imagePullSecrets:
        - name: ghcr-secrets
