apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: caas-frontend
  namespace: default
spec:
  interval: 1m
  image: ghcr.io/alrimaal/caas-frontend
  secretRef:
    name: ghcr-secrets
