apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana/
  - openebs/
  - percona/
  - minio/
  - caas-frontend/overlays/prod/
  - image-automation/
  - qirtaas-frontend/overlays/prod/
  - qirtaas-frontend/overlays/dev/
  - elasticsearch/
