apiVersion: v1
kind: ConfigMap
metadata:
  name: qirtaas-config
  namespace: default
data:
  AUTOMATIC_EMAILS_ENABLED: "False"
  QURAN_API_BASE_URL: "https://apis-prelive.quran.foundation/content/api/v4"
  QURAN_OAUTH_TOKEN_URL: "https://prelive-oauth2.quran.foundation/oauth2/token"
  QURAN_OAUTH_REDIRECT_URI: "https://qirtaasdev.alrimaal.com/oauth/quran/callback"
  QURAN_POST_API_BASE_URL: "https://apis-prelive.quran.foundation/quran-reflect/v1"
  QURAN_USER_API_BASE_URL: "https://apis-prelive.quran.foundation/auth/v1"
  MINIO_SECURE: "True"
  MINIO_ENDPOINT: "minio.alrimaal.com"
  MINIO_BUCKET_NAME: "qirtaas-dev"
  RENDER_FRONTEND_ORIGIN: "https://qirtaasdev.alrimaal.com"
  MINIO_EPHEMERAL_BUCKET_NAME: "qirtaas-dev"
