apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - image-automation.yaml
  - image-policy.yaml
  - background/deployment.yaml
  - background/image-automation.yaml
  - background/image-policy.yaml
