apiVersion: v1
data:
  accessKey: ENC[AES256_GCM,data:sR/CBdKPtdhfMDrGMJwiBu/kkQYVuBv7HeuHWA==,iv:6fpMFyf+hlUzM16L1H0exQPUbD/8RMDe0aZhkgFUILQ=,tag:51YQu7kRiynbr35flJkt/g==,type:str]
  secretKey: ENC[AES256_GCM,data:so7rvNvvtdw9ZneXZT6+23G6l9A/0ywszTDQSSrNaYy3VI3ik2CRmY3Nns1fotIQn2MaDK8fCAA=,iv:HUenYhhV9A+8BEDStHVN/LCB01XsfTucVUpD3Z38upQ=,tag:JoincKF/wGHKhXCYFN+7lQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: aws-secrets
  namespace: minio
sops:
  lastmodified: "2026-08-18T09:29:06Z"
  mac: ENC[AES256_GCM,data:gR77QM+1cwAxymrBQLFj66IxCnxA14A34HFzomKCF0gme0zT+YmRLD+BJmSGk5gplfBy3F2R4w7J1c8KS6xOAKU71gU+HOF+kQEkRBdrIc4N+ziX7GG+aNg43neQJtuotH8nfdQtkJhrdi7xIh3RoC40xtwiLkPzIYGhcA5fhLI=,iv:G+/Uqe+qUH2vq6iIftbHdeqZ0MsvXfpBQpMecTRkS2o=,tag:18eTXsKx+bsK2wFD3pVDaw==,type:str]
  pgp:
    - created_at: "2026-08-18T09:29:06Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/9Ep/CyIQgaH4CR8FEYLfRKp9aWiEExS+rgzZTZpJLq4iA
        Z66aFk1JDESUVN9kARpam//f2z36rA1O0HrrVNe3bYtWXlo3d1EIeTtMzVEGpADH
        sT6V6hnP25Al9IRz+Co/j5eKF2xDthrzXwbhS77Ty3lqeC5GhCGlIKe6TuZKrKyR
        LGAxXyPYeRvkDHJpY15mSqxxGREosP3O0DYXqrnnnywHIwj55YCDDlrhhMK9uNll
        BZOobvfrap6xeVWfNuOl4zGyBUf+6+en63u/68t5wbJyI5k0BOa0qvMsSYktTViO
        r+qW9og5/jZ5ZJBJbejBU9Xw0rYuH7vXgtWHg/oTYibk6yoaD4LmV47NQNK4mEo2
        WKjpN/wPMxQoF32YS+POXYjtSq4Zxc3Fi/i6wNaCXk+FOnfX9CwxLffpOlPa820C
        hDzuM0o3LnPTHCFnwMGVLfPD5nhb7dp+5UloMZrr5/IMe2T9y08d4qrY94THHi7V
        8Q9PMPh/YkT3qh4Qz3AWHNx5XvRI2DCTReqexA4X1S0pEfivtyQJqJ4WQjM4aCln
        NNhLJP8E1+Jbt2SKzNCpK1iHdtmmZMxfPVL2G3tsykUuQaMXaWW8mpGqZsRcvlXH
        a7WMsy7xRebYORCie89VXe5FiGprWBeVoX18vrE+fKqIhzFgsJ37JJHFMvzTSfTU
        aAEJAhBsEs+g/DoyPJDrLWaMLAXwiCyO/d8vsSsGQ/6Pe4H5MfsbZ0DfD5zXJMcT
        uSTgAXj1VFKx7Wm86qu8txqJPsqbP5K5blg+AevPvZiub/j5jINpq3Sj/3jybV6G
        HQrrldWfKdFC
        =+RfD
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
