apiVersion: v1
data:
  accessKey: ENC[AES256_GCM,data:IjyJxcNgT1XPrckNFdYil+mQ8Qhc/3yXxPLAqw==,iv:XqAaImhkLndfFCEhzMG43f8VeIp3A29o0lue+etojgw=,tag:O64V19CYZuI2CttVPhP06A==,type:str]
  secretKey: ENC[AES256_GCM,data:Rk8hSJBrvMKTb0kkTt0UgOKWxXUZ4JjgxCEknFWSxEDtHusoi4fXLho5pY9/pQS1wRZ+/6ASv2A=,iv:ib/5mAZrRf8SXm/T8nGfTHV1yZJxF8rM3wPcePiV1H8=,tag:7o2C2VvPAgIO7tWAlVTSLA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: aws-secrets
  namespace: minio
sops:
  lastmodified: "2026-01-11T12:59:19Z"
  mac: ENC[AES256_GCM,data:cUvm87GRJvszf4+v/UB7ZJszl0Ap190kYpRhVibFtUzl3cwrtS6vctKxa4b+o64NvPO6ZkB19Co+blLWyrK3QuBlOj7INWV3ZkrYOd6OrrnCDWU2HTxkzGQIgbaLUUKyWEQVq8a4TcTJBfKjPf0uqcPr0aZzN3xHH0ZqUrWZsVc=,iv:5vyQ75CA3qFDYD4761UHjYIJSDbhzCZvli9mZQ9tyyc=,tag:KqSgE4uKeJvCWJz1dCNdZA==,type:str]
  pgp:
    - created_at: "2026-01-11T12:59:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAjjWrH79rtoCPkwMCJsO1UFelEVMbcIn8ZC12NdAa6G/S
        Obb+FE2x/Hug0SknrLTk6IJ4FyxM7ifQLSs4DPu6a+0aJ8a1yigrZZst227B8cSj
        B+tf6Qr3KpXlwHCUstZQT90+NOpERLPLh/bdlXwrTQ4pnhR+wPCLOxmNFanVhLkF
        4yyRWYfV2oHdiZBBaawgeg1y0MvTttKSdRPAkxlcuElhAFQGUCnGdBJcERmr++jO
        JO4ngc4Q3Ae4AYFJm1BibwiF+Pgv9uu6hhGWgW55uwCAyHPSmgoF/DQHsyWV7PMk
        sNtzO5KklByH3QOhnEoBz/DPA3YoGQ6RaFPuK3mfr1nURsmowl8RpQQx4hoFR8wG
        dp2/za9HzPJZozaN0QEN6g/JVuJBuChfAmXK4brXzIPANspmIh0NsYLQITORSmQR
        5lDgE/5ASRkzf0myDDZ8HFVFwtk24xbHbIm92DuUPYBGJRt0S5r/3laDZmc87sk+
        1Wi0njpmh/AuRKc/FZ10qmfy07c8AWaHxOuCHqfjDqYAxMENt40C147o+WFr3Ld5
        vDargCRRMTzYru0C2zdx4B7suUSMRU4O+BDhTigeI/tXI5bSv0E/0ZFUDhYVzxcJ
        dX7TVOOZKf/xLc6eqP59d94MYtyYekPUIe66LmEVtH7wQ0E9Pmr2sRoVoNUUxfzU
        aAEJAhBYRMo6bGmqp8iL8dTsEUNRGofMeuNwvOCE+NHmo6j+kihfRUFEDdvSB/8T
        Kfkja5NFTOcfCgyhJDHVxKhrQr/oNEaKMvSfgR6YbpMxA+kQq+xcU3pV3i4EJakY
        6rwind0XyPCy
        =nzHT
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
