apiVersion: v1
data:
  database-password: ENC[AES256_GCM,data:xfDGDvz0yEmpFnejPfEeLKVUAuA=,iv:fBZCig6+Ow8akat4CtBgA93hNlOBPiXGVVMcrTzDzms=,tag:qZSXRQzHuGxxK9/BqXzLBA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: caas-mysql-dev-secrets
  namespace: mysql
sops:
  lastmodified: "2025-11-28T14:38:24Z"
  mac: ENC[AES256_GCM,data:9PdKYPM0RMORKrwE2dULanfYNx26NX1951JyH9FB15cMbGEmahpJVmgJ+elT8Kf/otKA4bj/jB4HDcIZXfzgjr/pOC5P8bCr0RUHsZoXY0xb+l7BbMBX7+YjcLD8z7kLvsoI3xdOQlikFfxNu5YXqihJa/s2H/sfxFiDS/6k+kc=,iv:0FNtnw1fNozJD3CBAyLwmZLaVVY5wtxJSPn/RoAJ5SA=,tag:J+Lf8oSkEijSey0IRKOQhg==,type:str]
  pgp:
    - created_at: "2025-11-28T14:38:24Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAjJ/cjHe23OyHVvDnzG4iDmp9p77irGG2cUnQzFCoXbL1
        LWFi+Ldn9Quhx4gzZNW6RQRyHhMqdba1C9yUynrLQAfpKAUFVcRT5CDoKXH5WnDi
        CLg8lqpujKYSDM6SUHCY39haw9yg6vHjpwJiKY4sESZ6Ua2J01cHc+ezgfCyKQfS
        Y6ZOGrajlck919/Kv9rEyLT/tL3QeesiI9YxARPecaNUXH0R9vX04fb20KZhFNbS
        ll1lvabfVE0lv34LbgsOwu3FOve/VLQZH2nUrDW1amy8WmqNjKP0D9rNWL803S6P
        xpeUeERywVOzkNDKB801RZrq+vSjynVXJsdhATCC++BzX4Mt1uzbRuOAyj7/PaSn
        YSQRIjzqnEoDxRq2vJvOfHMI9aTOWoQoNzSjSP5GCGM/xe4bNu65S/gJBTpE9uz7
        M6ikTIcEv8rwOkeDQMup3xlhNxBIBLsUG6FYUBx3v3CmFhglFA4i6RLJ82PLSwnk
        tKfNNRcRxuyvl2Sw8BGzHsTRSryehCogOpI+5LIHBN6w1PnE6u44G0H5cnixVNEE
        Qg29qh87gCTO3Ep8qdaKICg9WjdFBMAQe0TpKDquhjY1mM1mge2Gbm9JeZUWSdrt
        kCgWkuDbLreYMkps2Nksvwa8zStn1XEuIZmNxnjbVw7Lsy/rYYOmiyFMh9YUkVvU
        ZgEJAhDaErZSrPrr1eFff/msstHLBcwccxE/tWeyNxYeaoZmB6rk56qfN0QGKtzY
        0sZbOegWnoLbZ5TsWOx2b86RCqm4ULUQhgydK2Vj9bCdllUMd3wn42cbidW3wG9X
        A+sHfHCz+w==
        =Yppz
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
