apiVersion: v1
data:
    DB_NAME: ENC[AES256_GCM,data:pEDLUBpF81aWsf8bfGFQgA==,iv:rp7zfkyRYK6u76Sm+8qc8uoq9lquOt0+8xD42t0+1kw=,tag:cFvCFOMcXsfbDaQyvgvqzw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:GbDNWjYA6lCiEA+oL0pYGS7f1FM=,iv:RUyE3hy5G6o6fsiDalNg/RBagd3IPV6X/mbhV49sMk8=,tag:/l/FDrM7cHN4siHkVRc/JQ==,type:str]
    DB_USER: ENC[AES256_GCM,data:5rMySBvv+NhSa7HjHTdFR2TpDpk=,iv:VWI8AvEnzkES7Ppusgq/wiusWh4eEPWzkWOqUL3S+gw=,tag:LnYB7i13rZsqX2nSXJyO7g==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:Aw1tJ6jCjna9q4JAiIcTlopJ5ZSDo5lX,iv:YsVCMnAakrkCx1zX0ngf2I7ZhCFUmDet6fvaAmiWwgk=,tag:E3oWV15FpQmHS+BIt2i7OA==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:LRVrWF0B9Iq47Dhn7CkbvieWc68=,iv:xSHnyJbso7OppvDWnHFKjfulqu9VLjkHubBpUArSx2Y=,tag:q/YQkvQY6EPC5rO+/4eYAw==,type:str]
    MINIO_USERNAME: ENC[AES256_GCM,data:YY6CngJZnhsnpLiIWj5m/g==,iv:P/nF6VkMWYqGPUDLXWpBT2Uukm0FC5c/aNUeW8KnHfw=,tag:DW3fsguiilfEGp5sfuZZzw==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:8j1e0ae1G8teZWtp9FQjSK5oZd67cw8aQa1kz3hczNRzFj6OovNQ7OkO54ksZdlXvDOSlzabXodv7V7o2bTubjnzH2M=,iv:+t0e3JNr+OjuMoQNaahwdm7EtXMRtP54l9Njh5DjbvQ=,tag:nkSaq8lxuWgkWO52R5OT+g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: caas-dev-secrets
    namespace: dev
sops:
    lastmodified: "2025-11-28T14:50:27Z"
    mac: ENC[AES256_GCM,data:k3iUSnRCq65la2YTFV0HRAruB8yoFbgzLXOHDm1QEDa+/QzWDEyt5IvBzFOV/bc9bz3aQrjJpY/gY/Cz8C4vAoFZELILk9drXyZ6I+MqSFfQBlepOnPqee1Dxcek7wKggIr9FK0PTgTTI+tr0EJwzykoDm/C/E5/nhzhRgOSiuk=,iv:kfKRTaRG3jISpH6HRQb+4jZ6u+ohEu+zbN7Rj8ZxjvQ=,tag:shrgKTyVx0tXTjTHj+pvkA==,type:str]
    pgp:
        - created_at: "2025-11-28T14:50:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ//dOcQkH5I6Gf17XzDdMRGV9VSy9JY2yVxUVjwW8t559jE
            4ipIVnrjZCOXVcPC4PBCTFzaRZTttxpcunWdjhCsUjpP7Smmt4it2unYOaRxLgdJ
            46Ysgw4oHLplUSEqEwB9yktgGWyrUMElwyzYr5NLmQ/xXIcJPaXZz183nf3crTju
            fzU+NL+BXMa1MTRaM/I0Y9ysU5zNGB2/VqZAMwwRMGuKXLJjS+xvmDDHNGqa8ZGr
            EUUMXd32GWR0XXenUbadbLwtuTbeNZK3L2RPJox0sGKbGDYto02uFi/e2kY+Uoo5
            /ts2HSYdo7ICrcNLiRHpS1+ddREswvW28+u2N04UtjI/6PzSmPJ/u9fMmz3hv3Ho
            Ne85i8dsC5gZRtkCmf0+C9GgRs65/8CWMdxyvRmVLrx+cOlM/KljLWH1ijunHN/D
            PWa2YZuhl+XXHvjNi9DYV4lG9TWngT5NE3Lg+4DrC2/6YSCo0dWyTcInZLknNRLs
            FlH8Dp/6BmZVaBztuSSQMnz1fFW736JviW7SL371A3XZGEK+bmLaVj2bsrj97Jh6
            AVSmZA6qJIAWq4yEWfLgg+koVS6lkMRUNXQuE0ev7zaVaa1Vfpx7ArZXbrjpOk2H
            6VAdza4mgdesjEESx/9oeXUF6CcVSYFE0pCfKPYK0VQKPnyTWiL6VFzQN2IG9HzU
            aAEJAhCHAcR+YNBxqd02/cOSbocwMzmEg33tbtLXY/8Np4VtDFRC9nMKRxLQjQvH
            7NyF3mU/YCwVcbZmlakN7ve7F5Ry1PBHS5lJeCghHPQdrP1Cv7KgmnzieA7kE4BA
            2Swqen3kX83C
            =WbG4
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
