apiVersion: v1
data:
  database-password: ENC[AES256_GCM,data:zA4KdptQ9pdeEApnK6GkEsargYY=,iv:9iNkovteT+NSBJUEv387JA471Ubsyp8N0atIE59Mq/E=,tag:zMPS31VrBBsXzPJ8UBK5YA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: caas-mysql-secrets
  namespace: mysql
sops:
  lastmodified: "2025-11-19T22:19:44Z"
  mac: ENC[AES256_GCM,data:ipIzJ4F3FI41NUbpzp0HvJGEKrhHK2nz1XW/YdbmQ5lOXFYpRStfdwlMljzhxS5wibWNUJW88poVN1TiIC/Kfsp408FU1wsZR0rJcainrTA46ct8Wj1kK5T1exgyG07QFFHioHf08Cwipe45xHvvlwYEaq3vt8hlJ0iXktiX37w=,iv:4x7EIWJgZu4byuwj4l1/CfzN7TqbN1/THsDh22Yn9xI=,tag:CHztmVJeqIzkbZBQQzJS5w==,type:str]
  pgp:
    - created_at: "2025-11-19T22:19:44Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAArjmzkiql7nZR7AvUy/QwVZeiaeohcc2VgNwTYAlRBwf3
        n0FDzzFmqLxFMv6G+/GW01lMPkD9y02NrJJz9Tupv8bpk6wUTv7nxqQDDIpbrrxA
        3TfrqBFl8YKvb8m3kmnDe1Ie8dBZgwMcohLc9BZVeh2hxO1TKM+2hG9Lwd2rfQjX
        QyiTi9OKC35GmI6J5kraGs3AHBQkLRLEVaxdgGV847IcaPt5c6YszCaklolEUQlU
        +kgezOJ1mdhUleGqKQ6XHcjheH+8VVe7W8bcRDGyjGlqnfoJll8xmUY5p/rJzfpT
        turceh/9WaP0iA0dLBbfJxuO8REEEn71tOT1qge1ijqq8La0/Oe9R3oJ83km4WvV
        ZLBbh6LfBt6YZEm7FvKyVKG+InQnIWIiMVbu/FbNsTMTXvFUPl/mUV9Um1i02pPu
        Or6waN9hskTDUrAvdFPCC/hFT4fRu47Aa+nOItp8U0yUXqWrTfbdwSnh2rQT5bxM
        Lq3P44GIcmzIG/YqVb1ziFRVZzT6Qz+Glo7kRIOChkj0ZN+YsuhAun0HW091wbCw
        TMwQXOaLNsQ/f7tPPYDqpj93AqoAQLr8sRSCErohhI+WpMlIO2h9AXN2p85LencQ
        6RMVd/+j4DIzVwoY/GnzGz65EvkfufM/Am/CrDLcdgwZmYw1J5+B0rnogzyj2UvU
        aAEJAhDOesD9Zv4e2iwd2FHwmPEIJP1SwNgIOqHjeHePD75ds1eYLPdHru4l0ikV
        23ivjNPOvLkPs/RIBfMSz4rDulGLOsf11JNn49wqnlqNajYcCl+PcEcJi4Mm5X+4
        TfZPOcK09aEj
        =pP4F
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
