apiVersion: v1
data:
  database-password: ENC[AES256_GCM,data:6aX4HY5ca4peBICF6FI=,iv:HkB3SBp2Rq/jgYG+bphJnaSYkyAXUzHZsmeCapNwQSQ=,tag:nQ56g8JoN098jpuz/fad3g==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: muzbuild-mysql-secrets
  namespace: mysql
sops:
  lastmodified: "2025-11-19T21:45:26Z"
  mac: ENC[AES256_GCM,data:9zkBBGUfq8LyLoa7ahoLH03dEQlTe8aV0E3ao9dupAljnFGGnQGkOz6ACZdWKloddAsCUa7yg1xu0BnGIwGDrTgdYQ8KTr89xf9FfXJ3XIgOG4hTxYMf/6be9UV7XW8c+fEnOsVHZo7LY/dCEwVDGws/AugzWXveAozba+gPE1g=,iv:+tdGIC4xt0anigAX7tRlkIKJIasNwSu2yJV5NEb+3Rk=,tag:WpOdczRi8u8XKe20N0aKnw==,type:str]
  pgp:
    - created_at: "2025-11-19T21:45:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAiVha7GZWK2WnG2lMJQoQYCjCjy3FJ/HWXA+RMDoLG6qg
        ANKFJc2gGWUMmoM+R06TO7cfZRHuxvhuwn0eqDJ8Umlsb3CFWwlp0Fe2gxOWvzfH
        XlHfJL620CfRoE+8Fv4LldfHKeDyL4i0sgdaVxNKiwkhejvp+pTM5q2tgw+XDQUY
        CFkG893kmPnVk8xEpv/H/c77McFof8lh1o4KURluaRjXSIosg+P0kTwK5yT8jF3L
        Y9W0gGlSP6DWMvwEBQWLeKU1ote3+g5Prosb8vw+bha6eCcd3F9wDdd/jPaVuPz7
        K0s5OBXsXYsNhDfxk+CiHibI8t7HakfKUbgGwgnrU6Y6rbJRzCbxKrh+eRrmi+8C
        5CYgkolrYdfQv3uOGKx0XPofQ/mzkpP2CbaKfJDWkJoGHGmRrBsaRoYb2IvMbt93
        PQwFrvzCQUFfFGUNsAzmp/+5Ms9RWkN1zmz/ptT+pLvW2xRo4ruYAF+kylj+hOcX
        iCScQSfHVi/NKXw1Wur1V9nhuAmwQYUH9q5B+OYkypRLt+xgeiVJMIThW252plCj
        Ld2slacCbK2tBWiHvh9C1jLU7zH7wmT2+Zae+1E1iE5X3Vl2ns0vVjwPv1LPTW2v
        +SaqAsyXw6jVFSMDR63DXvszG3uLA14RkvOL9VOGkF2VFNSzUrf2cwnDy1/L3FDU
        aAEJAhAbSzex47STJIsit2ul1lAV3tYA+V8GopaTA/5UiBvxtdDH2gLUfrMyHRAQ
        Jqm8E/pzm+Y2a6sC9gOTG/ptQRrd3XkRGWsr5SSULyOGUQtWw3BghKN7xDS/b8kW
        Tou4Vv5jqPjU
        =IdYA
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
