apiVersion: v1
data:
  api-token: ENC[AES256_GCM,data:q0wrSw3qhTI8tL1pYf33OLB+Ii0MCPPcjE9GZQqri1nmBZczqhp3OvDlciU=,iv:d4hmQPSxdWnDEC5DZm4JAnGlKsH0gYa0kx1Fdb+drJo=,tag:YzDa9aG/fRape1H12+umeQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secrets
  namespace: cert-manager
sops:
  lastmodified: "2026-06-01T07:32:08Z"
  mac: ENC[AES256_GCM,data:sYGOsRQKiY3AYZqWNo/m44MMFCWnOoq/l8qShIe+mauvAmLdhex4t7+0e0A9pbj+OsoUm9vV32zALbzPM44m5LuIYYILF78HcfaKHuTK6acUiEBYmugyaQoE/RsR94ekWhxYrlmUk77InJD2ZWz3n0qau9ctrA4yfgzuSpevl7I=,iv:uuK1yajcKkXuzWmSIu6PjywhiqehFKeLNba4yNDRRkg=,tag:RnNGcszSJj7V8xTdhH2t8A==,type:str]
  pgp:
    - created_at: "2026-06-01T07:32:08Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAlmNjrlf5JXxImpD/LYJshsYKbXfcoU75kUi5G7P08q7y
        RioFp7sru4B9N+dkIHKCMBKvYREPogzWv2LDpkvm4ihK4cr+hO85QvMaxd5TqWE+
        EohCaJUL2kD1BJBwaFpVJtNAcIhfxbbuy6nKz4dQjWda8yNtk4aDfVkbiTisAkDH
        lOeRUXwgiWdWJtMypen907fJaXHzqlIVueG5PrG0ZzX+cznKSOvyQ21+laECjFgt
        PZcgI9GOWuUxDViuDxPmLlAOvoOoy1gXvxgB6uHFSwRgQgBYgP1cqgYPu53sRym2
        MG5d3REW7BWQNw6eSwhS5XbJ9JKjlezYvRpCzKfWhejtHvMi80w4fBWljPfyLgVA
        ipBx2VZrFyK1nc6YaJZUETpv4CnwvFY0n7M75iJQHPAKKQME1OdkKIZbxktL5MOw
        TF9gnWzi/c4UKYtRJeFGqiMMdc9Z8Ml12lPvASBa4SQLgzv42/uX+BMHhIhOQBo1
        57GU2z5msAph94ve6MYmoRBV/Iy83HZWkPK2JJXYGhph1Df2BQL9xSiACI8cTOjo
        8RVt2HP+PPWb0Ms95a0pxwTZ25wiwROp+cDtIGgZaFTiLKJdjiqA0lLFEhOaAP/c
        kc30SkM36nmgzDKgjx3CiywQHO5Z/sDzJcmxSxQSjt4KPYlO/l19t8tuJDyVhP/U
        aAEJAhC5KGcMZV10fmRBcS7YZKlCw7K8xv623PzzoTj/ZgvX1n7Wyqwij/xQJ5Je
        EwEGuzGi8pQ4bCu56Y1UD+EjoprULT8TtEeOkh+xRijohjLEUCo96OcIi6zuHq/4
        hhJrENIMRC1M
        =IHvG
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
