apiVersion: v1
data:
  api-token: ENC[AES256_GCM,data:yo+/4oppDSrtfJWfot//t0gq9o0BEGPaxf6phPjlgVD/MzjY0fKnkty9I5nrp4ZRvsm7XlDNpA9WVOTcvxo1rsswmZD4Yeco,iv:0mPKPsk72h1zLAR7+3uOPzOMzyT4SiUTumzAwXaPlSo=,tag:iKjvAdlSs8kuJuPm9nEg2w==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secrets
  namespace: cert-manager
sops:
  lastmodified: "2026-06-01T07:48:13Z"
  mac: ENC[AES256_GCM,data:lUUE/rEyT1h4EsOy1fe6fuRIpzKMwxyQL6B4cBKXX7xQvQTDJlBcMK08hgy69KaRv8vy5TK05LCDgPTGtkxW2A+Uks0TBNrWfslFAjZA6Ll4ma3eVARi2rsnFa5AeE4l9sDYAT7Zel1oIuA1aeWp9t73TtpNwpp10XORdlCBzBM=,iv:5fUjMQKvW7EKgEFiHl7XL0NmTiaINl/9D9eepy/gE0c=,tag:TS4jVHN5z0Fb5STuQGIUUg==,type:str]
  pgp:
    - created_at: "2026-06-01T07:48:13Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//V4RcCtnZR7guaKHF3IO0/KDOxdQbBsTmE/xCs+MCdg+6
        OTBjzR3ylrUzkgo2DD/YYIPEiwIFQOunJpoVSM9IgGXecBUeFrzj7aDbZ6fhMfvZ
        mAxHMg684ECf0FZI7pF5DuI87Jyj6ZDt/44SrLgQw+zVf2AYV/m+lLNde3aRUKFM
        BQM7bubhb8Gftia7m2Bvcimf+Eq7ECMh/1qXzO70aoQG9eCxrLPymV7wEoU5nzt+
        vKZB+nfxGnFKML2tyMK+UsXu4dlW3L47EvihP+zbBsIn4i5KosUivV8NkYAVSGBx
        BRwNpH0kVnapBDtIfJUAt0WlWpb71mi+UtT8MKPsq0ISbSWFaDretA2wVLdVD1qX
        vwhixLSewduCWkqRpYfD94DiRO76JFAlatMi9dqqTQQNoVTf2DFBHu+ysmOPc4HD
        gQpKiCLj1kj0dkRqw2tM0ppJ9Xo4yINGZnUl1Y1isX//uo6MFtnMsYZo+xi6qPKi
        ea2QHdzix8kqCMVzJGOz+HepUXyiCU7K8GGQfTKhoRt+J80kKcNnYwMJtgI8ZWHm
        xGERvVTy4Ck3aziou9Fi4i4crUcvx0+A81FaT4VmGt5X2cV5eOqRxjRRSf8jhy2F
        Ar0TznsAC4ZzxVtElQccyLNtQTzLSG8w8Vi5/Y6veBeoBm7gbkFLOZV2mWnj5ybU
        aAEJAhCLTx2f3C9QtFSYAarep63KkhlFr7TTnzAYwMuy8ccHdmIfW0bur+TYC6P6
        gXtdgoDHY58sLcwvHYbLKEFLeLuzJBFeO6Tm8MYbSIHhCugx7ie1GszWNjrsSzSw
        A4Mdkv80QDGw
        =SlpK
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
