apiVersion: v1
kind: Secret
metadata:
  name: csi-encryption-secret
  namespace: kube-system
stringData:
  encryption-passphrase: ENC[AES256_GCM,data:cKfW18icMqtHIs4gGnfsKphdm7VEh7dlck8vnDO+TqhWBYQnY6RY9VWAZEu6F4geU1iAdA==,iv:AfW+uzLyNyNQVIj1s+TNVmaKA1HyfBMJkt9uLc4cXag=,tag:reJYT3/YESntXEBhgDqgvQ==,type:str]
sops:
  lastmodified: "2026-09-06T17:28:06Z"
  mac: ENC[AES256_GCM,data:VTJRBhreQCN44PaGydo/Zr05Uvdvg8zN93IeSCai7y2tetj0E6r94zu3HtKj6gPzfE+QfNe1H/uumOtwOu/FpwPjXTI4yjT88lM6pqd25wnQxr6eIR4ca7RIfMsSqxN/BfZ75QQvFThjNhiec3tidtt4jZcxKsERmpnKdyXqG9g=,iv:4om2rFWpGsxmtYHVWazYeSxgmX5QhfgX5cogaMN/Jbo=,tag:HPgVEZF2iYG9auzt9MFWCw==,type:str]
  pgp:
    - created_at: "2026-09-06T17:28:05Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//ZWsEgc/SOhPyKCu0ZMCriKqo+mjkOxZ4rsiebJiFie+d
        Gd3eTdUzfqrIOLglAawAh6MV71ajdqyo82ElMrKheRRmbTlP3QMtz6kCE9FoC7KN
        t4XXZk/Ds/wPvqOT+nhtWoLGg37OQqKceF12YB606KB7+W/2b43uWaWZzVsDF9FR
        UzOn+1zySY4a3lWdb5G0pqwhy/N4ckZYdxVPpeMvfZ2SXWQvOOii13KxY1ofqb11
        iWt72rXkTwcdhO/1UAkuprksB3vO33VEtkjX5WsE7yVGKOgm03wisM1hemcev2FI
        LluvywwcTYxVCWHFaWYuFKWlWh3HkJBcCuxh9pUFplRbX17IvdfOp5r4x9J9sYkF
        WUYtNOrdnGXtERxqbzRaM+FnNlcXKfrSyseH6KU4g4n/fq6WHQL8rKfI0hSisXLX
        Wfs6a41Q5YhqljwsHcj3r0oAQyPyNXrIaKlhPtjSlJJQKlErGQ177HHGdQG67rEu
        ieb4TLGbOAMIGa67EfjN2O3OuYtkhAs/CnjALiJQz/WcUXnf4pyPo45gQ4FexaOL
        8IaAKRZ7vCgnMmf4xn5P72Kkc010jC44i8hO6m92OGgLUaglPKbJTmOa19Qc2sLc
        VDIJ9ZuuzZtbxm92P3hUlDZ2H3eYEcWXOCm8nWeZLpLWJ4uHdYRtfRE7KQYY6CzU
        aAEJAhDMWGyvbXVmECNMSTNJt2RvSJyq7nu20ypaiHqSEZGjsTzd010wLQkCGwSv
        E8nPXz8KpyT+g6Jd+Iaak+CXJN+N82qYxweX7rJK0XTXcO14feMJJyS0MyX3vJ78
        hC4zLemmcQMr
        =wfMz
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
