apiVersion: v1
data:
    config.env: ENC[AES256_GCM,data:ey/Huyt09fHIYwZ+takdW55eg8IzIO2MOG4cBqVzhr0u1NHwkEhkP8cIXSX7nKhNTweofnbshhqaUdmsmPrAat5FlLheiWWn5QHLEWs7IUmGN+/hyNrk9HG6u3KBfKFTq/g0EjPJijEqC1/3qHnPKQ==,iv:wog6n7KZklXvNyBZY8UEmbarbI9iWWBUIQohtmEzJ4w=,tag:Cz9O1xG7N48cAFRoiw/gzw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: custom-minio-user.yaml
    namespace: minio-tenant
sops:
    lastmodified: "2025-09-08T18:34:45Z"
    mac: ENC[AES256_GCM,data:fGb2nwnzZtyN0RCUxUcdUfqaPtOhV8miPLtOTNLhr+uY/J7RIRYw4gS02WHfhVGXFHLWk+G5hRsq648uH7ys0/6Yc0hVq7fDM/ZC4a3fdNHn+QewFRAYTHT96Jqpi4JSTeW385Q4PJE3kRqNdb7MTzVQ5jFLTTMtU3ElItkfMGM=,iv:O0kMv7Dl8ocLTLZ0M6OlP6jpXFVZ9NqWr+UAnd4Apps=,tag:88zf7YNF+KSEyJYRhyGHLQ==,type:str]
    pgp:
        - created_at: "2025-09-08T18:34:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ//Un5VF9L8CJc+UKg00vSCY1XIacfi+Dqtepjf1HEPZlW4
            Ys0WimthK7sDMG1wLf+aqkBbaLSWZSwkQMpmoUMULQWywu2BOPZaIMetZCaU9DG4
            z2Xj/dF0rltow83dDCAMZfkt980xtAXcI79pO+z02dhrAPS79PG8C6RNABU9kf37
            veoiyvdsqc888tgwM359CDtlIl8GzI94BldjSFn+Oy0aBMfiHzfg/p3e5xKxPOl/
            3Lii2vCpzQE5CJeVQ/WHnRsZTt+aZuool6DPTeY/gV969CDlbomagUnnn7bZ+xDb
            txldLIdEMeituKiAqZI63LuRQtJdvzldWv4R6wMM4WW5PZV7WA5GZcpNTDA809bL
            2eGFSpXxxX56VrG2EjgldFFYKbz4NnLyyKcnTmLxvTsoAED/jk2k0GRirGDFW/bB
            c0jxW8HbNtLu7DwtnM6murLbLXgc98EIFlAdkzyEKMZV1F7Nz4sDXVTaYjv1g1zU
            77RSGCnM9RqKxOgKm7qbzChUEh3lhMttXELf5oLZxt/wj7LkCQTqenBz0WrPfmMP
            6CwqGDQByLnuxd2CZOXtF3glxhRFbwYOyp134m0f1y8jeND6oAXcmM62mItk6JgL
            imvG7XzujDvViexkLL9SKz9SJVwUQgNnoLxH4EFUkYnAs7ThtU30NurBk4uxNxjU
            ZgEJAhAfpTf8S751CB6TOONNRjPFrQo9UFoqAP34bTKzuCXTjRYqpc1GozrV4ezL
            kv3wQT7CEFqUxk0KYIcUFNBEAAjZeGNX0WHWgu7IVdWnVVSlzruDxbuiERjM7TmG
            myfW1nbs4w==
            =C91l
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
