apiVersion: v1
data:
  password: ENC[AES256_GCM,data:UzRK2Zz2UsvucqmbWTbIwLkx5fM=,iv:Et8Ra5YYpoitU9tpkB5T0oSW85+cqv+WMdyIVE7l7nQ=,tag:N7NqV96O4WR1AHDFThRNJA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: elasticsearch-secrets
  namespace: elasticsearch
sops:
  lastmodified: "2026-03-28T16:48:09Z"
  mac: ENC[AES256_GCM,data:x498HaBp4fYIJqDcbdLDkeRqtDLxDfp30JLUUF52dkJ0uje6Wx6y1RBD0qvJdaMullkmy/O9NnfjMyUmhpIygKsT7EVrbnMRvWpoV3GbkArD/IowJa8JqwO2VLwTq6F/LyM37oDsyH+3HbKkg5Sbv1EVPPiCYcRiia0i3kUiGS8=,iv:OCisSpYurgprBISAFoYw0Reu1/sSaf+JMsv4U5zQLmk=,tag:DroJWRlkZ+daRh4ECJEZ4A==,type:str]
  pgp:
    - created_at: "2026-03-28T16:48:09Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/6Aj79v9/Tjcqsch7rHqfdGya/5u4PL4NJewrdUlPsxC+6
        +m5zRNSyEue5Dt8dhvAinVNcdY8m3zpGiA7sEU2mJCrwceCG6wAqECUrVfDh1gvJ
        mGvNW2zCP8Hx+mVsS99mW8mcodsPH5qelslDR3TFzKlX+nELfuGwG5x10ar/pT8S
        H4g+9GcC2USYKQGYpOhCppKuT1HIpXvUKwbICifbSgmxhtSnABhtAL7OfHZyLiQP
        tELCjV9LQOlt9gwgz4MNgRAL+4c0shKnmiWGmH/N0+5oQxcqLg33BLVv0jJxNK53
        wKBpSmbHfLOJoOnK7VRsD3zf41qbHd9tkbDBU2QFpBo9ve9vlqTbLg87zmp3AHNF
        GMxF8V5TjWhvOhdSKFIFHHkUK7r+ICqwxLfVNjviuCo7k6sZRrpr/KT4YmOEPjro
        tx3vM4XDS3UYeGtfAitU4/aHCbcjcx8ATv5fL3UJBZ5dCF2n/VWkOQfEl95Gah24
        Am915syHGcN4o3Qh2Poq0ML6aNaZsAZ79XLjASTPjEVw3UQk4TnXgetzvLbvzwBL
        sH1SsBzo44YZ/MRE08G3COsf5SbWMNbCkJ3FZfhIEUB7SMAu1F/g4qXUNmqDdseg
        ZCjVHbovkA/kNcyj0BKiyNl6BSFhsG1JR7Q3RQH0hpnIqbgx/LCj7F3pPkt561HU
        ZgEJAhAY8u+46WGs59JvouR7N4ctkdGhO24/fhcmXWxPu6qViiZfXJbB334+vux0
        n9KoOv3QmP8EEMZTZK4rvdPmHUW+ozvuEB+IeCnWIWPBBkCR7ywd2wfarskztVsT
        5orwjM3aXw==
        =hAtO
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
