apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:yTKPgjk4UwrkyeEwGZlZc80oBOc+uczKU/auuMjJPzjDO3cyBzJ0Qao2yd1s2JaDKkoihMtK51FpApZKD5R2xnkuU8NNe99egsz2xP+7MrJI2lrPM1AXQ2zqRYSFdGEKbKSdY/qYsdwET3/ivPWMnr8WZ04X5xpnthm4xLM2k9F596wPqqC4Gxq0bWCBV+f6GjqlK/oysjLiLyuksYZjZ5IB734/+ZqUuwM+FHcyWGn+gT6hLPY380+xFFX8brDRDm0+7Oaf/jv2KSNlzLhYbaBr8W6v9TTun3y4sz65tpN1gffjs3vQWAtUS1I+Lg/NhAiC9HATh6NTkWh4YCKJzoj+FA6y3TbvuRRGE9PmSQDjvo2WRBe1yG4CCkNS2bb6TxmcK8uLjdG2EB//gZogiYJxAkm5IASdYNMfzFfKifX7hlfF7TOlj2YlKQVDBTnh4ykoEGHwhv0PVwY942oRLWwqYfAG2OvQPWtWBWJKPrs0kExQG+TfWhty1fv3nbNBo8oI4oouKr8HpRJ+ma+GtaFawEutCC8dN8XAwhO85vM4+XBBuYMiWXOzN4tfdkwn8xtlhqHpqHQ=,iv:7Jc5WsK2O1AxQ1Q2MMb/9h871qaoC6Cx9gbVmmLs++Q=,tag:SB0kMH6cJV/zVmuuWXT72g==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-secrets
  namespace: default
type: kubernetes.io/dockerconfigjson
sops:
  lastmodified: "2025-09-13T07:06:42Z"
  mac: ENC[AES256_GCM,data:2MA+iEiKFksJj8n0EZo4X6M9dkgUIG+V8zoWl0+zwAE5RHvsuM/NuIPar+Z+2brCFI/FE9eQxAr/IXGPkmvXSJcbL8mMUvR5Lq+dvWiM1EIQNl9ucmykjVaymBgb09KOFJkjuJBl6RTOE9h2xJkxx6naOLGAg7I+NUK3GX+Ffa8=,iv:4Va9EOSkN6c0npVCXqxwv9p9RpVq36XTL8fEW+e84a0=,tag:uxjF+PQiyHkvJT0jtphCOA==,type:str]
  pgp:
    - created_at: "2025-09-13T07:06:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//UzUOYo1nUrTCaO7dioTj4g/e36ul+LbixW/yCYIlBERX
        e80eEUQAHSOJ47H5PvxBP8LkUvcsdmcylA591AIdOMG6RCeT/GypgZfC3sRBJWic
        VYRNB8sMXhUAZpxSf+HIcaqrlX8cSV9wBJm+FU2+QNg47hSaWRxb8321+vr+U3Pt
        YJnY/s2tTnnVYkLGdhhqqTTrNsYjGvBogZg5i3h3cCel3xuYchlp4EJtfWGXhTqe
        yh2SVd9jjG98n46hUMLFkrDtMlch/Y3w1zaxeuncfp6aIlCCqAuSho/eB7XZa2CL
        qq0EgnyuBrIRTzD5ao1qYvY41djkqBeP5obGzDYRvcVuEaYbnBnK/4a5OHvY+COA
        Whu6SuJXGRQlrX4TeXCqg7vo0yy3h1JEk7WKidTqt3rsfjH1CouEGIFL8AgkLMlv
        mRHSPdyOmCPdlElfRPY0ZxJfTZiduMPcu3DwSVR7gbvnR4oPPu56szcgzfP79WYX
        vhpzXDnwsOoRtE+wZ7scQ82odSznbHYigWlNjnyx34e/3xamZEpOvUnTfum0sEBB
        zFtvvbp1rne/DpQ+DX6RiuN6CNx7yH6t2YZsNL8Izomexg3h4ymBTlJ13mvf445Z
        rIeaR8hNZE6Snl36Far8IvjiEa5nnCgi8m9W/YWVN7wVEDHeqm3tP/u2lsPoFSbU
        ZgEJAhBSCCjYNpkRGofqJhjvMI5giR1BcUn39NddzWQQgimhB64k/aoZBCSRM+x9
        GOmJVkl735rBRwSPGAAduhFhTrzdZFVZwTFnYet3oJZsNaWuntuvPtNvkcwuHZgy
        sqUZGSxwMQ==
        =6ODi
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
