apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:+0ze0QXxbIxDrTx96ES2o8mOWujbCsOHRJe68UkjxgQmw4eEeTt3GcnZ3CiSdxpb66fbGaVLeF6G0Fvgk5IotXMCpM6KPHiHe8Iq4i3DsnH+ej1xbS+kcbgVfjtj4MpHTH62lSxSuMWZQcdmhT+hUznTM8lwQbFSruZiq5Yqu7afE6Go+d8lGuhuUjB0EoKAp6Ssyh/9RyursOTmsee68PB219KRopiovyx1ASnqThHFdJJXdbIYumDWplUilEkkOby9Z8P2T3fNpE6XSswL58UkZZGiMWkrSVu4kcqfeGjpNGmcYwf4T154Af9btA6p8lc2Eoj6SKnHvY04hjLMR5Gy7YkTcUSz0UxH65Qzsbq+GGD8gsRvAfnb3T4wgERCYGJ9YamxW/pvkG3EtPiaP4fZT9PwEEGGw3EHnGRHJi2adGG88CY6u9022Ii/5rOT3OXL4B37Hv67UNB/FF5+x/BPQZchbcqAtS+hY2yOfBpBW8H1E35qxcgCm27Rlgp9MecKc35KWlAEd6DhwGHzKBxnXV8=,iv:lTYord6nWRpdYyu0gXF674brM37cszX6UMek79hKKRY=,tag:3qwOocA6WWBh8Zyk2yWyLQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-secrets
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2025-09-13T08:24:12Z"
    mac: ENC[AES256_GCM,data:OySd9MhHcDdqxNaYrPA0ncoeisYAa6wvwLUtjv5qDDbp4D3MqeUbqFGm64/7Xi2ZNnwaM4unS7xDMlraidttaI+RR6rZ7tYddNtnOCJab46q5btse/ZwxckJ7tYvaRiPDtqy9znp7AlAD5+foSX6g/ewI7wHdBi4/aE7cUykce4=,iv:eMTdAmubLsRsS73wUYlM4fZaGA0eYavAxEYJmzxg7tE=,tag:aBEMxLAuUo2VUbev9gpSGA==,type:str]
    pgp:
        - created_at: "2025-09-13T08:24:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ//cOo7wYsvcIdbQgpI23stxHo9BGwoZ6IAzmsJNqzV4KUn
            CPqUrf7Dkl9DKtrP/PJQogrrmQWmTaiiFwtiLIpA63YlZhoCnVRwq4fXsFVi6PUD
            u1Bs+p5PHlxUrD28rGnqETmjcrPYXwZFOW/nZ4dFOyRUQxCAQlDb8lH8FjGCRfzL
            YPqe5qF4wfnWcfSVi1fGrv1qauCJj7QBdSVf0q9oMnQl8XlLKtggbVpcnaJVfqFD
            JxcIFMrm39KGnBKAoH/j7Y9rsgPeY29wX7eaNpG5DL5mUR1yDjCUo8y2FroBxnIB
            gPvr9wNipqx2ZVk0e0HP3nGcJ9D21ZxsV2jCsG0vOW99IIwDA8u7nb7PwrWt3rh7
            Cew7uPA7zpsijUNNenjQ2xopyum9ppYCQgLWHCTnkcDlEkTWJ2cToQiypskaCITL
            AaCZk6Nhkb1qIqaiYjIVbjBcTfNF5tBXc9vfErlYHBdp2f27yQ1z0NjbbhJN8Z1V
            BKdazZAZn3tkF36GOimEKiLh7j64yXWq/BoeOG8DtO6GmR22aXtoaB+rEMo+E7Nl
            BdD5dV2qmVk+bQLnO3dgcYPr5uzRXZgQh4w1/5yKcY0mc2PoHXR6MyqWl8WyxeTs
            L6LMEPOU1f935a7VcTAPVuHRd+1XSZ9MDw3dfpRg4zxrKPV4Kesi8x0Y7Vkp4wzU
            ZgEJAhAwj0SyiAVCYrqeGIFfj/g8i1intPDIeuw08HUWCZsjuV7FM0TooWhFRKYz
            O6YQ5EA/exeR8i3Ygjs2HjNsbGtMXPQDdVSrDh4L9iu0Wa95mfbPObW2ZYy0SGVZ
            SV+BOrWGeg==
            =3EY+
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
