apiVersion: v1
data:
    password: ENC[AES256_GCM,data:OqQNpr88juh20k6NWFh9V9FZYhE=,iv:ElqiXnATBhI/6YDAf/VZ46wj3/YyDzJbOUw2VwzVRbU=,tag:/Bi3ezu9j5JiFiaeIlEAxQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-mysql-secrets
sops:
    lastmodified: "2025-09-02T13:25:19Z"
    mac: ENC[AES256_GCM,data:5djSUuafNe8a9OJRchSX8QkP4NG6z5RF/Y0ACImR4bYwKcVUU172KJFJoRGp9BhDJzSegzN4Af3Qxh4NQFcrLXyDdAK+hNdGxOx+I9p/Svs6KtmHZqTm6oHX4LZvAfx4KDKUZdJnJhpWauVledc3jtUfBW0nBWVLRpmcgE0Nk00=,iv:VzlE9W85JjHed5piKUfeOuyqI28NQ1JP5p6JwPCa2/U=,tag:ykMNsFHDt5CpiG2QXN1UYA==,type:str]
    pgp:
        - created_at: "2025-09-02T13:25:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cARAAqqQ4sMONcp1L0H9VtYgdsHfUc1uso+BSu1b8+PICLsdg
            v5wXWNrzGILQLUwPVaOHkMOQl2W7EQKYZgHOATaUBxLBJUdPHOZp2ddG1zckahVJ
            gz6RPjKRTy6JOPWalC2accl98+M4EDygaO/WzTQq+ILYHwPrpEsYcUpfYJWuhMPK
            +Ouwtk3rP1zMQ9pg7xb8Xl40jLoowZH7LjWtLsPgrI7oTsKQz/3TrA5PAE3txr5B
            E9ZO9BXszYNcYAsYETE+1/3g0BZ5KmX7iehBi/nRBD+cyNQDF9ywDRMBBsSO+aT+
            G9YzWaysZVq97LrphTOzlRdruwyJe3q/CgPmWhTdvbXzkKUEmGiO1LQrU79IcK4j
            NlnoKoop+yH7qRAzdk1OPryTrpA6Yc37zZVbbA2Vp5eyJ9ilr61a3bi8PdGF+01b
            +OkVPYg/VV42EzgjiFfM6SGrzJeh5Xe7OLVvz08yRUnzOoz4JF3Kx4bvm7WcsD83
            Ug06fFBb2PYuL/d0/Gui5WUYGLyDPGqX7Lg0efhFhpDMWCbyv1bZrY4W8EN+VDoF
            pmLUjd3lkV26vUPn5+4pXz8QqN/3xyFeXVxpOh7PdhfqHkWi/kWCxDEZYLBSGsWc
            QzEt5jc/NEuCSaj/fkX+U9wcR6S2TSfTRjU1ubBJWA6sRv9fdHKxssQQI7at43bU
            aAEJAhCFVobNVEMVUoQgVZVGhaev0X1UyXP0Ljkdi+mkGShfK9zRN10BR4HfFgZ+
            uV3+Uz/4y5CWFaky/ffNuEsMviwlTbgqqXXJEOAStdjDy1SyJ139Pa4P7fchFp2e
            CMIC7YffPtdz
            =JUAv
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
