apiVersion: v1
data:
    password: ENC[AES256_GCM,data:R5LeTHj2CJpo9ngbMCBd9cc6CeA=,iv:TISvQ9TeDIut930fIp8OFH8qeEGr9fpBUlBE5Dh16Mg=,tag:CfZCVq7z37H1DTODbW02Bw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-mysql-secrets
    namespace: mysql
sops:
    lastmodified: "2025-09-02T13:33:02Z"
    mac: ENC[AES256_GCM,data:ZmyN7iBsNr7wgGJYNmVgnk9SnSfoii/1P7rJXgYkAMp2jncWS9qabJ/DFmX41lQlMFZoRu7qWdUlgmxL78pg6RIko6D35CYFY3uc+XEG0SugytR4R7MaNz0PNZWy3FJY2JKVd7oaEK8ILYSfPBjdXL96H1Y4TgpTmu8kBo1mAr0=,iv:6vmvjjUSXOiEKAxq9EhuAK3MrWq2wt62hJ1d+Z3W7CI=,tag:xn9JdUYRaP5+B2AN2S9dAQ==,type:str]
    pgp:
        - created_at: "2025-09-02T13:33:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cARAAm5hsZMP9HYZm+ECBYZED0s2p/kmc1HeZm4rxaEryYcdk
            BVL0okcO3UrO5Xg3o+ITJY5imHyGVvYrgJaWGo2ffBLVTH32DK2oaUX0xoSXi9/t
            NoEY1w66zagormL8oOzg3GdEns5gNRO1Q3uTWsIAY8/SIsuyjWQCO1g4lmccYROt
            QgvneU45N0P54HQ1mb2rVFhqVRbTadB56cVqOWUHr+hjbI8dVnpa/5RqMAYCc9aJ
            zZoeDo2cGR8DBizaIktnZWXF3yZCDJ/beddgUWufag9/o5sIIMwLfwKKBxqMfEZU
            OjatawPewRc7zG4elEATGurNUfBlcqnzEQI2o3cGX1J8932Xr/CUxLzCwI5p2buB
            PteOvRdeXxvBWn3vSOZ7R7OHRpCoSE3mLnW2fJPABTZAInUB9odMk56f4R07/+3y
            U2kSDc1ujZan6kSIK8uSLuga15nl1b9kLnONUtfHAFSp8rMdisXM3qkCpablE36M
            EUspMbkdXCC8j3kCXUNzaqLIwKwq8sj2m50V5CuyICSH05Rq/yL/z1tPDRIHWeL4
            1mYesCyX4z8zJOidy65QxkZN8/kdhgZz6EKIsceXi7QE8O1We0eTOHDXN5xUFSEo
            wwBJHeF4FC8U2Vh41178vsT6sNj2QlELGKmI52zVIPnC2leH9XqSuhH30Mdb0OTU
            WwEJAhBydUqZD7l89BnUDcMQE5+yLiP6c2+KbRQEnFbRiBGG4wdjgJQv8dRgZBwS
            DzDKQz1FzVDMYZA2O2fnazFyEiF9AO+BXCb1nkZPELkCP/r7ve67UBvT0+E=
            =bSeT
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
