apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sync
  - caas-backend
  - caas-mysql-dev-secrets.yaml
  - caas-mysql-secrets.yaml
  - caas-secrets.yaml
  - custom-minio-user.yaml
  - grafana-mysql-secrets.yaml
  - loki-secrets.yaml
  - muzbuild-cert-secrets.yaml
  - muzbuild-mysql-secrets.yaml
  - muzbuild-secrets.yaml
  - mysql-grafana-secrets.yaml
  - percona-xtradb-secrets.yaml
  - minio-dev-user-secrets.yaml
  - minio-bunny-user-secrets.yaml
  - aws-secrets.yaml
  - minio-backup-user-secrets.yaml
