apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sync
  - caas-dev-secrets.yaml
  - caas-mysql-dev-secrets.yaml
  - caas-mysql-dev-secrets.yaml
  - caas-secrets.yaml
  - custom-minio-user.yaml
  - grafana-mysql-secrets.yaml
  - loki-secrets.yaml
  - muzbuild-cert-secrets.yaml
  - muzbuild-mysql-secrets.yaml
  - muzbuild-secrets.yaml
  - mysql-grafana-secrets.yaml
  - percona-xtradb-secrets.yaml
