apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:3x4jEKWlCShQJoSACCDivarKvNs=,iv:bYcJolvTQhuDl9BHAYPaN5YB08jf/WzYTxxkRIsdK9k=,tag:yA00/83bt6qODbTOc7fN7Q==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-dev-user-secrets
  namespace: minio-tenant
sops:
  lastmodified: "2025-12-03T15:36:12Z"
  mac: ENC[AES256_GCM,data:IICDGfr9RIuUomsPD5eoklujrEwagvrAQZa7kfBAlO3Nds9dIxWdvymMsNkRLg27LsdknpnhJKF/3m/hHaChsitdUbBoxzlkCMfhlNYWR4oF+B6BZxagDrcviu9uzhB3snk3Y8GqFgm1XOvQ1RCMur2C6Xo7HVdvm1b79p+cyPs=,iv:/XTTMaU7wPrP2UTmIf8ZmWIY4YxUOB7AzgLt8aa/5oI=,tag:5BFVgP+mC6+Km2NsNfinng==,type:str]
  pgp:
    - created_at: "2025-12-03T15:36:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/+MBt6Nragm91rW9/swItA3vX5rkc8i/pXALRU4EWJlfh2
        S8Fa5G1YGkusxWGX3uGHnYmuyKpwYoHNISl7xuqWYv+mIbiSN9Y6/pBGcPTsyd++
        8BjzRcdCshfKyEuVX6XlmRg2AxQL6Fi1lGR+nMsEuMNlGpIv/vyR/zf0EcvtNGAi
        HlFLMFZRK+fHX5OeCOqQB3Og30rX97jdNMd1KXk2DpDn3THE+d/T0KaHJygxBex5
        ccpra0nrmMYg/R8Nt9WMRPk0xmbkcFDDmPJkEE40SUcL1jrnnqWjB867rJUrWWJm
        B9vNkGcbEvKz/g8qOSPc8j/kQWiyp+xPZYCAIjqcYFzOwUkMDSp40T87GDhHt+Jy
        N/qfEy1csnj13K1ktaGEXoI6pp+k7VjcDTtP1eSYnEODMBs1/ePNyYAkN8i0RkNI
        vPnRy5VO9U7cvioQ/XH79fG9Py7+7NLCfxxToXHxmsUSWVv/bLsHi/sAi2wATe5N
        aA3W/bOuT1e54ptS5HgHMLHa5D6jty3oTLImIeSeIzzMHPSU/wtTSVxXcXMgVt2a
        0Hbv+37JM1ixAwKAcNiMnT5jDna3BE6klFY7YGsmY7VTc9qWo88FQ8NlrMhWHwxX
        CnZ9HHDHtnIndVSi4gpibXpeAEeS9ny1tfRoAa1FcH6DDg6Z0mCuaZBCz5QEZwvU
        aAEJAhB+ZtGf3gnNVbPxc0UZVALCeXZWG/Uwh9VdVudjkKjJglszhjbTOXozp4YF
        qpYF0FG+lXOWFB08cZPJ9JeUXY4ZBF6nhe89jl2utHNwQB2gXy/NUPYeO0hJUczT
        WgdeR+oShkzN
        =FdFU
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
