apiVersion: v1
data:
    secretKey: ENC[AES256_GCM,data:CqDH5legyMM33Qoqg5ej31CUdZM=,iv:8snv7zWUL63v6MGHeTrVcsQpsFVnSaXEzGuxvfYWRZU=,tag:XVVY7oSt3opCaNBk//X4Vg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-bunny-user-secrets
    namespace: minio
sops:
    lastmodified: "2025-12-20T20:25:14Z"
    mac: ENC[AES256_GCM,data:XTUK0/sMktxQxE0mioB9U/MlDD/vT40w5mqRmQR5rTOHa8jh62vh5w3V5xZewHKg3Or8uCnEBVSB4IZ7U9WusZHeXWFQ4C2Ka+0gxJc0iFRTARKx5QI+VAcTh23OI1spzWAJRhunUClyD0UqLwsDGdReulSCEaZKd8w6p5fuzR4=,iv:KZvaci6cdJILJGqD7MB/AviI21zwYFTZite361p9I44=,tag:Mao7c+jhzYXtyJ+GPEF6AA==,type:str]
    pgp:
        - created_at: "2025-12-20T20:25:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ/+KG2rKoq9fD0oopOZt4hmI5ive3LMqm/9z8qFYKPtCBO1
            k7tXtJ5nYt66fhe0n415X9xZc1kgH9wklYsGMeYoc6b7RMMp34rRMlDwyqyO2CDF
            7XMYzK/ZhdoztcdsOo8TrLj/BXerDlClCgzjud4L/28szUEH8bdS2//D+7TXElbW
            LBcU1Y50MLbm+T8eX+nsCI4DBOmqwt3d/ETIgWCpInA53j4g7eLjALs0491L3dZI
            1lMtbcDMri3v4U0FbjdmkWSmPSKTQwxLyj1cgWhRECcFgiOfyQZJNQeHdRMVG7I0
            dP3iB1T1xLnKpRV7S1z5iYkKOXvKuwYlW5UKFCppmQTmNfe6EYxIr+LTzhEHlwql
            /cA9XxBoj04nqSxnRX067SYqW+zYsIzhYtNVe/VAT8nDIjgD1q51mydWHb2+3FEN
            vp5qtyelOI85vEYs8ws37P6DCRfBoSpMEGasGZ5bFFCdZqANyq+/Y2fdbFFpMzcX
            04Al46siIjWe4az30J6+E2IgwCRaJUll8MHi+EPGeFHDD0isrBu2Fdfu83ts2lwG
            plSkKfk7yLlSnofBmZEvBlIuvrUGexpmlDLqbhnYdOrYYVZBbfsLX8DHhb8eoilr
            iiX/codG0U4THL2+Qq6gToOAXKsM/TqG0zx7f3Q2MMvr5qYpyM8Z8thfh1DERsvU
            ZgEJAhD48UWQ7OlxzKDSQKFX1BiN3mHUiMApTH+V0NEOPPd8YC8sVBMak9+CMJ31
            7nn3np02NSHoVF+sbdGyPewoUM+ndxLJtPa9cOFIQKDs81kDG4hGr7fegrUzcfQO
            QEOchewHPg==
            =oQQV
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
