apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:TgAIG38Pu2zIR17LHTorx+nVfYM=,iv:udhMx9pgGg3MvWggUHfOMXXDuv8LW5hMvJ8JamoI1k0=,tag:qUC72vcXvbUC6ua5+1YJRw==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-muzbuild-secrets
  namespace: minio
sops:
  lastmodified: "2026-01-12T13:56:42Z"
  mac: ENC[AES256_GCM,data:Qqijrscs4PU4I0d/QPuPAq/MjgZRMgo40G4BK08pU3DvZYpg98neTPBURwv7zU4fvBkcDlNp5GyQYsRPAzJ+Pb3sJPavi3vGdCpHt9iXBKsUc9pHRaZuxewnfG+XEuelN0Vf00CTNyXLtISA62imsoyDJ9Y1BWPVq+JOu8ui5jY=,iv:VQRYWA4OkSfYhnxcF5k2ALVAp1KJh260FjxUKcJiwOw=,tag:ckwslj1VMM9O7NKKBFo/Kw==,type:str]
  pgp:
    - created_at: "2026-01-12T13:56:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//XgFYkuwioiMM5tUClMaxxI4ihD8sk5LIItmkWyjC0SaX
        kzK5VMsSieAqTU/OaZbVkq1SGjJfhf8X4am+iGOfGbEoj2bhhodZsct7MTVPOsdW
        chQVFAMTkrFDTEdpt0WYASFSrAcwQByPIdqfAHry6+HWSlQrj9QU4Gs5EYLg6mBt
        zeLaSeRPBWLp8wZ8mh9KCOIIxVZ7LtSLd1tNn5mm06Bi/S1j/k3VH3t4ie6xFlDW
        QpH2YYHrpME5RByfp87bSTj/n3G3eU1T0+q0EVaxjFyd6WnN1VC2fKgGSKqvZ+DP
        iwVZRJiIbHIOIb0rjBkiOMPGHoKWMxYkDMMmdk0dOZW4t+sDIxfR4JvuBM+4ZUQs
        qEHvdq/3wOFhhdWSPHkmiP3QibnS0Dl+zkxIA7ymaWKN0+QhAz41CxFrsklFx/CQ
        G/QnmUYJMqZGUAzK+SPpkt22dnYIxZGmvCF5Urj73n+6eMyiLHFsbZivQfW3XBTp
        bT7fwF+V5Qb4/NA8cOBeVBONfiw9QcTiTfZVq7CwsaDAn2P4bozdl4SxXBr5Fc6J
        L/0w9Un//L9D1P2aDiQ3nmZ7itn92jUYissoIrlFVU4I5afIrIOB7GrcRmL+9/Ha
        8aS4yhQTA5tGIQUkSI4gNJPOsfeqL+Dazm4RWvEX3icv394mDx1kNNXWA/4lDx3U
        aAEJAhAIyBKrvDTl1k2yQdutRZTJBESRz5rbU/jCOscAq2v8fpmNF+MZbj73WDf0
        FQOil0LcpT+g9sEkQ0ntJkd4yOHRAgbse2BJzC+N5Umz5aRXujAvkNGrEUv4RyYH
        e5rUAdzhLdJl
        =BKYL
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
