apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:iLAHVqcrt9an3qDwKLxsl1khQkA=,iv:cKnmrjFfbgoR/z6kAEPCUF8oRlf8NTJoWEP7vAM6i8o=,tag:KBsUK/uGxydKz3Szub0BgA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-root-secrets
  namespace: minio
sops:
  lastmodified: "2026-01-12T13:41:36Z"
  mac: ENC[AES256_GCM,data:lT03JM/o2r5uRavK6wDN6IEWAmP5gbQq3xw+m6mRAdgEZ9Rz4cSsiN/HEhWXjVUaQhXUxnlL2FUOWDFG1NBBCSmR1TAUDzXE0nen6ApHMskQmQqAXYHsQYluH7l/6RFdRVcwE1SQ28U4125/9uZ4xGO3uHfaNRvYngur0NRkO0Q=,iv:8wo1gqDZ1qFcgoecGhuMpQXfPDiouLNkNVTATyZUvls=,tag:Cv+nVXIGMkU3uR6op3j5Qw==,type:str]
  pgp:
    - created_at: "2026-01-12T13:41:36Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAku+5pKhHZuWTjT+X8D2qXaN9JFfL9M4bSS9FxyJu/iq9
        fbQX/yFpIBQ/D7t2jViILznFelOH+JD0T+rBWB3Lsu/bnoQbfcDVoje4cGZPKi1a
        +BuAGxUxHunyXe7MLE7jezGnNjhMqpX1FmmPiA9cd719kUYUTu0GL8IgSZkkGABF
        LazCtmdmkFQ0iZQY9s5J6MUKkIjDpiwTK4EDQB4JUqfAB0Ck09NyCOGA2uv8CXsO
        JjLj1DIRehPQ4D5XKJQmeVjWyIKGh6qx54gkveMM35psoq5aJWNWnf8xJUsbOkHo
        k3e1tyxNW2xgkwVvCglUFzvoUG9gSpzsz+W4Ww9WgEFWQURL70kOGLvWvMOys42E
        ptY/hIQ4839q94f2xHuEhNz5rZ9I/sBhoCzPD6HmspwFozmv5Xwv6th7LNwhHwgf
        wnUvEz6Mj68bCkikCXn0rJJc8Tg2yC1IZmoEUk7DZQzF2Us5hEKiNomBnbgMOUUB
        sIjjA5/mP7K1f9QYak1hyc6TO6yRzK0cClppz92aG6xHQsVCojE54EOL713hNV8C
        W/O/DIkdU6PyVFfUGWxonIJZAy881kKkuFmptfRc9E/4g7Q2x9zbE6iwdFkrofMl
        6X5E3qNhOF4jswC1vDDnSGQT/iLF5hbrHfEphD5sW1rEQjAt1eDYnh1hyiBSUYnU
        ZgEJAhCRuXLOPjXTVT8B5NpyHb+cNje1JQk07K9mI+CQLfHZRjciRSvClf/1zvpk
        KjDyKI9ETEwooyYiiEOi7bhBaS5TmH8nfmT710l0j9UbsGYcvD4eL6g7GPHwpY1d
        FRGgAT2Bcw==
        =4vyn
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
