apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:zMMqYfPppNP6lFPuZf6+mfitblU=,iv:dgeOS9IT8oXhVaJOob2P7IZN5KrgBXkTuQ3AiPiAG4k=,tag:G3M2tN1I4C6a1mFkBNrD+g==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-bunny-prod-user-secrets
  namespace: minio
sops:
  lastmodified: "2026-01-18T19:12:15Z"
  mac: ENC[AES256_GCM,data:gATYg4pmsZvoGv+zeemSDXcGj5Nfey7qjIdR2FRnFSuj5dWC8ngCCJUkFoqGene9WtdHiJj+MMcra0fMzcRyYG4Ku3IIqv/KkTo4j9cy/JgOwGI9f24hY+rJ+ioJqf0ZEs9vCnR6URr/ycY+u/o9zen9GG0Vk0m9yZ1HYEbYLzA=,iv:z2gwkLu8ko+HUJOr7DROg9zgP4sF3juaZ7yXuWwTEog=,tag:wVXkuTuJv3AcH/Hbf+/c9w==,type:str]
  pgp:
    - created_at: "2026-01-18T19:12:15Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//ZH9pfORdkkxwGapI121azrqZvNEZtJp19oD7/JVZQXGG
        MdOwpazCCDMpoiADQYO1rAa1ulWYJJyBVlXipvcR+32p3HoyQ+oge1bHVd5y74B8
        vY2N0wqEQCcZnLe9louNgj1kpaISCxhp/cW/6SC0kEPdH08Bz/BuVFAl6aR0+2zw
        QLDcAab004v3XkXarbvGO0rXvXPBC08nRlRKAWPfvBYxBli4VuCWzIhcoKBKvBQC
        stjtzmksf2/AfUMs/xmrWhm3eZoO5C+I0K6+nppHZQYmfOgT/gumoNr9B7jLayEM
        AAaphFcKtyBPCb9JjK5dKCOVtJuIy6IkoVfaZlpBnJqd9JC8ORK1z4u/qr62yynO
        YZ2X9LIA4095JywRGY5Ua7tnO2Hwb+Ka6XT76X4iW/8Oq7IWUSh9tTmsCnQGIiG9
        6dQZO6AYCqLdUvWencXkEnnzva9U+RiBR3Im2JVcn7d8fZnu5KHCOuFJB4kO29g8
        9HU3otU5v61R+OWdPZ6oxEctAr0TpCwd/lkPJhmw0RHAHE1anfMk9PcLnY7512V3
        2Nb8knQZcLC2L1yuh8HGZMf3rYfOw+qK6N7JMN/EykjLPeC2KUpmsYRgVHKVjok6
        VmMgXdKXx5Vbek+G7bADIqy6miyNz3Dtm2cj2Gizb3mCpm7bDiBgEw3ZWem2xAjU
        ZgEJAhBD5eSwG6mxtRJcHaT9Pjv78C8Sgu9dCAKmOrud25oMWNdmmi3eLTI+2gvB
        sOBHmUqGnLXHtniro4EfHczauOw5LWltvQGg+1dA4Dam3g0/6rpTjh9i9s8ENjbU
        6IDCQdY/dQ==
        =VTl0
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
