apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:2/tOKw5lv6NZFAyLmG2evKrCYjQ=,iv:Wk6ikCjH2qU8i+lly+pT+zzivh3p3OSTLeG9HaOLkMc=,tag:8atX0+sEK7WchUJlFoez0A==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-caas-user-secrets
  namespace: minio
sops:
  lastmodified: "2026-01-18T18:56:05Z"
  mac: ENC[AES256_GCM,data:YtNADlwekiUJTcJ2InX5D9c1j1O/xFkj2llp7nNmzKojtQWXzitmSy6Vri8xX/ZE7dP+wJh389QaTuu0vKl93X3CfmzGAkW3kH3/Hyn3FVs8iYfxGweZOCtrzUSuCjGjyyZ5izYbHNHhVpyPto0MVSd16TXiv/Uy2EZ2+U2D8h4=,iv:g3HVaACeqPC+cZ5b5caz+olCIPXnAnjoKsysSq8bbYY=,tag:+uFocY3783Rv8LlXPrbYJw==,type:str]
  pgp:
    - created_at: "2026-01-18T18:56:05Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/7BX7jbhb+heRebjzb96R13Pz7UWVP321Sr8+KExQ/FqVe
        A/1y9ygm0VtugewpX7Q3exrLL8L/tx4yBdK9dCiQiudnsCw57/PFDSxEaW0hGXI3
        /R3I9BKFsSIEKbfPiBhzE9/SdXdPYgOkpDYNbM65t0op8Hj/fuDi1JXZ7xK2Zcpy
        yWD7g7MBTnwTY0LBNAoE+SDVEGaVDPHpPuAb4A3bG46ghTLytMnXVmwsapsIXCf2
        v+IEqI+45gcIng8FlCyaajVx+75tz3MG93wKfdFseBT+B5uu58rYynrwMJkjjvGx
        ggY7a6/TeHk7VoZZtt07Io8KuE7bNmfJ9ggN+lOhaneEYqN5DvJ7py8V+PnVD91p
        6dcQQ93jpU0BM1UBzHNNMBOGSwHbrUMXFyZ/vrYGH9HQvCosCPBxf8WbEwz1gcM4
        x0k4V690Q3/ZH2wBE8MEsuZ8/Gg68w+9gGGmkJXGqEwFsgJlT01GGcUgwSm9PGEq
        SEAiqXxXDbX3aaR639lF77cci/x7memUbKYA7L1oewB00uEzKMqbuUXU31C0Umn2
        ctFhabrlRHe4oUOsL21auGOg+iqJfZIzUyLk8zT6NAKwjZklbcYm5euE2YLK3Q4m
        YLLOOJyJ37plVs06YivXcG7CyAsArOA22EiRVlPVrakix2aKihakMYS84eG9J/TU
        aAEJAhCEXWsf72C0uEXMWxkSKSE1hLouQFdhQiWcAHkiZf/0TF2ZvCa6W6UKtSao
        P06ymMkVE+LDSAUbNixWOMMfr5On8duhfQ9B99isHqtg4j7oXYWDNyjKoj+PLCiW
        o74ux1F3tDJh
        =i0al
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
