apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:3R5WxEWiOXgYBGX0gyG/IX03Qz0=,iv:fnLYjR3AGrk2DZxW34Our2i4jF210HNKWFnBms9dqEU=,tag:CYYCetDwYc/GOWQ6w+tG4w==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-qirtaas-user-secrets
  namespace: minio
sops:
  lastmodified: "2026-05-04T09:44:11Z"
  mac: ENC[AES256_GCM,data:f4FE7nhkAAJwfCk5+ZL456SIbfVdw4qtk+MaIWM+TGM+edygYeLtydX0jRrH2XiP0jY3+lzmSnd7es1M5Xru4+5Zd4DI8JZQYbEq2fVnhbqPIP9YGueMntZpB7WYJm+utNgTuvlEPuE7vcO/4AgQGBPhMlKVh6AEYJy366YfjJ0=,iv:MyQ0qJV0/cFlJXCB7awP9L/mfle9aJtyFUCkwiVknNw=,tag:8nr1HNpJ1uz8CDZFnD/xtw==,type:str]
  pgp:
    - created_at: "2026-05-04T09:44:11Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAqQlHfc/QJu+6fDTdLLeUQcA5DXlopNj3hHTwP9HeFPdM
        hCPwIvRKMvYYYG7yrKd4Y14d5d1a506g/+LH08WKWtaU4IMMiz7rX27p0irLYx5G
        RUiid8bK/CFdOANUONwrik1Ke3BXybE2rPOyTr6IOPe4QuUXlNwCpD/Aazu/KrK0
        P7AFXuOIcEJ8zYdA4PBZ4AKJH+uYmYGgENosGXdsgK9hO0hjXe6YTr4kin+MyRuY
        hU+lINADUu234KSS0j/WKkUO4cRo4OXxS4wTTYYdsOaG8dEanusBhLUogrMp160/
        AiJFfI5eqt2bkQC/Yx1W/4G/9b4XLj8g7LE0xr5JEXVkUfZJ9f4POE6pvI8lUY2p
        LxOUXpR3N0sowfMc/I/a5X48OJbbonhXsYtiFD9+Lpk3ns5n8qxKCwTmVcZ8oJ34
        qCvKFAeB2rVM1z18WgYINkAzKLc26PYvqyqLIiVOv7jbGnKmPZ5st2Nz/YUJ862H
        cAnYB5hMpPY9dMEjnDTDN1NbB+Wqk91dsT2LGJ6derJsUPZRlBtKrcvtFtRBnMJs
        58MXudkTqUJ2TttLbXxszatLvshJTD2mFo4bREhD0T6ceT1OkV1Op8Z+BT9WJqnL
        AWE9mblE3DuD0ftA24lf9Qg6PThu/JL4Uovk5LeqCm/2r5HZ1Os/1WVPzHxJPMvU
        aAEJAhAsCBGH9bRTYPGAlIxZ8nc/62olnwR6F0h4bPOjcHkSB6zLXaB3OFlHkkKk
        fv4DuaKzfO2Sps3P0rneEPxT/CSPUMezWCoDU1/5el6t5AWQhLBMazEBWCIiq4xl
        TYaaU23b022I
        =RRy0
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
