apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:TVNRyhBEVtg4fzeNbH0UZSbj2Gw=,iv:nJgf1VCy7NVIyBFHNYX2Bo2Y4xYRk3/ExTVIT0xjtyY=,tag:CjXFxsZOTzQKdlCgRQwXMQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-qirtaas-dev-user-secrets
  namespace: minio
sops:
  lastmodified: "2026-05-11T10:32:45Z"
  mac: ENC[AES256_GCM,data:yx+Q4/YU9FxCT5dAq47BMEN37pgk4RudcM7YB2u3/eiyUh3Vf8zVjnsP5E7myjrgf9l9R1CRkn/BDMaOq6I49eReq7Khxmn26XmD+xWAYSfl0EJ1XuDABWrLrZgolyew3Dn+/5BMt4LguXGR2RV6zdveQqw8fHYmicRoMtY5vy0=,iv:mKwhROQl9e6EmvvjmK1u5ZouM6IS1DgCHBR/g3zW2jg=,tag:pzP6uzwbCLjcAgECFkLt8w==,type:str]
  pgp:
    - created_at: "2026-05-11T10:32:45Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/8CL0eeyrkGtA6r2p05Km6GtKL8voBgUl17TV7KrmDsorX
        D3xkV95gt6qW5f1Er8yXmtHmcLIfPQA63AofWyJjxDB1to99NJupM3qF4xx3jHs5
        VmHhuUQkc1bAJSRuYBSnk9QNpcz0XVKI5cneW3rq62YfD5DucUhxXlONNkIXpS5s
        TomDfqNGoPnbGxcCc+Q0bsboFgIgRUvF+5szEISmgDfQumBmxndawM1dklBSrfEH
        dFe7mx8L5wNK+ZyQlWmoLaG2VSxftCFffSVrYr0sB4gxSRC1QytVQZwy0ISUB0xP
        uchlaoPSB0sgDcX+T3R/kyGQgxiQNXB7AtaGYIHyvabCpaGNhm8Z6NKcuwcJsIJH
        Zw8CCcEsT2rzWW/nW8sdB2Y70SkjgT0oSrRG9tYJTUWA2FOlBBp4huMX8eiJ+Ced
        D2seo1X2kUqStj+C37aTS631lK0UHfAtP0n4AW3szodDk48nO99Oik9fgbSniLZl
        974+ZJqTwzQtn4k2IVPsfru6+8YLCvMxh4AB9+sw4veTh0BsqwlUikds3Djj5/72
        DXYu6ezdfAd9nOLPgSbAt3tsTx+75zafnH4rYGNJ0aIfiScD3/IjbbCb3NWzr8rV
        tgpI/iPjBNXMtN24Zjqu5+fbAyvZE6HwZeX0StTK5w7zmhp/h50l6vuTQomWZI7U
        ZgEJAhBLmuY5OD877JP/w8ICb0UiBxtZd8iENdhCN9X0rwT6V+7zfsOJjtCvXhvS
        LLMDcwOohwEb1795NuWia5CpioJuk5OyJbAFs1ba0qPd22CpCqseFfms6xLXfNrd
        CGQq22Nqzg==
        =59f6
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
