apiVersion: v1
data:
  secretKey: ENC[AES256_GCM,data:/w2cLMN+DqX1PV22wtmi8ruJ/Jw=,iv:9u1QL+gWlD98baTQKBE67c7ss8ap0mFyb7FDmfyMf/U=,tag:QQ3Yap00oEs08vQQJUpEeA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: minio-backup-user-secrets
  namespace: minio
sops:
  lastmodified: "2026-01-11T13:04:46Z"
  mac: ENC[AES256_GCM,data:jbUKm9+ATZYbJHHRYD0IiTOf2iQT1ImlwqpnH+EPIu6vTCsjNAic+exEHwQSwBHyYWPZFmHs+AgrqP/1DqakGjGqTjLO/BMqCUJnNQViyDc8VgP8was815h1H96TQa0Vb4DF5d9UenOG0yjU2ux601DXDff6h36HqZiYZIaPc9c=,iv:mxj9+EcIanoXOHKGkjeo78f/FL1UkrmVPb6/SLL/D+Q=,tag:USqbiXvLgN6/omsKiqabPg==,type:str]
  pgp:
    - created_at: "2026-01-11T13:04:46Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/+OPtA8tNo4HQeuWbZ8ZMj0wU8x4J69BZBOb9J3GZx+u0d
        a7KNypBeW52JmBxVzY2VrRlV8N/SkTOed5wiOqYZpI8ziEBSzn2IHQ9+qDh8vuAk
        4nZH5FSqxxrs6YXDcvAbFK2XCtZkEbZIAe7KzYWPD3DtVeiG6PvtNdITMEQvN9wQ
        RXko1KYeGvO8+7qpEzSHsDbY0bBBMZ3nzWb/l36XrL11DkdnqlMnX4vkUXJGEpil
        Jn2d4LdG5XauyzLudPkHZ30G6l8DBKXBhIfPCTWW8Ayi9VOJQ+yjETSFvXq702q4
        Dg9+ukOVF6XIe2HGLyRGdBMSOSOjPqbJSTf9MQfH9eK/JkHNPGdYCesCIHn7kdMN
        JPjWiTbhkqgpId6BIOxeHsM/uigN4FUsfo4eX5/fmory8giofyfxH1OkiFnb4f8k
        oNtkAls6PgFMFMdKa8AxG8YyewlEKrPU06b5MNzt671hzcHL/Xnnow24wHbIOTA3
        MJ7ZZEH/L90HWYvhcXRTztS9K2zJwd5TTj1Mou3ovZxGblF0yhqqzEzjzYfgkro5
        9opdGcz68gCb6fGoVq2U6hnGTqapjdjVQPoFmbiucMIKJd6BZ2xBpDmbKLjGwdqz
        lo7XEPFcvvo+7/gBPThqlnWix6/3fCNs9yMVCJseB+wNYXRrtg5G3i/dFu99NanU
        WwEJAhC2hz4ely/8dJZoaAKik6ClrhsjTYFVKqlW2NOhwFsEZPXIE/+3xPd5iaEN
        YCqGlrzaiqbnr7QXunzfBBu4AnJusd6Q0POajQe97DcWwT8cqFVFNcNpivc=
        =gWrN
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
