apiVersion: v1
data:
  DB_PASSWORD: ENC[AES256_GCM,data:brkW5ZV3viRb3uSyWOeE8MjNur8=,iv:sudt3N5VQfsihILVDYcmi6hGbBlcBanmdys7u1hlgAI=,tag:f/AZK4ov9sxQDAEV4CHfIQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:DEeE7JofHMW523jTJd+K8w==,iv:y6a8U6oCN4ESuvRb95biXT9i15kCCDYaBC2VhwruStg=,tag:Y7QGHhVWLxE89dP94UyJjQ==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:aT8bhW8O8fhxGNES/ViJxKCq6SVZtgnR,iv:r/py0rApsiLatKrDDooorIvl9iFWSa0PGdkiYjvUBFY=,tag:KsHZu+Z9ddtB4O7MXbqu5g==,type:str]
  MINIO_ENDPOINT_EXTERNAL: ENC[AES256_GCM,data:fe63+goRqePFC5bINv5cglbSEC0buUH7rCid2BBaYSEjzjKw,iv:fqsrqPdSFw68JfXZBZZb1iMMvT7GJ53VmelkUMCHLeM=,tag:AToiwr8cpa5AQ73y9f5TlQ==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:WY3xw35AXrqSlpLCJs4vfxgS3Mw=,iv:MVRv4729ZPL48b98AUzmT1K0cLL2VstjKNhTSjOjRRw=,tag:uwWPVUKHeOYyjhKXiOwVjQ==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:ZFNP0M+GFgtpRH/wCdUUXQ==,iv:WlyOZvLe0w0UU23kvDF9nyHHH9x3vPDLY/5HMt17/5s=,tag:J7c/FXYL30+NvC5H2vA/7w==,type:str]
  MIXPANEL_KEY: ENC[AES256_GCM,data:g1avBT3fG3fdvIrODPKkZPChHQGgSZ4EyNeKkivNxQ8D309DafJmt+gswiw=,iv:pmNQcV58wys5GbSEgZASCt/NWTDz1kieEFjna1GeU+8=,tag:IlNCr6Z3XawpRENZXvDi8A==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:SR+7wcZiHUdrNXJ1dbyiWip6NUS31PlU5gNzjrmzPMOy/X5bdeRLwR6C3ostVIuzf9q4/APgFXPcbmiQ1Ah1ulQCxmg=,iv:tBo6pQhLNi/J4W1ht5TZZdUQSzw1nTVhonU9ebiXJDA=,tag:SBgMXC47qNk7J/pf5QvsSQ==,type:str]
  STREAM_CHAT_KEY: ENC[AES256_GCM,data:McJFo6jUE1ZqQNvwCW5Aow==,iv:/k5LrgZBzuIzq4fmjP5hKlc10FhzAl6wSh2iTicZUHM=,tag:gFDTz33a5T0UH3GXX2ylvA==,type:str]
  STREAM_CHAT_SECRET: ENC[AES256_GCM,data:k1K1WqKzBZ59ccazD/PJf3rf7n94lEGs97t11FCFnLy0zFn2Je6q8Q3ug2qH8nYUw1aHlni6h6qZuy7I+s6s5WBmFsMbNHn7tmQ+dXKQllOee45p+a2lHA==,iv:kGyohBloI08Kf2j8RjEfBU2MDFbQoQdyh8d6fF7MImM=,tag:Oc7HSVBfCO+GXhIjURNexg==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: muzbuild-secrets
  namespace: default
sops:
  lastmodified: "2025-10-09T09:14:13Z"
  mac: ENC[AES256_GCM,data:o2M7fqzXmlk+UyLwXxa6mULMXjGVsfilb4U498IETyvbOBCFndoATKrRAu4btua35IBA5icbPpuPP8sMrffyJkYbUNWZntsCcrtk6lGhFVzOxAO1IsZ2A2sqC+ryMxE6OZM3cSwi5ugp9i8uSfoWUSzcRVS6MGRg3ZcZuQ6TlTI=,iv:6Eg1MBP+kY1M6O25FRo6SPOuOtlgR/msM2EYOiNMN5c=,tag:EsUbR0J6EAqU9zF0rQtXoQ==,type:str]
  pgp:
    - created_at: "2025-10-09T09:14:13Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//aG/Ik1RCYHDbLWuL7yop1w/BaFRtUYiX9vt1RrVIiWW4
        UG/Smz1PdyYfN2idb1YaGzujPSh0wZTtsim37UDGzp70Z4n4xVoUfOqLbi4nE6He
        8NwrBr3q0Geh3ZAw3yZ0Dtj7C9nNpBw7Ln3hwDUDAuXEmi0td6OS7V/60uhrdbrQ
        9+gULrkaie7UKqfxkFRYh2DaN6wdbGhr1pRdY9ka+lYZEIZB728198Hr6VLqTOGx
        FDEt/5/hCfPlvQmPoWEC56fDDx/2yFDr9F0e3i/VKVYsYLtsONcmTpjG9BJFW3j4
        HWmSBssvs2vhGshMvrZwpASKQHOtyWCxg0yeVsrV5MRV6VwxTNOK7KDkxRNfq/MC
        FYF5P+NWuaRlKhNjKdZagRlfgN/IUd5yVt/FQB9uQaeQ6PbvCTlKs4F2o3EfVtF6
        2I9x8tSqODCqDP91rdau0mKQODRqK0fL/GBsOokVQDiMpPeqktO4fFeuO/pAb4FC
        1x5VpJpNcxvVcxqhxkfoeDMRPti2VG3wMvQpWD27RdeilYhBaEipqYXm1hh4Ucga
        yyf8bYsdGG5xkTo7ddQckhkjocTbpIcssLOz4FvP66DayBQWWPOjkPf8FvyreJv6
        hr6DXnL8KmZIpaHSKqvZIIRInr1ETdQzihCzddVQcOBXOeieU0JRKVgFOnZcLNDU
        aAEJAhBZrKszj8l7nS4+kSqRTLvgKMZ636s7m8OXNL6RofTQB7hUcT/NRlr+ikTa
        3s7z3tsuhNYA/QY9BmRAhPH0BehWbRRO53kTlAB7DUL/ygClXWYrBuDAOkbPkLwn
        qAdWbapsqzwI
        =0mZg
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
