apiVersion: v1
data:
  DB_PASSWORD: ENC[AES256_GCM,data:bRsbeRrMew4Cao6qDA7MZB8E9CM=,iv:+h2L4caXbXg5YCPCn1Q3CodU9aMm1NqomelbcmRcGI4=,tag:1Jx67VRbFi3ewUoUbbSvDQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:0x84YvWYURodYxwAYQKaxQ==,iv:whAhAEPVt59ler7+BWsvpYH52hFgZoPyoTveIJ8Y4IQ=,tag:E+ZNIn2EeDrRCOw/kaafAw==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:JwQYvoNYhfXiliS6ev4MTnrRi1aNW7hp,iv:fIosrKcifUYdlnrJIf2KqQhgJ7g0MJ6kKyqo0kIUnSU=,tag:EC+AOidB96kiSl4hiN+e/Q==,type:str]
  MINIO_ENDPOINT_EXTERNAL: ENC[AES256_GCM,data:/8l2kXESBSmciGmCB+qmWimMUBAC+Y+iCsn0Po4v3ft4S/ld,iv:JanmOL812xQCK/YoEl0Ec5J4gglnLgTEyvn2p3w0Et0=,tag:wh6YwCZtI2yQYka99ezK0A==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:1sJiSgfbG/VqdRvav9YryfJCjGg=,iv:zXCQjysqWPLk2ph5KX/cmiK0fuE9n2WE4LjRDRRgzPc=,tag:kVQdwhxc4rM+ZO+/1jTsOw==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:AR9+v5cr2+lb4QqiUnY8kQ==,iv:QFEPcoGJHRduUxZy/0tPe7BlToJnABrk1e8MhuR+2yA=,tag:TqM5C/X2ekvvo9jwlMAqTA==,type:str]
  MIXPANEL_KEY: ENC[AES256_GCM,data:NtJmhfgkO1Rgkb5kn0/XlzbeC2Tez5iyUlDXz2rp4izWeHamiQZ40MykBTQ=,iv:ynel3wBmX65VeOgGvs3ajnwU+T+43j9yQ+ty5jA7ksA=,tag:ToApwubxwRZ/7izTSq01iQ==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:IE91VmMzC5l4ixu1Cxvecjn4wfmNx//T0BnPWGNmyf1BI5lJoRLoxwQRmTa+dP04v3jsH0NibQm5gDTqZuH9gMPgGWA=,iv:PcbsDlE9uSe+5niPrSqunLqfSzzVs9MvvKgz5JQ2SaM=,tag:63hhcrcIl59qGcAdy3ogkA==,type:str]
  STREAM_CHAT_KEY: ENC[AES256_GCM,data:MmthzUrkjGztB/obY4Mmbw==,iv:frINBXyWI7z0az7EWkZpm0kibLB5SRGAJ9R96oZeIbs=,tag:v3PJsJz8SXnGChiacC2S1A==,type:str]
  STREAM_CHAT_SECRET: ENC[AES256_GCM,data:1vmlPXPFqpVg0v+6ecwzzSd2BVRB9idL/fvA3mq3ulgCpoaxJeqBugjYa6YIMgehhfhJEimBxlflIo8NJk9gCjEIN1I/yt3cjvLCTmrRuq2Jr/0AsmxN3A==,iv:vtjFa+eWgmxQ+IfGu4RRQ05pUm8I7dQon8gZjsNRx4o=,tag:LC2ZUH1WZ6PMPkOQI5PMcg==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: muzbuild-secrets
  namespace: default
sops:
  lastmodified: "2025-09-13T13:42:10Z"
  mac: ENC[AES256_GCM,data:3TIKgdnZxn1IZUtmO2CPUlEYFB2Eva2pBrW2RubFhaJctZtl9sWyebEQSZK9yyuHecMJ6v/SLb8noVQ8Xe+3YL3HdXoObue0k5jRncXNIuOU4aFrNIFUAaPVFOho9B8UaKFSyGqU0aU2WXN7q0gAMq+OUGSPqIe0UvPGoYivd60=,iv:lo3kam1JDAizmJESo+ngzzjWyKzMLEWMz/LalXMQP/8=,tag:S1pT3bXRYKvbPaUuewlStA==,type:str]
  pgp:
    - created_at: "2025-09-13T13:42:10Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/9GxuBSSll7oK5CjxIU4gGZAeKZiRvdVublNFJ1ozHoNCo
        sfK3dkflSQ8IM/D590M4qR+3s8d4c7y+1+aQZCa6qEKvNRP1tQqSYaPcx5eyXe6Y
        b5NOMuir6uvPznu0rMYXOBUSS1cDBORldGeTpkSMpzSDDMZLDwctwj9Qba+3fRoP
        CCXdaS4tcHXj0WYE5SlXNL055EKFNWrLEBxHId5KtK1fNpSlPyCNkAhe7y2Q4Y42
        kIFRbbl/utgOVIAhRcosX7JkutJymC6z4G58c9T38ct9yfIN7DcuZF+lBxlj3okn
        DzEC1zJ0TAEKK8LBnFQRTGDuosytpfZJVyEoUaECUBSwzoEzwoH1LmxlZGtlf2Z9
        HTYOIB5tE1lKpcEDHFSpOprvw1vPe/+yRqvnRVzu3hPBTHTZyGoP/5+2xhJhh8j6
        Xznupmt8Rsr+in54I2RBMgX0K/lK3ih1654St7dphcaiBgU4xHdvYQz4QBR8to7j
        HuMMEf9zolxv5fs7ckBijHoEfFVk2Mo5T2sR0QACt5DAgWMy42X9Qn7yogEDcodm
        zbw7IJKXLQw/fJlY/jLUtxASL16nGyfZpar3LtED4Aa1CeHL7HpvBaVuL8tbP22I
        ZDHqEPcfJd/W7BGhMW9oLnQxx67gjpQEW0PPUJLVfqvfBbBXaQAhTt27ZApQ8hjU
        aAEJAhD/szjekTx1UAyCBXIHP1WVGG7yYhPveugYWsgAEyRH3UcQjg+MOrVaK0XJ
        wd/ncGOQVGSva6WJ6q6OU9cyNtdosvQcUeVc1D4sbHROTWa0bauzilUXeuXQ13YL
        qO1o1E8BdlJU
        =Y9vP
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
