apiVersion: v1
data:
  DB_PASSWORD: ENC[AES256_GCM,data:agcyUtZZRebC5a7pA5fHBblSOK0=,iv:I20Jb4jl7LA9Ca1mXp0SeR3OE0DohOFKx8kIVTrrbMQ=,tag:FtgnP0bRMz6pWHUSps0LjA==,type:str]
  DB_USER: ENC[AES256_GCM,data:0Nb4QIv5A13JUHbJiVN15g==,iv:PV8gnQjsh3vEpVNRkFOrBgtFq5+WDgdKCNx1WkVtPHE=,tag:lMJ4Q4u+t+7Vyb74Ngb/pw==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:yExIZd832sjg0hNIxUvBLP4JJAv1XawL,iv:GXrQogn4WoHpfolNerCiUL19wjgiNT7xABLgvK9T1Xs=,tag:kbw8Hk5YulcHQoSqITKWKw==,type:str]
  MINIO_ENDPOINT_EXTERNAL: ENC[AES256_GCM,data:LpSO82Uk28NEOOU7Ii4tRoEDEZajznEysmLYY0laNQYJHwa7,iv:oskJH/Cnd312RumX1W7nLTV4aYRvL9MOxqop4w+PEqQ=,tag:dBbBIlCyyqYdV8tlEI3ehA==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:v8ziYhhMdvyyuQavUn0R64Z6IEY=,iv:nciy59F1m/QnapL1pdl/dSEbCuURkd55h0GAmPjbuCw=,tag:XTYReG0C0qgZqIuMDl9dBw==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:QAkDK/Pog6v5zitqApQA2w==,iv:J6OKYoXBZW0pkTwaI/Ri6O5HEJ/49gLd5Vku3f/4GE8=,tag:TIOfP2vbjvNfFHX+HIsr9Q==,type:str]
  MIXPANEL_KEY: ENC[AES256_GCM,data:ELVNbFDfuF128b/o4kIeVzEQ1rPiFQqGHXDilqKYj/Zknm74pPx8Te6jzCs=,iv:1ciLaVEZyFB2qoSbroY2/OB/8btVNfK2qIA+aumc688=,tag:M+rxFa1qRosnExu/pNk8bA==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:Pe54E0lnU6kLH2PZ5K2JP3EUZ8gC9XgPj/guH05rPLpslaowcxmTrrj2XaI9bdZGR1F+8WMQSgx34TZqz2No7Jf05x0=,iv:HMPH24X5Yxy9i7xXtKmueUJTUSRDuGq2jj76gF1eg2I=,tag:LO224EH4H4yo/ulLxJDGhQ==,type:str]
  STREAM_CHAT_KEY: ENC[AES256_GCM,data:+gj1TFHNeFdJ5eAO6Q6HQA==,iv:b8c4ob04zGEqBfYexX0h1cMkGG0v25O3ZK8wdKjHZTc=,tag:phzxjGU05Rwyhcqy7f0W4w==,type:str]
  STREAM_CHAT_SECRET: ENC[AES256_GCM,data:wMHbq2+BLPtLgCsg4bS5mepcrgjbsrxdwGAXe5ocic66il0S5aRZjBqiE77V73Q7PcVlhk0oW68azZiiBf6qqVOFBWZtcZiWmyWgK4aRx5KJRCBKgXDsUw==,iv:3TOs8uDrXR6Wd9vcV1GlxVoJwY6DE2msZTuRBQYoOd4=,tag:kJVUa5OGieADsWHWFnth0Q==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: muzbuild-secrets
  namespace: default
sops:
  lastmodified: "2025-11-10T14:12:53Z"
  mac: ENC[AES256_GCM,data:hteXYPrwZf+Lq7QbR8U2bxqm6/LUDhV/Pn9U2b3+Y32ukRCm7V1cfZtrDu6UM+l3jll+JidQ0iXkoTebQ42wnSfAqM0NaxEZ6PJumkqmTSIVmcRm4p/wKcKTklNqpNdGWGQYhtSZR9a3NaR7U5U50EeIKCadeCr1ywxTYAJP97E=,iv:PhcZ++3+lFlRLX21D8hTumg+DJ4D8mkpPBqeK5c48HU=,tag:AqQz/G6CgqKgo9STDHbuRw==,type:str]
  pgp:
    - created_at: "2025-11-10T14:12:53Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//ew8Y/gt8jYRD25RQhEfkq8go7eliG8mr3ReoZ+gDLIcj
        jN1wWHhvlrnPOGAsespF8AK/n2NBgWw6eFrPl+m9v+0wBcxCdofTzhRYMt62D8oC
        MyYb/cESCmuqV0YXh3qGKcgo23/fsKo0uwLuwHThin5cj0epensHMDoWDWQDLqAj
        vHch7VVAYV0HKzAw+c/oNyNe1T0GcuTMXPL51/+9+UmDaPKhSaTwY2njp5fO00x9
        il1gpDl0Wa7vLF4szsTyrVUHUW6hytCGUMFQHWaA3MW5eOJSXf2LK1CI74ZRuBr8
        6AHeipv8fRgZr0xf2oDwN3xa7IlmfZPyI8Yhy+tHi4l+3dRMkxR1Zu1AkxSWGOFP
        4BMkvnIpWz4vPvWAEI4bbpke2YM/EJ2x/zDQvntbc4ue57ZpI3Y6uHvIxL79K+v0
        91DrnPmkpTjxrfjkBGOI85sLEAyi0ycfgWYx1A3f3gwxrkq5sWrr0unnyvu3OthQ
        ZddRnmEkE3BASGQFJwHob423+NxGdqAIJ6BXC3H8mkxkUkbvBHYPpOfvWlNXnBZX
        W/Wig30h/0r9w8oMtOatCgVLnhWIGVTnVe1sTUHWk4IzmhmH2iJTO4XNB04jBzmt
        opmmStWEf70sBuhfHJ915meDOiRH4HPOIUwkqeJL9LE/J7rVzx8JOZf5Dt+kS43U
        aAEJAhBQDVEQIE1c49CvON9M8w9KwYcNaFAkWFbnSRLMChMry7eGK4c1+mzBfKSR
        z8Meoh3qFKldLOO+ueLnBC+W+X5LeKwctTadoJm7K5yI0Z9NexnyRtC8bruUfQJW
        oTXUEEZXkUTm
        =+jW+
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
