apiVersion: v1
data:
    DB_PASSWORD: ENC[AES256_GCM,data:DUBpvyLQ+brHYXkMPQC6H68NfeY=,iv:BU2SHXhgecg/UFsvbdi4+QcvL9rZ53dW3E2E68aH5jw=,tag:C0xhFuB8WUKJakHUhyiDYw==,type:str]
    DB_USER: ENC[AES256_GCM,data:V7j3FUs/FIOapugi6jIUXA==,iv:5KjZkMnWCOikhF1iNh98afTjKMsF2pisLYtxB8tqT0Q=,tag:qElMzR0jc3ebLaLDvMBZPg==,type:str]
    MINIO_USERNAME: ENC[AES256_GCM,data:YLhYOCP+HT/jkZ2cEis4VA==,iv:cEJzw1cxgo2AzEYGwjzzAcAHctwgI69xs/HTq25XRks=,tag:GgoRTUi6lWMuJoCZRyDhxg==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:pmtE1BZc3TQTF6kVSkcJp+xfLeU=,iv:A48wPKx/egJK0j3dzrdKDaL7xf+N4HWyBr2MEeUzFaA=,tag:sMDsJlDu7iK0TfgktuYdTQ==,type:str]
    MIXPANEL_KEY: ENC[AES256_GCM,data:Jr4d6eD2vJAKeU/wrr2WyL3JROoqVpNU5/lO76E6zWzrl4Mmfq+GqujDKM8=,iv:HmmhHiJELZ8ENc3WpGk4xGBFqcgrtrAiil+e3SSnHbM=,tag:jRXITFq71ZJXN7n7YKckdg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:RvfnHbvdOJ0W5qX/JoRupFghItLveOaQ3+1qioo22E8p6Ox8enrNLeIz2Umy1Uj2dS3CuMwoSnkJAG7+6/7R8AQlpDI=,iv:k2p3QE5yPfJzukXnR54zpGyZQTeK7Kc/3xY8X+WRo7I=,tag:i3HoGqkDJeIoAKEAJK7hMA==,type:str]
    STREAM_CHAT_KEY: ENC[AES256_GCM,data:JPocH+E5DtjvFzU+Tg0bpg==,iv:fz9+GU4K7FnBSOtCNecFBvyJFBPPy517kgZGsbULZnM=,tag:7TrpAg+98FRXYgW1rMyD8g==,type:str]
    STREAM_CHAT_SECRET: ENC[AES256_GCM,data:YSZkajN1L4Rq4gbRkKR/dSPzpWvCGAfGd7hB0rqrEnBW95aIwOslV76ElV/XxSDaz8z1fuAyvAekCx2ZcJJamCfuBJ+qGQMtwmfkFNWHSo08Ip06ETb4LQ==,iv:ggYJ5TWbtA7nAOPwOBt9ECvYlXS6qii1LOylbVw+FRs=,tag:e7UW/8gdhMVJlQtGzMNijA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2025-08-04T08:15:19Z"
    name: muzbuild-secrets
    namespace: default
    resourceVersion: "298560"
    uid: c07309e8-8eaa-4290-b140-f767b1e19538
type: Opaque
sops:
    lastmodified: "2025-09-13T06:40:44Z"
    mac: ENC[AES256_GCM,data:oyGmA1FiTI6v5Th+E4lggtCxDUyd9avXyEAncZUpcFDRAzKsEqPGZjqhLsuMAQTV+WXHVr33xjspGDFIxzfNOQDT38ghSI9V2PVn/a8jer+4k8zqe1YlkrlAh4opP/epoD4ZK1mMmvw8kNVfLGVl7sglIO/9W2r5oueKwjMxEnY=,iv:05j1oOJFZlmtaSb+pNSSIDYRk3ZqgLyp+OHxivLseNM=,tag:3FzficrFVTcrMhSVD6QzLg==,type:str]
    pgp:
        - created_at: "2025-09-13T06:40:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ/+Oiyq6V7evVW5kc5tNit28qqmfl35xBgE4M3I9SGle3Bc
            wk8Tm2FBpXmKRhYbUJ3v+4gT7pJFlT0F9G5Q0Ohu1rhSeJgq4ggiSY3qszTmnWoz
            9L8sA+SIa21YFnIHJWGis/Y5vSofiHGEn+kF2gFfHX6X9agEF7vx8ithhN4O/3RW
            cbSBa3EZY0j7RmYs1utoa02pohr1D/K7o8a/HwI+cCJeEUqLgz+2fvtBLYNWafek
            01hGQm1iDgsLXMM8YcrGoN+fdxYilSNzyuLc1rT7zq9Wilu3G7VPzLsSoLUjCrkB
            Y/08mAYPyIsNl+PxNLKq7/59k8rTwJEOjqqHsLdHJQVHOBvH+Mn9fpFgMudFAhj7
            ThJIBAgL05s8Pbk+m8T5ncMKWbpeCqIBaTldUbdzd0SMXYFhfEOotcOuk3VvN+kj
            kkBVRp3ONpxZxOepr6SnRy78dn2C0TpTyx8M/oWuAlJ4IFOydnL8ukFhyxvpYE/Q
            S3d08A656t7fdAriXSQpQFx22NdB/U0oBCBgDywE/s6U9dhYheNt6IAVMgYMe3sj
            xaUZwEUfI3V613GgdOkDAM4Z8HFXE/7YQZTJCpL7XQX0qjsP/Ws6MPECm/G3JgFk
            ntGhJG4dgYf66CeqNiKjlMldZQALUbSDuhN3OeLkTf3NlndvIXRoqf4AOru38kLU
            ZgEJAhCYE5foeYaoSSBKMfnRJvnjvkfg+BvlOhWkm3oGmZCfSWRZWW2VEDljfYrr
            xMdQW73B1xUFSUOVMe96XUe3irG3Tg265XpyqweUU3Jtxt0zJZWmJvMEivK1P0xp
            f8d7B2vtyQ==
            =4Axt
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
