apiVersion: v1
data:
  database-password: ENC[AES256_GCM,data:TlToOqHAKceitVqmhgYjExSJK8I=,iv:0mqhJZSpkvahLJsJz6eHf4Ftx3AwtQgW20Y87+L3/24=,tag:A76vu4/ZDjgk7J2OZlDM+A==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: muzbuild-mysql-secrets
  namespace: mysql
sops:
  lastmodified: "2025-09-12T09:54:18Z"
  mac: ENC[AES256_GCM,data:JxH/5Y2I3Xlh1Ai6PjqGj78PuRPxt67FL+/mSCSRvNe6Pu6x9/dUV8KLYXNqf5tjmKXLpt1bjWIkLUPXx2P1shXS8zOMrEXkz83VuDaCKTmnsTh/GsC6cCD2OJya9cA5TT+Uzb5O1ogab8XR49KKo0i3IQWl9lf1/Iaa7kxHBcI=,iv:INFYxolKinupA43FNIfQWDv4DhmUJnIlaR3GIXW4/vo=,tag:c8Ec4vaDilmULw/VPh0dlw==,type:str]
  pgp:
    - created_at: "2025-09-12T09:54:18Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//VpdgcAw4yy8PyglAEL1lbdMJ9sqfN1ipk/iNNMhP8FBo
        EgKN/gZ0Gq3PzwYc013HMIvyneHXjG9v1vJgmhkTMleO9XBQibEw+p1AkQ2PIOGr
        6XAY0bVxJwc00olpgIyolEUbbo0AaBpLVoPJP1seNPJGUY672nCMVO+DosWv5OUn
        bj03S7UXylUQ6Jz5S53XcTeHB2cedWSW6ejLpk9d0veRXsln7KuzwjhPpsADTdK/
        hzvAH2w8VzTKqqCKxpzBnSVItDCl5Ps8y+59XFQW8jhAE/c2wt58we9h7eYkGiu3
        EsE/An+ZneKD6Vdds7DiAzvzMV+JAAWRP4d5Ee3BpPd4fwpYuIrPamwBwD40tR4W
        l/H4KVZW0Ox+Xh8FGJyi+Wqpb7S2xtP+ajnNkOLgJJcckuy4lmurQeIq8AFLEFbx
        nJliyLYZnCceLdzLTTGnq4wyWBORSm/r41lWxrnV9ujULjlFV3yClgYD/NuVOdPK
        CbeRrNRS236lpgIYOYLn1XGSMvOKlpWnIp4eg+RyKI1uh4XR/aHPrPQL27gEPmVh
        K+M390vLeXFMynhCrDCVD5eRKrX35HJi7PptI5ZQJd8SRd4Jmdwd79/xgueORkvb
        3DxQXEUtyhjEqD41n59ETEhqr1M8RbBhf0pGvJqe7MWMdA4YMgflVmb646zbrpjU
        aAEJAhA1ly924PpgPGSdv+1a39D/Yfnal+UtHtkYU1/ACmpUj67ImhBMNkEajV3y
        ski7/XbObLH/CDP5PuwksGlBChFfR2xuZxm8SaJf5o1+K4iB/O+JjTmaR6QIDdg5
        UCg+3d5H6M/7
        =7xUz
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
