apiVersion: v1
data:
  database-password: ENC[AES256_GCM,data:qgON78XoIdKvf/zFfD9epO3Gf6s=,iv:ytlwtNoao59g96nVPVqBzHtBjsWX1tzBhoIt0d8r4o4=,tag:LJhVASutVJs7MgShlRNDxw==,type:str]
  database-user: ENC[AES256_GCM,data:cxjZAp/dOD+69ODigT6+Wg==,iv:ChinT+tMRcfy6B6uZ7h2o/C7CPKvszMVJZhqmiP1lHQ=,tag:bbrAQMam94c11R5ACWOvLQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: grafana-mysql-secrets
  namespace: mysql
sops:
  lastmodified: "2025-09-02T14:30:26Z"
  mac: ENC[AES256_GCM,data:+vw4soMah3ly3LrXEfvyX6mH711LZ3h1IYeo9Dp+Kbt85NhM8QOqVC+oSA/5fWuK4UdN0ONnd9UwzuGTvulhil8VhQ54UuXCFxQiBH/n5d4TVpmabbNJDALWHs6DBUyDxSB4UNj5XxTyTXAr+QjQF4ylCy4+bwo8itvCjmqxm0A=,iv:wceGNpCosX6ukr/kXankBiwU+P5W7YG0q3oqgptn1MU=,tag:Ykj6NQbJhbNbTPDyfS1Skw==,type:str]
  pgp:
    - created_at: "2025-09-02T14:30:26Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//U8wJCBdDSTGdul8XhES2WpLiK9pc+AIpHflZvU9Eq4pG
        9T02ajoMQfdy3Qa5STyKjiV6iMfCrhHhEin77QiJWogTk4OW9c2bvCo07FhdRDX4
        5y4Ouv6+Bj2q5nyTdfwRlvKDIo2WSGQtagm8URQvyBequWgEDNk7Qxtx9G0RdZ75
        KkKdCbUS8OqlvqzEbScJhd8N7iwsPuUhRMr7fngwNiKQBm6+HbtDtJmmKYn/qXQ8
        RarUCZl1ZG4/LkFZ5cdhURVWt1j1N6Te6BDh6dm7Tn9LWIYvZbo9eUnuNFWwOSqg
        wT/TiuSFkWaps6qwJfWozdCJUGT4oy/V5OSDrNnFPrh1CJP5zQCqJwZ5YOFlP6Qm
        zqB7Dua0xbueLYjJHTPr93DZsUNZX+2C2hqPddTtHLzFAeJqmifoWbBAVW+hD1rC
        w2yzhoeaziKfQvd5lS3ZYY+ifsYrGGFLbUNgxUxW2iwfysGyhAYUfp7LKX47Isz/
        z/oY5r72F9UaYB5j6G966OXCZ+bzRjfQTwBLOnnd3GeZE4rFEU05zqrvcnD2MDaJ
        D5SpUhWhbOec/4r84xPiu1l1UzOAejz2G3H/M6kdQ5hKMxxrT8UBoJ+sa2gF04pO
        bL5vd1Z0anCO7yb/ud1HRLRuJJ9TmOyo97peJ5mp9I8bZpvCR7HaZL8VMZj9y0/U
        aAEJAhAdLLZ+/2yMHGUzrUi6vwsiDnS7phmEoWobBjK2Eb+TlMIIZhQ9ajn0f1dw
        r9UhIGRnb0ZIjDHs9BH1JpJAM/p8dKd8U9u1StCmDr50NaEjiyzDA3kKt6P4O8Ra
        WdJQWF9YxWAQ
        =CVvy
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
