apiVersion: v1
data:
    root: ENC[AES256_GCM,data:hKQTvef9YM/Knx9NiJTxdLn9aFg=,iv:NW6viLRfJNa1GBmzAsNhs7DCLeXZzQKKb+E+OvF0OyY=,tag:ExHtno+TRB1/E/x/GcowRQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db-auth
    namespace: myapp
sops:
    lastmodified: "2025-08-31T14:55:20Z"
    mac: ENC[AES256_GCM,data:J/z6Z57OxfGTqqaMGFCHxowfg0S+7Fo1hf/MkkH3m/4j3jMvUBltVN/K99aaKNnsPYDebA8K5t2PCZNiJgWwd40SZhnCKSmSbLTLFmPQVqv4lJp5WAUaeL3p0Tqsab4aqAY4F+2GnaH6azjy3wpMQx4dYhtAJ77Z1QUgt8zdL8M=,iv:4W+anRWAu0oPbC6OAj1LfWFyX6haEMZP+nDgpFbRsEg=,tag:u9rSug79aUEyep54zy6THA==,type:str]
    pgp:
        - created_at: "2025-08-31T14:55:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ//QOT02L4nuMoh70NkGDsfxgWWVBDh1FB0D+qr08MEixVt
            gPaKPwHeYsknfs3oBhy1EFutvjw4WvJi0mtrVZAPfT1KFYgQbEcEO7JTXsSFgm53
            XmZ2fZsBEYjM+VY3XNfS/4P/QqHtSgqAZgdNPDSUAjeqlkKCyBeWsED6cu/6V9UV
            0dEsFQvI3JAEd61nq6q0Graqdw7Q/Z4T+NvN4kpGtI4HEFWbVQ1swi474aaOfapD
            wChQeY2JlzElfRfAbuHk++mhz5Nyr7YmjKDmR3pOCwMrL5uFmXPM4R0SflbHhA5q
            Mu9CxL9Fv5/ZIQtwKiPwquVaprg8rmlNOS4psC7MNOMin520i7i+wK8a6oQVJMxF
            KsNJv/rmiV5yldELHZRZN66l8QpV9ZWOsxl7p2aocHfAaTr1GRq1mqNCi7HXuPZ0
            d1Xy0+vWHgrJk4ZMybLtVZP3z4RorJfGmlurYrZ3amk4AeZmIROeer9cvFQtEsmq
            lpTB3UCGniFVZMEePzWHzBW8Wd2MZaV0rtoPTHKYf5K4kX18tG0ph7p5c/+nt6Qr
            6VhlLlLdb8h8QTnEdsX0s8e0CwsJrkoperW2xgvEKkI5MAmGt6T2ekxYvN900xu8
            j9AyJw53yZJaOiH7KzAfD76JZz7Yw6iJM8Jl9CRyA+zKLG/gM24bNAaIuDolO1/U
            ZgEJAhBuYSNkj3vfunYE65Z6jM21goc3VNyT9egflv7MZMTg+20cv9CLPKlkyUBK
            1g9or/+L6qhRCSwB1VrEIR+tf8s8Khu4KtAvKkP3kpM6GAgRTIH0bMyAkcbdCP22
            0exEbyo7Jw==
            =6oP5
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
