apiVersion: v1
data:
    root: ENC[AES256_GCM,data:oeH/B2Ul/sTW1+zybPsCOWDHtsg=,iv:a1EkSzObvUGcRRF3P4TKJkVPXZrqunU4jKGp/gql09s=,tag:vuRJ+20FzEPLtyRZe8jENA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2025-08-31T14:39:08Z"
    name: percona-xtradb-secrets
    namespace: default
    resourceVersion: "898656"
    uid: 2c143f34-4eaa-416d-a6e8-539ee2e73a8b
type: Opaque
sops:
    lastmodified: "2025-08-31T14:43:26Z"
    mac: ENC[AES256_GCM,data:4sgNBEwALZw1aaCZs5K5+eDZGeLgPgF+PhdH2qKrJl/2nlR6N2TOfe6WjdXN24I2AmwGaIpUioT86q6petlHo6wUy0YYQwJu9EuKdWBB0XPhRkI8dvIu4+V/xm5B2rkrGCnYPcvZ3If2kZCvw65EAqeNhDimrptHYk1IAmDotnM=,iv:hzfhbv74HaU5HiNqhA71h532liCO5z+v1DjO5SL5C3c=,tag:YsQv8MDU08VIF/0rl+AvQw==,type:str]
    pgp:
        - created_at: "2025-08-31T14:43:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cARAAkF6FtWMSue9vzwdwaqT1DVd0OzB3BZs8DmlXlVc851Vs
            x5zAxCISkyatr0cqoWZAWVxSbN9EDbBN0bSwcmd3Da605uJRUoO+6A6jcyhSuwxd
            bqdnNcjsau9vapmep5eyGPwePrtYC4i6UWRK5wG69nSczT6akNPOI+RGr5hl2nMk
            JoXAFEwRPtdarfS9+0KY7hvExPUQ3Wk73E31wf6HUKPMT71ulQzxXhhVF9tDFPK5
            M7FxvCRO3jWTWvzEJiES7lEKKV2uXZsSk/v0mFtjeEPk3+Y3c+CQvUkLgpl1hsCi
            R9FCypuQcSei/KK63fHlPv9jML4SWZd2kMhxAPyORI6E/Ahc/XiB6mv5Lt13ULcA
            Kwg58TndKTNcyRuyiAC9P2d6wwqTFMtenUNU1frnzRAAhWV5wmKWrqhGicXKe1YS
            JS3iwT0ajLRVK1DLqGOReYeSxZ89kKP7oE2eqURlhVJPludSevrQ+liCy2Ss8yTN
            sOfmDhkN+eR4a9qdOpYlQouu2exOLcnB3gYK/CkRxKL4ZIdL0x9/bgXXpDPfHyyU
            aI6/K8PJVQU2e3femilhaBeP6HdEzP8Hcs757OgyPYRs8lcd4w4f+SQu3OEW5Jma
            r3aT7kR/rX6bib2IMe+IqO/MqagkOl0L9G3A7TYDkEzQapmx1aio5ijXz0uGe4bU
            ZgEJAhAoQMJfYy6GX/J6NIw4CXFUZ3Yy1VVhxSVaa8mpRCz+rU3JGLYwbwRB3p/b
            B3BmHMyGjFIZPJFjstD7Ymxp45wajJEGRZFPpoVEABJHMmcJQlW3IQvbRkp3BY2O
            6tZKfyrMTA==
            =yeMa
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
