apiVersion: v1
data:
    root: ENC[AES256_GCM,data:zPeDGjLWSI0MZoBTMQ+AFwZPni4=,iv:Yo8YIrCoWC3OndwgmMTSZBQD+k1nptujsPpCL47JXmU=,tag:NoiBvX7XL2l2DXr27Sz3jQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: percona-xtradb-secrets
    namespace: mysql
sops:
    lastmodified: "2025-08-31T15:04:23Z"
    mac: ENC[AES256_GCM,data:M4rN/ctITPSUInyhWzgiMjuVSEfpn69nP65A40p8yc5qfjMco8zSGTY4zkW+AcJiwVsy3f/miQryn7wsPDAg5/HlAnHMJZncJaj3MNVXFANNUQNoZimG3EzOvvUIaPK6DrPQDPFVtTnzW1Q7lgRwaTFND3g8GBWGY/unZ3Gky2o=,iv:Z8mEhBNDJHkI+Jb8UXdnm50iPHJtVvNqOb+SJ2jCubQ=,tag:EboHiXi2rEKLcq+Ne4XOrQ==,type:str]
    pgp:
        - created_at: "2025-08-31T15:04:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ/9HSjbJyQOVWpPsjKVjnDvw9ULM6Ik5DMXbhBxy6deAWNA
            W7qmgviqAbMgApyroZt8UkNqMZgvm5G5wqD/AmKlHsjNfDJwCHE4WOdM/1CNbg4m
            BJijdlszKrr3kgSFnLfqm+9gPYBpX6hHnWG+fNto0MDposE2mF8fLrSb9UE/lqsz
            Y5+Kbe02dGwvlK4aAR/hY8c6akoOPt27dZsDwVNdOemyAYqYk+1KZjSdOu7qbtqh
            NxPh8mUdtmbPy6MNWUvItF0oE7bv4nfMUB+KiLZWSCaoEIIbOz9n8E+mHWFhs57h
            MbVgS8P33CYZfYEPA6houZAmd31EQZK/fuml0dh1xJNOiK0kKMuTOcLsSH5ER73a
            T9FqMh/va/bpbaMV2ACcEu7PW6T39U2bYc5NFSZfRKKcxJVzuaNr2M4JF9WoXu8f
            2e37VN7poiuRWUtZTXZXX2lz3UQUnjfisD/dSB3WOpj2+bjeVJZk2NcnF41WH3we
            jNcKBRs/1sEgyQ6j9iwkrFvIO1mVP/8YvOdESmZrpPCXn6ejwiAPJAGH6c/eLG0T
            Ycu+ZVIx3xXmCFTjGZv1tAb/m2S9SpzK+FsaRVrIAAvd4G/vt8hPF90uGRRjxc1f
            72eF+XTf6yZQoxjfeXkdOMt+2G+T8VBvqWNHmC3p6JmbRzLGpuK4cJihLVBMkcPU
            aAEJAhChg6EkDBRIJWxU9j/7FAF51xMWNGOQjnlaowqGCc2ZElZL30n5mqVwwZ4e
            alhqPYysp/7ON8YUYaw91PPT9PBF2+GUlhVpw2WlyoSNNAwDwRHNn7svpYenrqWC
            TVFkueSVHZqj
            =iQh0
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
