apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:D4G7ZddpE8S5SyY2lCTzjbMbJcxol2cL7VHCP8+zzZyz2dPoh0OcZXEvd8iJLDrkGNYWK5vSieZnDMyHdC+TUma8t6KT896+,iv:kBuFD3AhTRDgdEM3qVBR9XeqFkqGW0HCD5J1MyBw914=,tag:PSwsjR2Xw9lPF88Mj3eEIw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:Oo1W0Y6usQHnMasP+ZO8as3iysg=,iv:coNiItKa9yCkLR2Xm/y8ybL5mrM5+pJFl/gqE92Y+64=,tag:KKBTUpMa4CsMTsOMJ7i3EQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:8XV25XRHPykie8ZAIkqPJlIXIQg=,iv:JcOf+xRZQI6vTRfcoS+2HxhMTs8natF06jSRI07137g=,tag:1cp8hndxgTEY3yJWf0yL/Q==,type:str]
    DB_PORT: ENC[AES256_GCM,data:w+YYBCSzNWI=,iv:SH1zjSPmWAx6E/muy5jv/2/VEIswAy88ma2RC8u7M3A=,tag:cuG1xFOTB4QqhWIumg5Y0A==,type:str]
    DB_USER: ENC[AES256_GCM,data:+qMQkh7cWqKBnHsaQcZQeQ==,iv:s4XE0PgRg95WZE6Mlyhxb/hzAo2j+5gPxCR4491ifq4=,tag:pa/t5fbF7RgzEgCHBTHwNw==,type:str]
    DEBUG: ENC[AES256_GCM,data:vCNRXqt6aFs=,iv:JGM89+8iV3axYSj2Rvwvh9JgLfrGTJ6gIbxskedGmdw=,tag:6kwTxXuhaXPVSb1qMdv55w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:GuBF0HddNez1GFdI7l1vktZjhkSyzDmdqEuVj1wgJVeB7hNP2S5MpYHPTBnfGhs2ET+kSZ6EksEpk2hPcxTot8p/rcM=,iv:HtRvxWXKSlCLHUnINXr0vg+CX53FOgWe6evfYeWR2uU=,tag:P061h/z3DIJU+WFBRPmT4w==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:xyXECzV817qnUUekVpoDsRthO9g=,iv:BlYry0QestbaHUljzylIOmKZB/K6zuGCpSli0DNGoQ4=,tag:uzfPd5GoRVNkKdX3L0jexA==,type:str]
    ELASTICSEARCH_URL: ENC[AES256_GCM,data:k3VCZPsS5yh/n+ztxnMa1GnSF25DBFBvbrtHUOuyDrkyRnvnsPQIrVvCaYvKEPp1BhiquER3OkpeoBcPWVWLMzqLBmEkqACbd7qCLQ==,iv:GBEaqRgGKLLF4CLUxGNinSvrp6cHR/hsg77sWXScmZo=,tag:FOPwEPdP964n25mRrl3Tig==,type:str]
    QURAN_CLIENT_ID: ENC[AES256_GCM,data:vr2RWpYSXFnmdZmVIGwU4mYmIk9XqbP47aRz1ZTmJOtAkagM+fqkCROUKkJ44qMd,iv:Bhh01UtPSmSuYyEb7jqLu46vBpwklzAiRA6DbQoMY8k=,tag:zc6oj/M1HQFjCIDEwBH4xw==,type:str]
    QURAN_CLIENT_SECRET: ENC[AES256_GCM,data:2wtTsJXlJkC1zNCXX/8ehzX786a0Em7+0IdWeyjVaXyR5cei,iv:cyuI4esDPYRX8kX8SwBoS/BSBjm9oRLCsN55OpleJ2M=,tag:4neKScXbGg2u3IxCBl8WqQ==,type:str]
    MINIO_USERNAME: ENC[AES256_GCM,data:dE/PyUVGilgpssDFuoh3aw==,iv:6ZrgxQDnd5Jb0z+PjadESUopzvAX6sv/EjHu0lqhwwI=,tag:sTUzH8vx0ErH/zemstDHTQ==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:XfGCEdb6eUqneNT1tTFtwzCBDQA=,iv:tPv8UstJ/9Thyfezv70D8dxE8HTmsGp5MLdC6Bh9gaM=,tag:e4Cpwrk8wHE7cIu90MClbw==,type:str]
    SPA_SIGNING_SECRET: ENC[AES256_GCM,data:kZLxDKVaEvI7nUo6PEV4Hjkoct1olplneWXE0MTnNnBW+fL6zXaFavyb59BTcTswmWlLf07wLupbJgbfK9X0t11khS7f3j8DrkJwLHwBF4Sii2+sYg8jFg==,iv:o2h6D99kzIKZXiD+2Fd+8BJrKv8YmJMj8tW1ocyRNhg=,tag:RzaQ5j927h+ePmiPx+Fhww==,type:str]
    QURAN_SYNC_CLIENT_ID: ENC[AES256_GCM,data:OovukwE0m0TDUOhGMHY8c6Xijb+dmoiV7gKCxSC1ditZ4KhZMWjpxfV4352TTL3c,iv:FAdoV4WXVCkRnDrFWQXFDJiX/A7hTaDfBz3IBqOA+C4=,tag:xMxq96Jn4hvBQMTpCtcE7w==,type:str]
    QURAN_SYNC_CLIENT_SECRET: ENC[AES256_GCM,data:pnhtHmYpk/cyHZiB8sbOblB8jkNy4JSlUJAHCCqsyJ1Cn2e5,iv:k6JxxaUVrWt77GLBkMKzsvokYotmN3agJDA0ngY4QFk=,tag:+S9pLiDDKL6XRQAxEvuovw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: qirtaas-secrets
    namespace: dev
sops:
    lastmodified: "2026-09-14T12:39:12Z"
    mac: ENC[AES256_GCM,data:d/ZqsnwrsjB3sRs2BWy1sjU3tz8K+pZmCU38cQ0QtknvrWIH21nv3rcaCoG0Yusos7K7UbO9ttlrNCJoKxI7WcQJmHSPxtA4q/HVCCOLkp46GcTvfsM4ItH0JmT7gb4yUY3pB+Y8Bmyl9ccMh2yhklhO/GrZIyxXy0GX+urBmfU=,iv:4vBKeHw++9kmjO/aP/3qWldiqMo2ldmiGIVPfz/G+Cg=,tag:U24zISz/E4qhzyAWmDWhRQ==,type:str]
    pgp:
        - created_at: "2026-09-14T12:39:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ/+OekEs8mhBWyDrGxVbjMtxSf9kDm3n1me1Gak6vSkSBhl
            EAzkGUJPqtRARvbUUVuQ1DZVPV5LWjpVGX+LhY8/hGwo8uw02xDeV18sFsvSr53M
            gnxKxadOvfG1w/xVnj8GXEoIdebtGpiJnAcOR2EK79Q9Z5dGiinqmbH9YoyYeNN6
            nBd1C7Gi8etZvRHRwPoB4JPbsRY7uDAdggBEDTouan0cT9DuPTdezIYH++GVhUhb
            Wr3TXHxdeZUg5beQ9qPio8r9qcGk6ZLlD/MeqPXa0UTRAmuqVJQHXossi3GbQfTb
            oXYKehHj3rNSNNrDsqz4UizyWKh50LWCjWUXqw/gVggcVz0jUyN6IVSnZ4+T5ElA
            WlqXeCqCF25W5Vv9chQLO22pvwrzkGF2NcRwGELwPrCiEO+iwMMnOJ9rU9KDUeng
            cPjN2YGn9xRVjwnsawDz+MWDkutS/Jwel0XBZZg8LO1zN+aNh3VdZftXc2U1Ez9P
            7Hoaypc9vpUyOXZ2I9PuSw4kLrIMbSNKodHMLz0mjEg+VGBH673YCzwsFqJOYH32
            g8p7yUTAtZMBnrIBz08iRdXKt768N68IlbKPOMhT6PIqZSk8QiK/H14RI4DFPXFF
            zcf/6WzOAt8kdMyDjtbNTW5SmZd+M7ccz1ZKDIUwlclI0dicUvEoUth1YYnHCeXU
            aAEJAhAyNnsxOfAJltDzEOKnYOyHu1LZaB52c+sVU3hXi+KltD0qErjmeEVvglfL
            xRiG59vc87UhKJpXV02zYDaHUaxPbmQpopot7NkKxQfyZENPw+6qhrrxPn02aGuh
            gHk/Xf7cIYLT
            =Tlcq
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
