apiVersion: v1
data:
  DB_HOST: ENC[AES256_GCM,data:NDL5O/uRwZ101ZUFwooI3b/YkJmT015SG97QGUt5kBu+rELHHAXFikT9JHMnLQUW9AbZ0q743Lwi4bDTSi8Z4uABl+btG2r5,iv:K6JOpAAs5MDpxpGYMUUX93BKguGlW+ouFGno51SNLrU=,tag:uRyQo/kA4TRw4euya4l0eA==,type:str]
  DB_NAME: ENC[AES256_GCM,data:+FxUUsSeKkjZaJ/1Vaoivg==,iv:fh/bJMd7TBbtE9reIapCjklui9Z1T4lLi7IGr/VGx+U=,tag:jf+2YzOOAdya2NrgwWo+Jw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:YxCzbkC8jlQgDgt9qLDQ6ZRNdTo=,iv:S//BSR5tSMTdlt9y9aNbsyJjD6L0t5yg6OWyt2q0bSA=,tag:xzyUm5flJit4xja1r8Nq5A==,type:str]
  DB_PORT: ENC[AES256_GCM,data:IzGikyTDYr8=,iv:9IYWzkxSG5kKaXecoUEZFiRHZyTrl0+Y675kNN9lYc0=,tag:I80AaiihQkh6wlNAZONakQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:m75l5IVk1y2Ltv9sqVDAxA==,iv:vgmsHjdJmS5+7UMaaeeg6ISN6XJ8oeCnppD03S5NypU=,tag:IhZVMQsOI24INQROJ46xow==,type:str]
  DEBUG: ENC[AES256_GCM,data:eZTeWGaLTqI=,iv:s5D6Alg2m6MBeHc1lsR3cY0j0c7h+QMGhF5HH4XlnUo=,tag:0mEYdYie8gag2P1TQM6wJQ==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:0B+9qN3QYbsqC0HHzkQkKK690BOocyTwpQlcoKurd2cYSGFby5e7fBfH4yoUvwboBM9yxULFn2DlkjA1J5Vekyr2iZ0=,iv:Xx86QHsynm8X3fOuzTrIahOI4nodlIVlnQnV8LTwK+8=,tag:wnUjY6j8qD9pix43y+mn9A==,type:str]
  ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:lYPqZafklipy0eqbn4YCwSdkAB0=,iv:ZIifRat8SUfKsRmqLAqncJIrViVyBPEeMrIViBiWy9w=,tag:HjC5/zvKWAugDuCDOFi71w==,type:str]
  ELASTICSEARCH_URL: ENC[AES256_GCM,data:xze9DERmacZQ7rHOqJLvVty5y+3dVG7OEhb8Cpm47pB2phQ5ZSXbHH493hJ/x0HlApFQl9KGT9uNPaon8oB1Z9ZVssFOLEtgVKMw1w==,iv:a6VzKK6jogrSe+5Zp3t+niVm9ESuv/208HERF/SbQak=,tag:35S7xlImOmEXVtJLO/fVBw==,type:str]
  EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:q4nSmejG5BE1XPZGuipyyMx3GkuJYSo64rnpNA==,iv:bjRfJ6jOVOdIkbdAc19vRuowvJ0YPkKCgjv2pJ2tYYQ=,tag:zTUkFK7ywD2a3CH02uQ4WQ==,type:str]
  EMAIL_HOST_USER: ENC[AES256_GCM,data:aeke1ZR5i9pNBT1Ua+OWqi0Md1vxMtlE,iv:foB6lGqL7qePEsfk6wYx6soVG5cCXhtHSC0B5RmR/Dg=,tag:THLR16fmHE+wCrbx+fFZXQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: qirtaas-secrets
  namespace: default
sops:
  lastmodified: "2026-03-29T06:51:21Z"
  mac: ENC[AES256_GCM,data:pjYa89J4cncFZuubp52reKjb40+HKHiEC2hR4fYcovfMp8LdT/Kq9v6gGMR4I/xUXVEY+eGsGWxlIbwIW84md89x5ulujQAhpuxZEf5qU77HXLm5Wf/Gx8K498Qfjoc2CQztZ1AjCg7YwAC7ub/ckQqO37gg4u1lk9ca/XGLa70=,iv:R/32vndYsqU5mPfCMSMY3D1DEtX0d/ScBw6B2hM6yiI=,tag:POmz1xFWhpJvn3ACPcX0WA==,type:str]
  pgp:
    - created_at: "2026-03-29T06:51:21Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/+KbYB8dQSHzBdP+1FuApol4LLMfhCkwy2mBhsxPwF9z9d
        atTLrDrwPBM6wT94dza43JveNrM46M1vB56GwWPWejQ+TSc/KY/+r9IlIX7tVMo1
        lfh3rdTlie97Zb3u+fUoE8YoK7HM8MWrLQJCyptkzgzsBKIhTJLsaQmJR5fXNh6v
        XRzcOgC9hwEEemfia2TSnStm0UhBAf+DB4bm+DsEC457tKBFBD3uLcmmkd2gKAM7
        6oC2h/qJQWFOHAGjcp64mPELiU7J2i7S3MZL7+677R6XbNO0l9UEzuQhqEE5IwC8
        qfS+12OOg1c3TQ7mVPscMKPQ6irLMa6sEetpdvajJkl/sQqmguo+K1mdPfC6LkLU
        l+IOGSP2CF43ukB5Ei4oRMLyP5dyjXmBZf+0Vsjowwq1gWjL67ydiIFLFkI7p0ge
        fKUkEVIq3vHt0IpwVucEbM9GhtT0J0v5h1NKfV4m9l7YnV/RCVZQKrxBlpo7ofTi
        qk/LDt5vxoHZVjKO32Saw0GLgouklcJZedyx+giZKKCPAvpypXHBWVBI5sXPog7y
        QxPuqhz3QK/lopJZkMUCX7duDWARDMVQDOM8FAg98xsPXUFKLgq56SJyfqnXJVm/
        HVDWcXZbQOWr6lp00qLffBxAp6YAfXiG27zq2iOTvsiEvK29sz1VlTAhozRA2cvU
        aAEJAhDwYjguL07es1dsy9fRbZBu+Mi1jn52ZzQT2+EE0dDjAd+pHrkEopJ283p3
        tFJ/Djh1TV1XnZzP2OKTaLUb/i7I1yWL66Iap18YM0WyX7RTUTp1lskTCbiZMVS0
        gA+pJvjDu/B9
        =bzZ4
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
