apiVersion: v1
data:
  DB_HOST: ENC[AES256_GCM,data:gmBMP4gJa52pslTyoac4JzVCRo1Z7LFwiPNv4SQOvDR0IJzcV5tgjKzxH9TcqGB4aGUMOOGrSp/3CDZQeIwCVdkm1ZwrDkJs,iv:qJ9dqAzdmjr3LhHygTkuJV05v2zRDhyE7o4caYQtc/c=,tag:v2PXdfhFNToA5ISXzijAUQ==,type:str]
  DB_NAME: ENC[AES256_GCM,data:hURm2KTLoa5fKuykam/Pb5UKVPw=,iv:T0fQ58BJ4V9nUjkFYKvN6C62TRw9ElHHVtQhgir2KZI=,tag:HrNFSQThgZLsxKKslFgCJw==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:Qebuc0UX9M+iDNXrncqFMQzPvsk=,iv:LDEmfgkdNTxm1GSfHJA4XtgTXi524016UzuIwwQg5ZI=,tag:XqLN65BTf8AKNPK+layndA==,type:str]
  DB_PORT: ENC[AES256_GCM,data:vD5nN85s7UA=,iv:3+F3bmx7AYKwKR4U8S0yxwL5qsuk62ASYFki3OWcpDI=,tag:VKZxHrnNR3SJWqzRsDVlaw==,type:str]
  DB_USER: ENC[AES256_GCM,data:Kx7gq4f6BA0QhOm7W2Lctg==,iv:Y1t2JopcJ4qc/FLQibp8W3BYYTaltJ+8SPxBWIfxrW0=,tag:fPwDUY3cru3srubyHf/wUw==,type:str]
  DEBUG: ENC[AES256_GCM,data:sWCsTcrkmHw=,iv:/q7C2FV4LHvh02iG2AwctjRXUxHSU1uPMTY/4ivznYY=,tag:zGnFOi/ExwvAhaGvd3EoPA==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:Z/MS34LPL7RRKpnm3pGUWHqV3M9Z0aK731vOpbe1eGhINeEZIUQeZEAMkBJnzb+MTfdwoX5JnSq4D9UQjAlGok17e0Y=,iv:j+i8MmOinc53nYAQCpgubEiaW1dIzt+DX7lvkPytW0o=,tag:rz8P1dArVosHpVQ3K9lVpg==,type:str]
  ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:4ZFseEnmA2FXtcWH2G6q+3WjcD0=,iv:FNZp1DjprToITiN02VcsvSg7D0ldpAfiv79yQC1RuSk=,tag:Ty/U3l+3PnGzLEzTIkYThg==,type:str]
  ELASTICSEARCH_URL: ENC[AES256_GCM,data:53oWZY+GPhKfEOQOhGKy96I0NrGoEFN30c0VLGjSjlz6wH/9mH0TLPq7KjHJVbwKbzDTOEXMhMx6EvSNITam1ZQhqck/QpxKQTUeJA==,iv:lejyoTVYNz8aytPwKLsieDgzVAVAD0TZ3F7vbFY800g=,tag:hlhdEnXOC8JA5+kkbR3Ogg==,type:str]
  QURAN_CLIENT_ID: ENC[AES256_GCM,data:eQ1JA7ETYvhZo6G5srtgFFCJCbbAIppMmrRIFRJ/R0+F/ITxnSlPH2CzOXm2psgE,iv:XfWVwwq1Jhth6QvKrgJh43jWdQMAtYyRyUCyL0DUVPU=,tag:0FXmSJX/3a9zWoy+XqcweQ==,type:str]
  QURAN_CLIENT_SECRET: ENC[AES256_GCM,data:f5k5/quvtKS/f41aZglsAUs+EfaWPK5UGV2IAVDhEjzZPVJH,iv:5XQ5SDCaS8RO/HhIZiwYc0yr8iM2ebR4LmxDTmCDSwg=,tag:yALMXW3mo0ZgLt+VhbvWXQ==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:05hocCxzlqH6VSziJ66HLw==,iv:1Xsx0u/MVD6c1rgSz2UTaJ5X3aXBFA5Itt7k3TQACTQ=,tag:I3/vzRoaZVa/ZY0b9Z2zsA==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:P1qLquRPDIK2eVCjc8dPnvA8xO0=,iv:KMjAxTRvcQ3IC4aVzp4hyrcFMp2DiQGZmavrVfWufh4=,tag:/rzYDRDjP+s7P0IQ9QqJ+w==,type:str]
  SPA_SIGNING_SECRET: ENC[AES256_GCM,data:CwWzcyw9WSgqPk02mjudw1NSiWRSm3nzdVusMgUDrl1uGR3LfFB+c8DrV+qu1gmQvy/kNXJibI0TV5QtHTsFiD/PbXZbqnv4G6A3le7iGvCCLybZC0LZSg==,iv:UPPncVwm9fXjSwBNKVWUZej3lDmnZ2XUPAmh296lf3k=,tag:yLJNLePc1OKReDVqGUIVDA==,type:str]
  QURAN_SYNC_CLIENT_ID: ENC[AES256_GCM,data:eb6UH2Jf/ncygtp6+44Ie4cMWPMeZvVeXmDC42qgah9dr5bpfW9oAhcJLw3lTRYu,iv:FNSdi7w9MO6WqlhBhanlmYUzfFwOgUjZdW06aDMT4eU=,tag:fjQc2dmv1qT8fzVc3k7VCw==,type:str]
  QURAN_SYNC_CLIENT_SECRET: ENC[AES256_GCM,data:1l6nDIIN6gAFBBe6xyz9nPTvmb1oemQpSdHwmxKMAMHAD70v,iv:c/3C238iIRzrVq/N+QzpwaLkS0rMFVUXZhF2qp26bQI=,tag:hfC10i9BqgwthVVOYPzWoA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: qirtaas-secrets
  namespace: dev
sops:
  lastmodified: "2026-09-25T15:30:15Z"
  mac: ENC[AES256_GCM,data:RMZXCdEuOcZFeV8UAbN7VhuUIWH6qA5P6wW8np8JBul+ALN0D97lh3bFKiidWLbL4iqwGFLLTmNXW8bXKKioxUFLLx93c7YQMcRL/YPRnUObYYSujJxP9o9nF7R6LnrkV4LUzdX09UCYWHv5VXQgdJd2FkApUgnpRpkqcDp8q9w=,iv:VXhrmklYMoyvrWwaYF4lNiH58Ps3dOrDR480E6JKieA=,tag:H95ufDn/IeHxCUUSpki1Vw==,type:str]
  pgp:
    - created_at: "2026-09-25T15:30:15Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/9GgJZ3PMQi7vuat0FXCHrGRAR41ajomvfjnFf8GVEWCnd
        91wiyYI68NZfkrl6tAByjjIUFNt9S4I8Wy2xHc1zgk4XniK66pOBu4VdGlkXPaA6
        EA4VT164b3+ugdBTJ8hCUNivOUOtoxUCHr6VaqPVobJKo5+yPnEQwdRukLPDW0+q
        XBOFL7L8JIeq10ORgZVEdjAreCNnFwVul8iVbnQNiYkzrFXLLVxywshPFivxwZlr
        7EqcnJK+9hhTzlgkG2reF7E34XqAFmSZ9Oe5QBMB0qLI/9p5XghbHOugo+N7IV5C
        6EQRq7z1dvXF9nCQiyk/a4wjTvlWChLsLVN+M6LDomIUDu5zFioZ9WOELF21Ltaa
        jw+9Xw0osT92kLcqT06lezqf/v7Se0fgePmfGA1x/Tefk2oZPEASF+SDuNuNYwQl
        oP2jstnhmtr+5KNayxDJZm24JCiOaz+gAIYw1yJXofNEJwt/jKsWuGdQQ5vu8Wlm
        LWnyerltBK5ejFRFk2PQGCsfwN7Y6AK1ISY+3iWaii6BdEtBK9/VOKzmlw1if5kz
        LOBeJGmz1aU1BAW+rk3y5MwCWxNxM9MSchJSeAMb2mcHVi5qTNRtdj2kG587Lwxg
        susUEgOs0E70v/LSpIyS2TaEGtBTC3K5DWr9AKJjowILTB5E5ri3NuRYguNX4ePU
        ZgEJAhBAudfqKBRIeEJvaFkL3payLpXmTD69kVFg+diWEnjr0Ik3AbV5t6SW8LQt
        d2ikx24yzQBo7vvk7eETdUGke0D8ifuX2o4UylJTXyYAHcZXd448zsZpxeSit4ga
        1V/ACqI96Q==
        =fAEd
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
