apiVersion: v1
data:
  database-password: ENC[AES256_GCM,data:ZHyyuS2ECF6c4Wsknwdrcw/PbPc=,iv:2NLjSk9WXe+WXxR53oeEhQ78Nkl6kOqT5ytyp7qAqg0=,tag:bZZTJ+5XAvgRbm92R8k/OQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: qirtaas-mysql-secrets
  namespace: mysql
sops:
  lastmodified: "2026-03-26T09:43:52Z"
  mac: ENC[AES256_GCM,data:22WXilgboYn6Kx2gu4yVCk3SG6FYjoVUdC1b9Afx9WuFOPO63UJ+wDDD1nsSJndcEhVI3fBeWBgBYAL90bmHQIxe2YtVXHndUHYL0SkroWqB86Cn4FXZTgaYFfjS8cQq58hDM5NWIaATdelnC68qZWGR5IvwJkzWN7YT28x2Jj0=,iv:tlV6XW5WUgeeEi2yFgZzL5Ueyq3jM7wYvYbxAiMQ92s=,tag:+zXdFcM/t3wYMZifOLr0dA==,type:str]
  pgp:
    - created_at: "2026-03-26T09:43:52Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//XhzIuFsycAJceRUE7rQ/8R2oKN+KHvAE3F9hP3ToCqwn
        mjqGAA++HzBBY8ui7HWihA/9Y2qMKXxRPBF8DJbFnxjdpy7NiKCau8OZrxZvJjj7
        099JX3JKki8JOwyTDeGmeeKsqHqWUmB9f3s7KejimSj11c2M99DGtZzCZAE/qaMM
        wQp6fPxAhZWAsV6OQPCrXWBLtRZh4CThwS+smQzJAfg6+mAXqkpUvACwVsvZ1dFA
        HiLx7Cfa2Bu297uq3QaMXSylwidDkxef8OvinadTsFO1rBFRWSVvDkErj5zWDoSo
        eG4az4RAeqQoyLeY56cs3dmo6xL1Tj1VLTnR5jWXU/FWczu1N+yhJkzEhqeeFDIg
        JtoILeHoAFh25PnIXBQbKYtItQ04vDqMSXMhoxLdlG9KNjT/8F9LZaK3JKjsJOQT
        iG3c8BCq5ufby/hUwGii0y4kggAvb8WJITBk6LcGIftfd24Vq8O5w/NAGiZl6Me4
        Dn7DSu9vqKAKEDxeJM2iAIV7oL8f+ocquafsjaOIj/A9QpLzzi+4kQ8LRY+vlN2B
        ikspsRiG6ehQ7Ov3/NBZIGuYiFGDHINPc7hpGvRlKxsTl9G4XpMMsNpS1bJnewbr
        mN8VevnLvhJu2Pcxj6AyMDZFfOgnwp2QVLOXEq5ivvZgDXweVeWYhUEqIlNoyr3U
        aAEJAhAo8tZUwibmsvd2BZvaSTKD/JsSQIR1O6suecUVhO5z8gLn/Q0CNZaVdkR4
        DEypKmMOccP7b/UW81fqRkjgh2gHG3mcJMWsZkRfvkDAhLZ0q7W7mK/DOZoVn9s3
        u/pnVeoLAxko
        =4SBp
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
