apiVersion: v1
data:
  database-password: ENC[AES256_GCM,data:CaamWzrHmZUQj9iJwqPw9oClf3I=,iv:Xmw2FeuOXCcclQgmC8PwViU2aCGAB6WiloyGp35oNZk=,tag:46QSVrPEkJsQvgYlmRxQpQ==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: qirtaas-dev-mysql-secrets
  namespace: mysql
sops:
  lastmodified: "2026-04-12T06:53:49Z"
  mac: ENC[AES256_GCM,data:Xm6fwecdSZrDTDlofkD/vH3pLML8GZmjMBbwt9jZ5nC7v0LHDYMIgXf0qkeOFypok0TVb7OF6m9eZRf+07xrnggJlZiUcnudKqwG2NK3OEXcSnofyo1LCPJ0VoLkghImcno0OH3OHAzDCjXZfWLdd+SkWAQHFTV+0vOh3nOaHPU=,iv:0BalAjJOGMdjIXm/ZFUYA6TDH/pcLE1UhGLudMSY52c=,tag:RnipLrdc1AjATTlw4efStw==,type:str]
  pgp:
    - created_at: "2026-04-12T06:53:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/+KGMaZwj28ggIAqndNLwKsWPZjEnb18NJlV6fPIBJL6w4
        j6Dnj/eV8CuKpqWxU4QPQIRmmnhLTHD0ytU68ZcurjvdAfnyOWnDAOV+llwEANGZ
        Stb8H7sKG8uQOLemdFmDD/blrnjQH1nf02HHV0O8uzX/IHRvC566HPWi4Gie/cgj
        uBMjUtzaRlDeRFcB6A8VHs1rVJYz/6LG7Oa9z6/jSgToIyaB6iBJ6SViOpZSlZsi
        HpcdgszBRYlaYeoTRtXa7Ee7fd7GPMukiAYFQZG3VeFT43GLqBmYkMev8Zwc+iDR
        tPOUsr01lhUwrOJTkhJMnWhm/lMwcrHK59lFW3rTMZP8G/EKFBRRf9lCwxSnmeXN
        0iYNeaGfdHGRIuTV20jEvKIUCHH9Q5O0mpKpZ5vg/c2k7KXhNDEzLk9x1LlLg5dv
        K3DpzpPTmVlesNGSHnpsUVaDPdfz0z1lDJTM2DjkXMXJbCaODr5a3LrziyRO1eja
        qYRft3iGd4jRPdXtpEzkiHQAVnVISe+cSgCVLPOSE0mbWW6mcAVaxjoH0Mj0QLYB
        zj20SK2jSRAVl8/y/fDFRH+rWe4H+cF5MjNm/pcFgnA1fluoq/uyM5+rJfBLatJQ
        WqGejP8FqKIaE2XkFlu9SxNdVG4HA2jEocOvLrcA93+pbtJNl5ioTHLJUAzSk1TU
        aAEJAhDcmZ23tCvs8HlLwpFCVihu9E6ry9z2qi3RMz0WlJawkCn4SdMrVXMSH7jP
        rkMC016IJCr36vFiF1eIxLlVK5W+6oGoQNaObR24o1tdnAfBX2zvcLjaN7GVqOwq
        1gJZAkTyTsuQ
        =MqAB
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
