apiVersion: v1
data:
  DB_HOST: ENC[AES256_GCM,data:9DVtnBm8kI0iywQIt5EWThDR8j6H6wb5wgYiNoUSP16MzbDkRHGrCtPMD/cooWwMnEC/b1RCsIYqQTt7Vj3k1a9d2Mc6zUXS,iv:fjWCJw+wx4hd3vxFnMMD5W840ruNyj1GGHJB+IKoot8=,tag:wKD2hWucqAulaQe89hTPvg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:lLeI6nuozf4zUVPzttI3uqjzuMQ=,iv:xDrmpiF2l24XUXub7lyJUZ9IQcUBdWtDPSRzMTKg1Ss=,tag:ZiOvLFQPFgi3HMS4hTB6ow==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:Ss0p0GoSXFgM5qHYy+zBBSyuD2Y=,iv:d1a8L3XWetL+7I8R1H0c8iIXmf3rCHcy4n/QBe7Et/4=,tag:cuKRVzmmJMJQzrSCUNuM/Q==,type:str]
  DB_PORT: ENC[AES256_GCM,data:wTlmz4Hv5No=,iv:zKt2Q2wWPDjART+IybSfwFaW8G+5AFvuOztir+4Rdf0=,tag:f+CA0xBCWUCgk/H+QxVkcA==,type:str]
  DB_USER: ENC[AES256_GCM,data:KdAp8swcnRfX7YfY0fHUZA==,iv:kEtrdoKuQPlvDIWibbdWkxA3b1+y65R7JEz7SUmy3R8=,tag:2yfkmRtJKxw0mM7BH1pTZw==,type:str]
  DEBUG: ENC[AES256_GCM,data:O6YEx6efsM0=,iv:469i4mn0KSdT1LDugMBxiCmXay8p5zSAo97CzXU30ss=,tag:ptRvC8hDwT8n87KIGEuiLg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:aMrzG9mWfg8JxZQcOi9pERl1K/UeuPTC6ZJUYz5Yho26Jw+ImpQ6fF1RWGQ8VBxXrSqCn6PPjoVJ1l7U0OAT1/g75Rw=,iv:Ma2bbbOnYcCAFz4SHw5gwVn9S9do2CJQHxvzjmbl4L4=,tag:vdfZYEyrV9V/bFolDKETKg==,type:str]
  ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:rLFfsrs6YevzODLYYKcNWzZBPIA=,iv:Aarkpjxn3VnqLzwD7C+i7KQbiBzRuly8jHm9Fxb33nI=,tag:lV42m7vyZdZT9kEf8LBTzw==,type:str]
  ELASTICSEARCH_URL: ENC[AES256_GCM,data:eSEhHNKlzT1TZBy3s8WUM4sLUGEATDWfix5pyKgmCHBLB6i6iR2F+zeXvjF+OcJmxpzjEk1/HSYjyLnW2o4zwMUC48LSf0KbaSpaHQ==,iv:AqFZMYV+QtSxoMy+doTd0BQIMYnxPu4u7p08pohjjYM=,tag:zv70JKYW8sFja9CgnuWWVQ==,type:str]
  QURAN_CLIENT_ID: ENC[AES256_GCM,data:FJ+XBpH4hzHVRCFixU2uTVZMXTDmUk4mHAhPjwxK1gMjMuked778BpXP2J9hNr5F,iv:5hysxVrt8JzbRnd6D4yxsQL6CIfkZ17JlImQV/yu2u4=,tag:ZXV0b3y8wnxitlFRhuzu1Q==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: qirtaas-secrets
  namespace: dev
sops:
  lastmodified: "2026-04-12T08:22:42Z"
  mac: ENC[AES256_GCM,data:+x0u18cXTCZPq4UISN0De3YCcfE8+X5AXVkFpUpJ1SNx4rurHsqoRME9MGGLuDeBA/MvXrqU9bmX4bFU5YL8h1WVxOocoygHUTuxnOlse/w2xsOy+VMszXBCGrPyPNfZ1su/c2CXuoX9zJ+HA81HNqaENUWGU/SgHeZROs4o7PY=,iv:RxxSn3lCn2GBOcV9ozCuxy3B15Yig0yh051JWwA5KWA=,tag:4DUQFnNJpMtfhGJkuWLmqA==,type:str]
  pgp:
    - created_at: "2026-04-12T08:22:42Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAAhHhKDrAunV8ETXKhSbqluVGzr+5zaLMXWEdTTORaTUxT
        1cexzxrRJWhWgqlEW9isfx5EaD22kTdYbSCddw0yRj30AW6kcgDbz5K7FVZKIbWD
        /+KI2klImClyyOUsnFJHhZcXkRnDDbSoTXdaaSm9DepciFy5WFH3VJHcD6TA3UqA
        ioC31mG3nBty8EbKCLf2/1g0e3RbVr9KsyXEkxlqMADJbmjkVUiZtuUJRL040v4D
        sDlrv5WZKnkFDgQC7vaAafjGBBecEqltYMMpyzpHBy/fpqhbSuigyc25KjGgOhUs
        KynhmEIUtsoYjyT1ca/nTPVVY1gLflS/93O477+Dgb9ZZqfvJJx1S72u3U2Gyk38
        ewA4wR3mZbZXo6wkPNG1czFk3Cv1sOlWrq/zOJZUYC649qybhXM0VoWLVy4gf/EN
        MneuKusoifvH4V9vlst+gnPpqRrV8JjOP6IiuraA4aSslrdx3PhR2whnUmF63n9N
        gTomKB8s47NSX0aTAwaMWBABU2MWFNrtB26Z+j4FWED3moNQCKk3Bxvfy6cfl7qs
        QgO/xAElUpzTpqZM7cEpZ8E1icKIRBMcUxf2AWxSyT2SeIC71v6HBOBfvDuCd3Mi
        Q4/pttqsxGLehNCslgfqnVpuyji+ENQAGHgDKgqlMA1pHN46C/MOUhUsLfxGL/zU
        aAEJAhDEclpOZRe1adFiI0AYss5GE/5Ven4AEfIkzOGsE0vaWaGJcm7T3H74pec2
        XdCs14jMG2UtQ7SJEycbeyoCXAgfhLUAjecqCNUT4bnLVfT8DLZza50rrpLY8tRz
        bn528yV/wghO
        =L9At
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
