apiVersion: v1
data:
    DB_HOST: ENC[AES256_GCM,data:7c4MTPEnaOYLCd7eCtJW4bA4a0YWGpgOI/AfKLeGb0z0a2bodNv0AKAkqaRx8OTWXwjfnBrGb6eewlJtCszIN1C8VAtznyxo,iv:XNwUkOUlOT+UibbRPSOO+t6hJH1nHMpjPTRnFaZ+4X0=,tag:Wg1mwN21wmUVXI1BHsIiQw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:5HmjLb96kc/QHDyxf5YnjA==,iv:IzWnDS+ZFpoYayq/GpYi1ozXLPzaY1hUQNuUB7Vxfro=,tag:UK1i9w5wftJOBpcD05YBNQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:dToNx/7CworS1UV1DZ0HRGCypuw=,iv:LAzbPwTf0poUWHwEzdtetxdJ1t3/y25f9SwAFXTm9Sw=,tag:o188Fxwib6p/jU7lZU0gvQ==,type:str]
    DB_PORT: ENC[AES256_GCM,data:8Qrgo2JRoXA=,iv:Fu0Qc5zDo4jGlXKf4cgKcq17BF9oBKh8Dab9sNACcr4=,tag:1Kghgf3d1ED1H3olSh9SjA==,type:str]
    DB_USER: ENC[AES256_GCM,data:1e6ZvS6DrlRSILucwYbi6g==,iv:D84u09eRhhZTVcc6h3FBhqESJAt0AOJ9GhGE9sQhqvc=,tag:Msk0JtE7gPHnRxk3kqvG9A==,type:str]
    DEBUG: ENC[AES256_GCM,data:2DEjjUhucwI=,iv:ISo46lYWjIEXJYJH2Dkpv3XWtOAc16LQATn7TwYfQGY=,tag:IMClNqHLbOkSEME4tdjTdQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:nhAB//sCPDDn6zE5n0QyBq6+hmCCl036eQ9b6NTjxwxlTP+zc5pTV2P+P5LzFB3YUdiX8+coQ3ZQpkn0qTg9qvzzQOU=,iv:fqt41KRJ9tH1zoPd5WUzOcN5knnNOX194hjhl+Ji6Lg=,tag:APxYCJzCu/dRGcWbh3/7FQ==,type:str]
    ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:npOnBUJ1Y+GLp+eUujMkiLRQCcA=,iv:sQ13Ku6gJeTUu00z0cJn3MwuQdBEgVg2EBnVFndfZsk=,tag:nLTla7HtjwnDFDwgqbtpcA==,type:str]
    ELASTICSEARCH_URL: ENC[AES256_GCM,data:qoo97vEy8uKpU1cOnc7fXzSpNb5+5Qy4QmdsD9V6688M8H4kzArqJ87Ex5Ltn8/SRSfSbxjRpx2IDXB6S9PYdQurVw1yzgBruFTiiA==,iv:tlEoOLzw1jCY9rt85UZLlL3h5UAWr+9H1FNF4so7YvI=,tag:jO6oq+RrSiV5SwwDfAP+NA==,type:str]
    EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:1XWx9uTayDImMPct1Vi8JYhDRQFivZE6zY5MGQ==,iv:2DMFoTqcnKe8hyn7dhIgaO6ZlZLyh2UEiG4vVu/4dzs=,tag:Qih0OK6AgRauzlxI0TJkPw==,type:str]
    EMAIL_HOST_USER: ENC[AES256_GCM,data:ZEWj1731Ei3SN2tyJ08mUTvm9xeb9i0x,iv:9kYuQXdqpJw2rBVLSYrhurtk4ZhBptPrP7x4O5D2BrU=,tag:tapb2vB7RhBSKX6upDUhVw==,type:str]
    BUTTONDOWN_API_KEY: ENC[AES256_GCM,data:iE+wvLKKwWgsCi5g/QFp+5WRxD/O1oA87InSegJzE4knnhMCHUdlUIRDxNxuG/Fl,iv:ZYAFICaxCslrLmebARdSwkMzGjcqaoEjQcAjoTlcABo=,tag:oIx2faPv4noG/WRpRPPsgg==,type:str]
    QURAN_CLIENT_ID: ENC[AES256_GCM,data:C5NfmrX1/BJQyKSQLH69j1cXBHkWEYzhwI1OkFIMVDoroqQ9xsV0EXIw+mLZb7AU,iv:a9c3BI6lmrmjzK5aqvJPjhoE4h7j2WpxxRSSH8miRmg=,tag:BZABL2czk4evVrxOZyKSGQ==,type:str]
    QURAN_CLIENT_SECRET: ENC[AES256_GCM,data:He3mRG6Uc0pSI1F7GiqpWdqlIcE88e1dc3NhmgnBnEESUEGM,iv:YMtm7OWNsW5HPj0SazbsFDamgzaelm627oQqbqRYtDs=,tag:RjyfaAGGtyCbdR2hu6zQ2Q==,type:str]
    MINIO_USERNAME: ENC[AES256_GCM,data:+LDYFMdiyQMq9Hpg4h3Kfw==,iv:MlX80qR8jMGr9awqCrJKG8i6VLDo+FZdxnOkwSpUKlM=,tag:JCN6TKIQc48Ya5Tn6V3OwA==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:68jp2eoLKh6TvrWCigvTivqmWwQ=,iv:8m8c+IpNBWHNgTCA5vzswB+gaYm9fDuseTZIFIBP/kM=,tag:M5lHqKM3yE6R/1mM9v+lfg==,type:str]
    BREVO_API_KEY: ENC[AES256_GCM,data:WxPtTuZ7pKUeT8QR9kGIJVytSy3LYisunCeixwXMVluklO07moEbNRNpxRYeSLLVOg1Bbj0UMkgmO+OpszMyaehZsb+mC0K9s1fNzRVN1c1NorC5I+iHaOofywV7BiMY1NNatxvgyhNYymZARplsCjDgKxxcorqh,iv:XnhMErPIWjqTquphmiv9wpZu5tmcBx0s/zcvwB+9eyE=,tag:bFdfIxLU3LT1PL3/tGQtaw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: qirtaas-secrets
    namespace: default
sops:
    lastmodified: "2026-07-18T13:51:38Z"
    mac: ENC[AES256_GCM,data:dJnlqz1PZ9YQQ1tkeFMXkJMnmhPPBNlgLALrknlXtPfgTFpGaE5GvpPdZg8Ip2cyHMxcqD1k1SuIs/QRnk43G+ibZjE85HycnrzxGHLHBJ37fvHgils3hhyoduVgs0UNLrjHQBbbBCdlv77Yiz2RhtLfEHbWcFwxP+Go1KxBJC4=,iv:DXwXncJHYiFJCIdvQZPuFXXRgaFwpKRxDXxg08mtUCU=,tag:UwOohUNCGsdpQBYCG85zhw==,type:str]
    pgp:
        - created_at: "2026-07-18T13:51:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ/+LU+nVlnGSQ7vlvqEYMLD38JgHavTyRRaQj6M8j+XPV3A
            Xz+ptH+eUa/aeco+oDGChApqJ/lFMVWkex7/bjeshs5veKB0LIADuaFY2QIlMnA4
            HoqvV7SciOAuY/nW2ct8ugrXjFjARo3cSgI8YbXnCgzS/KzkINg7PiGza14c17iB
            T+Y0KcTID6etDT9OwY5y7D7ve+/nRx7PnJ0QdwdM+Tv7JgasaTMf+qG+hlu0TRc0
            8l2kNCgK41r+7sViVaoCCwlL+SiCApUHYls2CcG9lIDicHFJa971vNu2Av7ma7RJ
            CvIKn05CNVxNNuUh4jGAGhyQXsLXAyILN7Mo4BB6lYM3KC9MNkN2F4IOYVMXTXPH
            QuOJeehVbi91Jid6ha0w9yjJFkJmLTlhl0weU7FNFYxtmqzgI+SQyw8OHgBUP0Wb
            lRw8U36+LrGmRRsXEvzImufq4/8Ta/giSNrjKu9JqBsyroTU61YlaU1dn9H8xtaB
            2H3B5425w+LwBhbhDwgGHLgBywtghT7ygtcg6si/NgblkeU+5+gvGkQEOU2FK0zi
            zgGgOPUXu4DNjGqIeJHi37YBzzHWKz9fAP2At9HXDTj37vBr2LuzogSgnAnaogoK
            0wdiMt9yw9Ou4r/QLr5OCfHXQfHZp2i+epBfGTc46SXFcTBbGo9C9Z/KWhGjTGfU
            aAEJAhARwU7zebuYtjAJpHR3nTvVSv/PhLHnfoc5czjtp5UXl7ZtW5H2Q5k1FNrI
            EbvbdDKwHR+sm6Srnm6NnJHNiU10W2ZZzDBxEKTinmLhDvm9sQLFov6JMCyf6Vm7
            tkEA0qw4DXm+
            =a0h4
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
