apiVersion: v1
data:
  DB_HOST: ENC[AES256_GCM,data:kPcfQiG+FcxWjc2l1GqzU8nRVn7usgJezulaOZq/qF4uccDOO0+5uAp/KQp28eNLKRcR+l7EhiBMhKmaweVdu8fJ74Oka9wo,iv:rzJF6N0PVMrevNP7cjNfNH3pwFY/FN6r73BxJ+q2gmE=,tag:97PW43yWv/VSiHwZcOpDxw==,type:str]
  DB_NAME: ENC[AES256_GCM,data:4d8jSqO9kBK0YhbcnH2Gxw==,iv:p73YPjJJ2ArkyEtYeHlsVOcSUSTE25OmaWYMVYEmtQ4=,tag:60NvIbrPB6r1T2zCn2hqxg==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:WJneEDwMCEQ/ZESxSYJerLAeprE=,iv:6TNF59TjedA89OlaclflZzS7T6SlWhMPrDpvzfkTDos=,tag:aEmeiz9pvpx8RSG2vEeMyQ==,type:str]
  DB_PORT: ENC[AES256_GCM,data:4/qctTO1A3g=,iv:LIMXazTCMuERcj9Q1EhomusvR59YhUUU+n0S1knXcUk=,tag:mQ6YpEpuA70A5BRSjHpdxQ==,type:str]
  DB_USER: ENC[AES256_GCM,data:Z9WiLo3MsF6sLsdG63G1RQ==,iv:omjQSKK5QQE4+Q8FmALwBwDVvM330YxUhp/pT7UeTo8=,tag:OqYBlmRdOI4DdcTHZisbjg==,type:str]
  DEBUG: ENC[AES256_GCM,data:p7o3PCDlnbM=,iv:ciekcuFva1zY8Ha2RyOiYz3V9qYLCjGCGI0ypB7JR6c=,tag:5m0TA5JHjygQdThEPVqyUg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:AOPI3zMAdlDcAicu/EWXug03sy+xPNRkwlZtns/B86QfcM7zNz9Zqr6nL7Mex2hlS67Hl6WJCswxg/9f5NNm/0HRFUY=,iv:877yOu+NC/WB3d2k1D3WSPwMHoNIl9RbmIzu+2oFS4s=,tag:3oYqoDTPoMQ20+3fclwh5g==,type:str]
  ELASTICSEARCH_PASSWORD: ENC[AES256_GCM,data:iBTTJHt9RlU1PyZ/5iR2VKODSo0=,iv:o5Vfh7hrFMC2eEJ4P7VmlAeLR8JVvt7CZMI4JJIIhFo=,tag:59IwB7N0OpbiFVc7fzo+gg==,type:str]
  ELASTICSEARCH_URL: ENC[AES256_GCM,data:XBOP3uLCjqM6geA3zUKVOgfzbkyHB1HmnynRTTtoq7Gn3yMSHGVQwE+Slnah9OAV/Prm93tz9Thjd0fyrOiMHpSGVITFXWbewDYQyg==,iv:e0pT9p1jPOnA5IviLMWFyz9PPFuAYcOkrZmEmuWIEfE=,tag:amAHIUCxD4SubYkcYUB6NQ==,type:str]
  EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:2xmPdBJPTzF3t5aZ+7qGJlul3BV40KXwyUAFZw==,iv:f1kaw2hTF1mkFeiPcMQ008W0N+0aNyFwTPLeZ6Wpeuo=,tag:BT7cW8btsYiTqFSWJfGtzA==,type:str]
  EMAIL_HOST_USER: ENC[AES256_GCM,data:XOfsSpgfEEGer/EwfaXXh1UFeXNk3e9v,iv:RxvytRHQ4gP2jwHUhaj2/hUPfbyU2vR7TAzH4xRnFQ0=,tag:ZvIMZGDrknJFhEJvonKdlQ==,type:str]
  BUTTONDOWN_API_KEY: ENC[AES256_GCM,data:d1RmviBLgd1EbNTNh68MhyXKATh9hdHOWiSyJAY5Vxc+retPeKi9wd0K2XoTqt+L,iv:TZlW6ivKMQNXECTGvINP1klfz7Ovary7ruorLFr7USM=,tag:1J5WApmlKliyvQ7EuMvmZA==,type:str]
  QURAN_CLIENT_ID: ENC[AES256_GCM,data:uBLQeIr9afB0x6fbXT4C2xKOLsOC2MELYliSMTYvps6dJbdzXgZSscbGFTCtLZI8,iv:Z8dDBYyyndyMPVt4G14sdKsMRYEZpe+572klsefKBCs=,tag:tlY/0i4bNHJpadebwII+Ow==,type:str]
  QURAN_CLIENT_SECRET: ENC[AES256_GCM,data:3TrwG6cZNi2OkW8UO7BEHoYaftsEIPvTzN4xLUQxYNYPMHN8,iv:wTo9wg4DxSikGVnlnUtXFbLCq4EU+UUQstH1Eu+MDJU=,tag:MI6Ld+4DC0Rh5Cpn/piJrg==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:tZG0a+/9cNUAF38kUvI1Yw==,iv:3hBitaaAgmHBwbSVR4yDUykKrAUpZOFdJeaW1nsmK5M=,tag:skvGXTO9oRVCNUKwxa5O4A==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:xH0LAB/iDIQ1TKHTfK+PCuC07zc=,iv:347mMR0XGiJSNCgRwH4q0zdaAO/OazItD+QtiFvsnIU=,tag:NFPfJAlYQIJJAHuX3fdtdg==,type:str]
  BREVO_API_KEY: ENC[AES256_GCM,data:ooKedIX4IC/CVyMDjjUa8yDI5PECRTCilg4yZ+G34XzCv+HQeDOMkiTn7DbAk5Ba5kSwJALNX0QoybbNkY7Wc8ceslWXyq3SndpG7kpj+7j4ca+42OPKJKlvP3DAzz/GGSHw22R5p98oCG9AJ+sEKCf051XE3C3u,iv:Stv5Mj5X5rINyaCleTkoGfi9Ehfv/tZBkxsmk7lRi4k=,tag:sOoU/f0W4zrUrOx084AvgQ==,type:str]
  SPA_SIGNING_SECRET: ENC[AES256_GCM,data:he7vAwwE3l1d/I8RRSk/9bjmtVaXJ2Hvc73bS7nShRy6aGdDzdkOtSpQG78Ltpli8jY/ner8EqPfk6IKYN0KYH1zamvDWSGCFqeUjgb3d/rvca6KxMnq6A==,iv:XKvNrgVjABpglzl6aORDl5qxhlGTXTKN9U3UXcjgBcw=,tag:PMO7DAN4DUEFEjiQ5YI+rw==,type:str]
  QURAN_SYNC_CLIENT_ID: ENC[AES256_GCM,data:ZR+1CPZbDxzMZdbuXESkCyJeF6adJyyJLSpQ0YI119t1ftTq8dHMGN+H3IpF3SEi,iv:nj/qNmB5BpltzJdWO7hxN1vRib1rDO0/eHwFhlStxhw=,tag:YD/WtFuyoQyAxm2+qeDb6Q==,type:str]
  QURAN_SYNC_CLIENT_SECRET: ENC[AES256_GCM,data:d6jmhq03icBhDX6sVhiMIDc0oH5aNxF53ZHzlcKElhYs8ZwJ,iv:QCtpm1EaWuofQF+ooIhmzByQlk3sR2PWMQhMclrFBrY=,tag:q+JbEycw4ahWtEXGGrtbIA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: qirtaas-secrets
  namespace: default
sops:
  lastmodified: "2026-09-25T15:30:20Z"
  mac: ENC[AES256_GCM,data:n/QpHN5da0EpaefnJgUudliD4m3x5m/zYMIDDAzTCdJmnP4W2DUjFGmIocuzOA3wD3Z1bO7Ve/ETJV0ML+g/t3DskeH8hTAEP7qtdQpIx72chK+wNECjK94BSu5Qufg6Ic10Z7xeYPDnYqd2O4LuhZa/FaDZVaz+4NMGRuk9SKc=,iv:7tcDtFAZvnRC5yfn279EzGyLNF90206lgDX8Lc/2AsI=,tag:LqbddBerxLBTymTiHMBRsQ==,type:str]
  pgp:
    - created_at: "2026-09-25T15:30:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/+Jxi52Jts9js4C1j4mvtucMy7cVIQE9muyvbalj65d5na
        aKszTQjY2RSq5x2k0QjMnUjqUQdIgq9o0DOU9nUKlQMqxmuELv+aE1HGJwQXK80M
        ntTYxk9qpmGsq+CSe5AYjRNqJiH+L8Ws/MzY3Ns+pZkcB77+Z3ZJm6Yut16B5BZ7
        xQ6j4zUyafT74zNrIt8vSnn2XCbff6K/sAowshwrL8ecUzJSktmH2QjZ5oIn/57n
        XQ2yW+tZqnZNrEPCUtgie7Cd/bxlHWCvc+ehRrAFs4ufFHosyjwT67vEUmzNk5u6
        SSUVNLgaPL6hp0RRsxqm+RJ6oTOpAmfksiWMWrC/XnwL1jF9HtoIqrWgS5ACHWRt
        yFNUpCUsqaJh3iHratZQ46SUnw1kWBUO0PuqzJNRnXZlFnNZqFzbEP0lZL/PrYsu
        la2+PVcquyUydMX/FkjLVjzI8TAKTK/nj/weMvZQCcSH/0ypXlgWCLLPZ+D1G+pF
        dwA8aCJyWzMStnxyN4F8tK7fZtpD/3oEkrZhaoBo5M9AWb2sHBYyh6NL5HvwefnV
        pYHrj6Ztkw1L7prhbFn+bQ7gCW5VCrdRm0/2+JXIyBzGTQ29pwPA2DkWCN9rYZGi
        U/lt1Iow4Zi/OcI2H9knko/T1jiZxBL6H6XMjTlqiPQBqfXhjFu/zPIFJyv6cw3U
        ZgEJAhAYsU/T8dPh1p3uVHRlg8TxurhQ/YwzyAjTHmuRLIXvGIPj5ejOJTp5XVHZ
        +SwoqCDkOEGdAukwDISyMS5AkGDjxEmyjBy8UJ500bYO9CNW4h9sDr9GG8LA46gv
        TWU6fLqC9g==
        =KH9Q
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
