apiVersion: bfiola.dev/v1
kind: MinioPolicy
metadata:
  name: caas-dev-readonly
  namespace: minio
spec:
  name: caas-dev-readonly
  statement:
    - effect: "Allow"
      action:
        - "s3:GetObject"
      resource:
        - "arn:aws:s3:::caas-dev/*"
    - effect: "Allow"
      action:
        - "s3:ListBucket"
        - "s3:GetBucketLocation"
      resource:
        - "arn:aws:s3:::caas-dev"
      condition:
        StringLike:
          s3:prefix:
            - "*"
  tenantRef:
    namespace: minio-tenant
    name: myminio
  version: "2012-10-17"
