apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: caas-dev-policy-binding
  namespace: minio
spec:
  policy: caas-dev
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    builtin: minio-dev-user
