apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: caas-dev-policy-binding.yaml
  namespace: minio
spec:
  policy: caas-dev-readonly
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    builtin: Rockband1768
