apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - caas-dev.yaml
  - caas-dev-policy-binding.yaml
  - caas-dev-readonly.yaml
  - caas-dev-bunny-policy-binding.yaml
  - backup.yaml
  - backup-policy-binding.yaml
  - percona.yaml
  - percona-policy-binding.yaml
  - root.yaml
  - root-policy-binding.yaml
  - loki-policy.yaml
  - loki-policy-binding.yaml
  - muzbuild.yaml
  - muzbuild-policy-binding.yaml
  - caas.yaml
  - caas-policy-binding.yaml
  - caas-readonly.yaml
  - caas-bunny-prod-policy-binding.yaml
  - qirtaas.yaml
  - qirtaas-policy-binding.yaml
