apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - caas-dev.yaml
  - caas-dev-policy-binding.yaml
  - caas-dev-readonly.yaml
  - caas-dev-bunny-policy-binding.yaml
  # - backup.yaml
  # - backup-policy-binding.yaml
