apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: loki-policy-binding
  namespace: minio
spec:
  policy: loki-policy
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    builtin: Reselect0187
