apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: percona-policy-binding
  namespace: minio
spec:
  policy: percona
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    builtin: Sloping4585
