apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: qirtaas-dev-policy-binding
  namespace: minio
spec:
  policy: qirtaas-dev
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    builtin: Coexist7710
