apiVersion: bfiola.dev/v1
kind: MinioPolicyBinding
metadata:
  name: qirtaas-ephemeral-policy-binding
  namespace: minio
spec:
  policy: qirtaas-ephemeral
  tenantRef:
    namespace: minio-tenant
    name: myminio
  user:
    builtin: Simile4083
