apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - background/image-automation.yaml
  - background/image-policy.yaml
  - background/configmap.yaml
  - background/deployment.yaml
