apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-tenant
spec:
  interval: 5m
  chart:
    spec:
      chart: tenant
      version: "7.1.*"
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
  values:
    tenant:
      pools:
        - servers: 2
          name: main-pool
          volumesPerServer: 1
          storageClassName: "openebs-hostpath"
          size: 10Gi
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: v1.min.io/tenant
                        operator: In
                        values:
                          - minio-tenant
                  topologyKey: "kubernetes.io/hostname"
      certificate:
        requestAutoCert: false
