# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas-backend
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: caas-backend
  template:
    metadata:
      labels:
        app: caas-backend
    spec:
      serviceAccountName: caas-backend
      containers:
        - name: caas-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: ghcr-secrets
