apiVersion: v1
kind: Service
metadata:
  name: caas-backend
  namespace: default
spec:
  selector:
    app: caas-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
