apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - namespaces.yaml
  - secrets.yaml
  - charts.yaml
  - minio-operator.yaml
  - apps.yaml
  - gateway.yaml
  - cert-manager.yaml
  - caas-predeploy.yaml
  - caas-backend.yaml
  - caas-predeploy-dev.yaml
  - caas-backend-dev.yaml
