apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: qirtaas-backend
  namespace: default
spec:
  interval: 1m
  image: ghcr.io/alrimaal/qirtaas-backend
  secretRef:
    name: ghcr-secrets
