apiVersion: v1
kind: Service
metadata:
  name: muzbuild-frontend
  namespace: default
spec:
  selector:
    app: muzbuild-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6021
  type: ClusterIP
