# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qirtaas-render
  namespace: default
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: qirtaas-render
          image: ghcr.io/alrimaal/qirtaas-render:0.0.0 # {"$imagepolicy": "default:qirtaas-render"}
          envFrom:
            - secretRef:
                name: qirtaas-secrets
            - configMapRef:
                name: qirtaas-config
