apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - caas-dev.yaml
  - pxc-backups.yaml
  - caas.yaml
  - loki-chunks.yaml
  - loki-admin.yaml
  - loki-ruler.yaml
  - qirtaas.yaml
