apiVersion: bfiola.dev/v1
kind: MinioBucket
metadata:
  name: pxc-backups
  namespace: minio
spec:
  deletionPolicy: IfEmpty
  name: pxc-backups
  tenantRef:
    namespace: minio-tenant
    name: myminio
