apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: redirect-to-https
  namespace: cilium-gateway
spec:
  parentRefs:
    - name: default-gateway
      namespace: cilium-gateway
      sectionName: http
  hostnames:
    - grafana.intern.alrimaal.com
    - minio.intern.alrimaal.com
    - minio.alrimaal.com
    - bunyaan.space
    - api.bunyaan.space
    - bunyaandev.alrimaal.com
    - qirtaas.io
    - api.qirtaas.io
    - qirtaas.alrimaal.com
    - qirtaasdev.alrimaal.com # removed to not impact SEO
    - qirtaasbackend.alrimaal.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: "https"
            port: 443
            statusCode: 301
