apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-class.yaml
  - gateway.yaml
  - grafana-http.yaml
  - http-redirect.yaml
  - shared-cert.yaml
  - cluster-issuer.yaml
  - minio-http.yaml
  - minio-console-http.yaml
