apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shared-cert
  namespace: cilium-gateway
spec:
  secretName: shared-cert-tls
  dnsNames:
    - grafana.intern.alrimaal.com
    - minio.intern.alrimaal.com
    - minio.alrimaal.com
    - api.kurdoos.app
  issuerRef:
    name: letsencrypt-gateway
    kind: ClusterIssuer
