apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shared-cert
  namespace: cilium-gateway
spec:
  secretName: shared-cert-tls
  dnsNames:
    - grafana.intern.alrimaal.com
    - minio.intern.alrimaal.com
    - minio.alrimaal.com
    - bunyaan.space
    - api.bunyaan.space
    - bunyaandev.alrimaal.com
    - bunyaanalpha1.alrimaal.com
    - qirtaas.io
    - api.qirtaas.io
    - qirtaas.alrimaal.com
    - qirtaasdev.alrimaal.com
    - qirtaasbackend.alrimaal.com
    - alrimaal.com
  issuerRef:
    name: letsencrypt-gateway
    kind: ClusterIssuer
