apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  serviceName: elasticsearch
  replicas: 1

  selector:
    matchLabels:
      app: elasticsearch

  template:
    metadata:
      labels:
        app: elasticsearch

    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:9.3.2

          ports:
            - containerPort: 9200

          env:
            - name: discovery.type
              value: single-node

            - name: xpack.security.enabled
              value: "false"

            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secrets
                  key: password

            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g"

          resources:
            requests:
              memory: "2Gi"
              cpu: "1m"
            limits:
              memory: "2Gi"
              cpu: "1m"

          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: elasticsearch
                    operator: In
                    values:
                      - "true"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: openebs-hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
