# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas-backend
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: caas-backend
          image: ghcr.io/alrimaal/caas-backend:1.0.0 # {"$imagepolicy": "default:caas-backend"}
          envFrom:
            - configMapRef:
                name: caas-config
            - secretRef:
                name: caas-secrets
