apiVersion: bfiola.dev/v1
kind: MinioUser
metadata:
  name: minio-dev-user
  namespace: minio
spec:
  accessKey: Deranged1876
  secretKeyRef:
    name: minio-dev-user-secrets
    key: secretKey
  tenantRef:
    namespace: minio-tenant
    name: myminio
