apiVersion: bfiola.dev/v1
kind: MinioUser
metadata:
  name: minio-loki-user
  namespace: minio
spec:
  accessKey: Reselect0187
  secretKeyRef:
    name: loki-secrets
    key: LOKI_MINIO_PASSWORD
  tenantRef:
    namespace: minio-tenant
    name: myminio
