apiVersion: batch/v1
kind: Job
metadata:
  name: caas-db-migration
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: caas-db-migration
          image: ghcr.io/alrimaal/caas-backend:1.0.3 # {"$imagepolicy": "default:caas-backend"}
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: caas-config
            - secretRef:
                name: caas-secrets
