# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muzbuild-background
  namespace: default
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: muzbuild-background
  template:
    metadata:
      labels:
        app: muzbuild-background
    spec:
      containers:
        - name: muzbuild-background
          image: ghcr.io/alrimaal/muzbuild-background:0.3.0 # {"$imagepolicy": "default:muzbuild-background"}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: muzbuild-config
            - secretRef:
                name: muzbuild-secrets
          volumeMounts:
            - name: apns-cert
              mountPath: /app/aps.pem
              readOnly: true
      imagePullSecrets:
        - name: ghcr-secrets
      volumes:
        - name: apns-cert
          secret:
            secretName: muzbuild-cert-secrets
