apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: muzbuild-background
  namespace: default
spec:
  imageRepositoryRef:
    name: muzbuild-background
  policy:
    semver:
      range: x.x.x
