apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/deploy
  - ../../../base/deploy/background

patches:
  - path: patch-configmap.yaml
  - path: patch-image.yaml
  - path: patch-background.yaml
