# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qirtaas-background
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: qirtaas-background
          image: ghcr.io/alrimaal/qirtaas-background:0.1.1 # {"$imagepolicy": "default:qirtaas-background"}
          envFrom:
            - configMapRef:
                name: qirtaas-config
            - secretRef:
                name: qirtaas-secrets
