apiVersion: v1
kind: ConfigMap
metadata:
  name: caas-frontend-config
  namespace: default
data:
  LOGIN_ENABLED: "true"
  API_URL: "https://api.bunyaan.space/api"
  MIXPANEL_TOKEN: "8eaf7533ac6465dffa802012d29ec378"
