apiVersion: v1
data:
    DB_NAME: ENC[AES256_GCM,data:uEXoQuDiIqI4K9Di,iv:a6UMGExd8rDYKkPCfI2cGINK0s+XX2libEsh2oU6iEY=,tag:vUzaCcM5n1hcqQWvjL9Hfw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MxYDIbn6kb9hyyZjmuSIl2aJYSM=,iv:B2NOXZsG/3289SunhvuYX9lkcGrHjtYw81EvhV90+ts=,tag:+e6tV/8VBIyaC5tWogkCHA==,type:str]
    DB_USER: ENC[AES256_GCM,data:QMQe7lmdL74xW/VE,iv:y+hc9eZOO73tDPyF2twSV/y0ofqXW5mvybcK9fHOdsg=,tag:XRNGtjpV0j4gRaL5nz/FCA==,type:str]
    MINIO_ENDPOINT: ENC[AES256_GCM,data:FPpKsANP08uFQ4inilHC5xuRe6zYK9to,iv:tReO+piKDDGt9vzKUTq8u7nRL8jIMztWvlnPXccfE6k=,tag:Q++kmmIwtFhKEPZmftec0w==,type:str]
    MINIO_PASSWORD: ENC[AES256_GCM,data:YRXIR1pQHqxsEanlRTSfA5cY+d4=,iv:r4iG0Mdwagpzyjvyaoy5Cfs6EObwgixy+JRFKVQ6S6c=,tag:P7nZ7is9tJTogw6h7lBBDA==,type:str]
    MINIO_USERNAME: ENC[AES256_GCM,data:coThseyBlv6vNG9AopRDCqlXl3w=,iv:AllVeM+ensYqN6Vhw1uscr8fI5unx3pBGNuGSj9sQVo=,tag:4t6b5fQ0EU1HHk3nYwGthQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:DWnYitgmvkRXxeyrsTRgU5BD9wQSbDpormIRr/4KodSnCQrlMQ/VwNEFLy/9juar9jiqgX4LNI4CtJMUfLphyzJgdxE=,iv:b8ccG0ml1DIpDEChqL4H+lAQBsxalCc75Ce66yTGvhI=,tag:AnjFNl+ZemBdhM56WDZpvQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: caas-secrets
    namespace: default
sops:
    lastmodified: "2025-11-19T22:29:39Z"
    mac: ENC[AES256_GCM,data:xBn92TyZ4ohjMkjtdcTR5vByisV/A5kRPi/covG9TtpPHQvVqzkOYomEx3c3yPiG4QqeIFLI7VHyBvNXZHIoQIgTkiT8Vt0kJDBysDDW6d1dOPt1HcVuA3gzzXc6luKY8+mWDSdv4sspNlLFiBDvv72Q0bRrLBoSv+xtsjowRsQ=,iv:ZM73OSfmLlHAjYkCEx2Jm71xsKI/tRd577Qj4bi/2/Y=,tag:/bU36PaXF3oXOFSFVfT/wg==,type:str]
    pgp:
        - created_at: "2025-11-19T22:29:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ//SaIA+oGAqUnmcpTOfkjPtjaNx0kuV2KnP41yAzMZ3OPg
            rjPDU9st7lFuYESlTeFwCERKn2IAgnFBnqdjgKWiqWYJhtbF1A2hyex/WElr4GG/
            49GHrkMcAgsXSotZeO4EjvE2UboFwVrRHK8s59jokWruKXuJnr4cKj9UlChMepL+
            jLy1Al722+vRpBd6RcsRtvdCXoiCswYz4R819X9UF3cLgreVSRR+1brpgB1YXFQI
            OqJffgEIUSt1XyPGZz7UuocFfocSKUiewJJiQ/NTZLdddZwWNPVNvEpmN1SEQxBV
            9bD4G6lMFcHhbycF/GTH6yRwLyQFWGnxSLRo7XJo8u4XliVVh70c9yGSzgabW9Xo
            XIaLLuUlHPmtSFOBzZx8qsUh4xx+U3tSjAGirOSbi9n2Vmlgsr2sdd7yMCO1f0zm
            FbEE8zB7UBRa5t0k+bD4HjSB55o0xuzcjh9wjohO23/g9buahFi1HeEIgvHdjUsr
            VQInit3HtvTKQUTu8ZH5BAuL8BE0BEyULsVJl9dfPtM7ZA8WOim7XofyLFWPKqjC
            Q5JPk3lmoahqnpqyRS7J2uAScJJ7lQlNUXufEgJKchs2RhU0WX17BMlK74aUr0dj
            ip4+4SUA+QlM3s+WXSbDB2OSpGmoMqARMI6aBRyuheMThmp+RAQqCd3XqG9B3enU
            aAEJAhDQPvBOumm0t3ErUHHb6KXhD93CmYuAK53fP92ZYibIeAwrrSS49TswC3UW
            qjmpMyyN+mdq0DkNTsMJjqw6DeYQr+1Cg7sydHGRrk+muiWT8UUS4novHbp5h3LU
            AAhPUtKE6BIU
            =21X3
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
