apiVersion: v1
data:
  BUNNY_CDN_TOKEN: ENC[AES256_GCM,data:gN3/BC/Z8iqlzMEgqUkXvUWIfxaFBxpf+3ex9MxGMdoYyU4HmYD+k2Cx91jHOI4m,iv:CBpdwgKaQORRvXzgovGf/ezZBWAXNubArODJmzvKMu8=,tag:WQIkY4aeZwQw6OVoTYiTfg==,type:str]
  DB_NAME: ENC[AES256_GCM,data:feaaOzOUcwSgtIcH,iv:lYMq5+eRjArDRQEL00OiJNzWb3DVez7XTN5zJBPVoCY=,tag:fhN7Jfs6X02fAZt/kLaCig==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:ALIFwWEU0frnTjuafQ/WniegT9A=,iv:PrYOIUvDj1/O+ZsWywntlHP0V6DbV+KbxwiyxlFWZ8M=,tag:6+UXL6QGzi2Cc65mCE40Dw==,type:str]
  DB_USER: ENC[AES256_GCM,data:waUabsh8U8/yKnNd,iv:K2O9Knw7/QvLRYirEesuQ25SujOtyom1UwoZtA5onVE=,tag:RC2MpxYhIubdR3P9YfHRYw==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:3hvtR+nrfpOApSRghSvLcGwvIIDf9wKk,iv:une0z5jwfVtbe0enl8k+3Hli7tf05/3alh+Qg4qqSQQ=,tag:biBgRxYG60K8amZBGxL71A==,type:str]
  MINIO_PASSWORD: ENC[AES256_GCM,data:990dDj9z+Me/D6Cya4fEscEvsVw=,iv:sl/s5CK78rZPRbQiguF/43PMiMWLw4cPGlddKDtJqSM=,tag:enjd+/3bjB3zNOVh+10k6Q==,type:str]
  MINIO_USERNAME: ENC[AES256_GCM,data:ZgZl6yUfdfUtWvZuLesOGA==,iv:iLXoqvNLY92BPaIypb+CiSX1Jr0+TGfdf0vMZeoHZpI=,tag:uNBv6uIOMr8wWBFO6JRbOg==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:LH6bsHua23KGl/prVFmj60PhDHMh3KTlbcvPnnwDGZuFPcML51gdBSO1WLp7ggawiIkqJzok+nX17JOY3FPDbXC+zC0=,iv:EwezKAZFfUicoG4+MmED7EpGQUZFL/T45OUHgSVci18=,tag:EBw2Z/gRPmCyyNpGC1B72g==,type:str]
  DJANGO_INTERNAL_TOKEN: ENC[AES256_GCM,data:BqOImskaTe76GtlkrunbCQ67St9tWudsnIp4PuK351sEjqfL/sFxoMNngR6g5ejIX8MBbvTpX5cptVPG,iv:I2fxHaTx3jHwZM5UaaoCLakg+Ti6aVOnP0FfgAqM6qc=,tag:nSMoEZlGmrbcCfvGRYRqrg==,type:str]
  EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:PCUG1SWVoPrioPJSRylN47HExZ+ddWaaHi13UQ==,iv:WlgZlctoC1r9DTHfKeYeMQth34nsZFvs9n4fsBqupcY=,tag:QSYXVj7oVIMZOAxaY/Ef8w==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: caas-secrets
  namespace: default
sops:
  lastmodified: "2026-01-18T19:06:31Z"
  mac: ENC[AES256_GCM,data:qlGK8wtv+potWn+zEO2Hoik6snyLSJqlRT4JaZPHHCLsHRu7EiuKMOM7SmOjCuekSE49eJUFvvbNKhseeWlNbarhGTPOp4LD9kfywXfGXHZk/WHzuH85txK6UbDQULeyj/CGSOuQgTlkEV0R/3PYtkVNRyWlr287T1XkGw7wZ98=,iv:HXQRSN3ocdz+p+cFabkXHFOdrNlhs+xo/c0X+l+1YIs=,tag:xm3Zp+knED2MWlUNYIC3bw==,type:str]
  pgp:
    - created_at: "2026-01-18T19:06:31Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ/+Imzi4Uxh6AdelmfOosaQYSlhHpO10rJpNwz8W/dNqJW2
        7AmSKAauhqH/3a6cG/Us3IL6UTpGiVl7t4qsH77dRTqp4PhnVzDEWYDSx8IrilKz
        oymtJzn8wNFmE7GBrYbWoW23EjbOvnvvgXrjLNA9xwjnjYb56MtwwHuvckb8kEuV
        rSpiagg6odE+LI5ekUZtN/iRTZX6Urt5xDvTafYzj9bSB2UN4cJmS6g9X4tZW8RC
        IPdVDUp4tOJSt3j5b38135nA5NPb1t1xVvcKSv+81WRwlfM87zMRb/4B5+fz1JY6
        po5iyQ/VI7qFKQ9PjxcvMAuudT7Org4acIA/7ki/trRWTRK8vGbQquzDXxAXxmZT
        KWSR36eqWyRNLtUOE/HlQinpYsECalyNxp+UIXn9UX2JD1YVtD6SybrCwEEPvk7S
        QbzhDWbin6Qu9cqbNBOHFL7h83xfQP/Zo6Qqwd5rvO10G69efWfy9hZDziumHPz1
        xYkMG5Jat5WJuNH2eEYJfyowGd8eejuU/Nz6YO+eU7fFrwtwylxleTKuD/9TWkBr
        z+AK/VaVZ7df6s0+Bd5OS4E799d98GKcDqcySyvqQF/3QQcn3btUNTDmdGkE+4YC
        5u/scAEfAOn+WrR45LAZzJSFr1zubKd9SAdf5mO+T9SjXJByMAX1Iv4nxxvuKoPU
        ZgEJAhB9QRmHMdS4LR8JvlHe29OCG6kCEZg2qUK1Og5tAQfEdkTf6Jee5V+isow5
        0we9WvRwb+kr+w33iGTUxGa5Q9XMWqvhwyc+gFPj7LWC3QwZNVHvdbFvsMOG/ssc
        0EpHcNVinw==
        =holm
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
