apiVersion: v1
data:
  DJANGO_URL_PREFIX: ENC[AES256_GCM,data:87mwPKz3ALSHCHl8LuHbgY9dWzZKDgmm47hVWJIZfL3y2Fj4,iv:vt9x/OERTvUqGJ/Ljyn55ZDCjB/DX9zaOFB2sMb+mxM=,tag:fybzcvYzmFtw2axcPqHckQ==,type:str]
  DJANGO_INTERNAL_TOKEN: ENC[AES256_GCM,data:/m/MCZP5DlkJ6cfVah/isE+oDQ6qG3Hx2oqTavAgL2zxI5PsVxcIKthA88DgnJxftP7n2giN5xMq3/mi,iv:GpBQe+27hmF9X8T0uBWDQ1RGmTGeEY+4hYPO30aYBFM=,tag:iCVse2cRXdqS8g+UkkXdXQ==,type:str]
  MINIO_ACCESS_KEY: ENC[AES256_GCM,data:5XknoO2bYz/Ft4Aen/v+/A==,iv:5MKg23EyTrdHFrUv/+JSE1Ub/Rm55gYxMzsJ9a/j+4E=,tag:FN/PFqRLPTuAJrDHLYxXTQ==,type:str]
  MINIO_ENDPOINT: ENC[AES256_GCM,data:hcY/unmAc5SKAFtm6delnCob8nCG2v4ogKZeHg580Ep+YE/V2q6KxqfOc3nkEroA0vQQGjCCFMFu6C3oJmduVQ==,iv:JwOfFkyQDHB4ZjaERoZkX5qOKq1zVNkpB09qn7LcZBI=,tag:jwPxGtZhjok1SqrflLgdfQ==,type:str]
  MINIO_SECRET_KEY: ENC[AES256_GCM,data:J6mF7lCVLLTSwDEEM0VzdWfDWt4=,iv:QAhyh0GBQuSx8ZYzETOWESoLEftUyR2p1RcrasNICH0=,tag:2YskhgX2Dd2ex/MbZiTk0A==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: transcoding-secrets
  namespace: default
sops:
  lastmodified: "2026-01-18T19:06:34Z"
  mac: ENC[AES256_GCM,data:cuPC8ahN8aRvvE3SFSMr3aCTg6oZ1rovk6tZToqBE0asyiFPRTcvGAZsziGKxElQFHEdASQ5MLhg9HqW9WGV1fkIbwOufhIIgzvLmzdFcH/tlZwqupFuQVjPi+90K5GcH/l7OUwUzfK8TFKZUnUDv082xLVdEW+q0hWnmAQPBTM=,iv:UOIGuXOLjlOe1CRiLCyCUN/eYZbfVuTllqgB78lxQXE=,tag:0W5n2XVEeuF01llf8tZvSA==,type:str]
  pgp:
    - created_at: "2026-01-18T19:06:34Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//bkqai2xocnMkLyz41Eg/F0XkF49eE6rYIiCvZc3RREB1
        MUPifmQpok3HVVWwrcjkBdhts1FfZEnV7FTYupO3ojGItP2aj3L15BYERclLo5tQ
        7SE4ZjhzcgnT4lBbQ2IHgwHw4XExYT8JHFWjh9yUO9PLxYNR7FIp/l+pjlwtFEn7
        1Qk/hcQgDvUPSLqvSm8d3mM+Udj4394CUE+vl53AM6YKD4GcQPPNH4iVRuLV1jnZ
        QPsUfhZhD+PcYgc1nDK7ZWUmeK7f567z6aKWszxSRl8fFMJMbfcwEm/l/fjuwi8V
        n36RCuKT084fg2cWHOqZitvbDiM7lAuFS8doN65RpduUtp7cwYisk9C0ql4/7K4D
        3/JVFIRhES69lan33WsS/4V3fS+r/V5m9FnXOiQdvMWunm0MrQq9CfGwFjgpRACZ
        CLNGlHmsg0U0A8woa+z61RwBq1pJ8L2WTziQ4ewbQc56kJBUFBOoZPLQoGEV6o8f
        /J7KJgGoRD4e/YS+H9JmqjMSNqZqynGbsqGeToFtP632z9CDNxsLFRF8mZWszpZv
        6ULAKBmG9/XSDOG7SsRiF23eZ8KhlHI04U33dXxjhrpx2JploRSY6hYfImvVsJ6D
        p5n0a8LULgVzeeFSBS5pWxfXQ2A096jxCZ/2Jlamc7A+UI9d8p+18FkuAHsRJxbU
        ZgEJAhAvSUcshcUVLlyG5wXJgh7ee7JoXBRXjTxapBh8kNnuAVE2fTs6ci6j6XTN
        7QLivwUxO4g3Z3jaDvBvAvqmdMUf8hyv4wnGoMM5QqUmMN7jf78EczUfA7/7z2T3
        N/cgzKcnQw==
        =/wvL
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
