apiVersion: v1
data:
  API_KEY: ENC[AES256_GCM,data:SAaZn73/TmQDi68FwMc1nPzGUMSWpVJQzfXTORWhqmR6SCJfZ/8aiC9UC3xHs/JC0WuPYKsLuLF7P+StSDT4PmowfNb92QKlbPioE9KZ7bTVr/S1ieb3RQ==,iv:GJWISXNZRU7EO79MtAnkwSYKqV005QjqPEjXfqXcSGg=,tag:Ufb+Q2GBWEi+zplNvj/Y8Q==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: argo-dev-django-key-secrets
  namespace: default
sops:
  lastmodified: "2025-12-19T10:26:19Z"
  mac: ENC[AES256_GCM,data:WbSDwmdEzRMd1XDPRtXfENwiE8hatp/haogANmyYPvZ54X/lQYYA0y6cHCuDzOuuuH3+MiGZuTjL2Rai0TWL7mCNe7bTxYeQm/savluEJRtkHyDiVRTP1vVfOxAzYWQXRsu9F/bJNGFfJOEyBXomv5J+JjPoQThVk1x5jO4dECY=,iv:9MC/zLuFcwq7dh39xoi9g07OS4RtkZ365U7hnjY+cHU=,tag:PrQv0jBfIWqE9Kqx4HCWvQ==,type:str]
  pgp:
    - created_at: "2025-12-19T10:26:19Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cAQ//TbITrtFtmHs3Ba0O0dR37+L5ZvscPYknqs11VAaf0MOo
        +v2j4c1LkCgq3stBJ9/27Igl7ZqD+lnHAM8kPV5iVNZzH7QTtIlumI1003l8mQwE
        0I87waUh/hxWycF7PN3xOUX1sHznU59dHHPWiLGyDcX7AjuxfnYUZBpbg0KGm64s
        O9iWLmXzCyA70ZixiSPNgWMclujnJI9MGNPofuV+3QetttBxc2BKHG2UiRWd60RT
        9tpv/L4/dnvCCDvNVv2kHdVf3IJ8XUA+pHDiUKVDDKeU9DEJevKPm3GhBk+Ay77O
        7Ko5LWqrfTgj8Wu9/iIm1RGSV+dIfE5svRVjyLJ7LVa1KpQbT4HQr9yK8d+8xhQN
        WJ4evAw2Ov/EKW7fv/SPBbDPuxh92iyBXLzmJnG/rT15JVA7alX8C5vDABn7BjY3
        9YMYuQ86JQMRWHRyDCNrtNpMmnBoL8MiHKNcICCpBFXARXq0E1NeqUBSPDuguOex
        jBWCdalmnLUZJtWLblzM6nQ4fyFpsHAbKiKJavwZilsWGTgj9vciG1CfQ/qv+u99
        LOG8EhHOtJqvl9IFFmadQ8Ygrp+A586w7nU06chp4bFDBH46BVIKv32eBGbKT15x
        TfKarbD1yY/2e7zzKZWugEsvRicLHylWSUSfuwlnCr6v6D1QasG1pXZFUCfa/zvU
        aAEJAhBSLvbjkx+2W8qi9Y5jxRaTJZWUnx2BrXBaVs6vf1AC+dvGEazeHwjESGno
        7aCe2kFT+7Uzd8L0FrO3g1zHu7vUzdp/RXFn0uCQY6dpZaV2R9NHb4e2Ti2aEi9w
        BWshAWs4Mrl/
        =dC9F
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
