apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:0atpd6C1jZItG3iiRuTmoqwpzGUlO/+6bWqWTvT6QiaB3L8wviJuldHCNE9QUZUCaAI04Ps8cl4s6vtUQUF4qRuGy/V45JxFOhzqv6XiVBbChtAADEdG+0Oap4W8ro8EqJABgQDCH47tscvTJ+Snp6zVfR+L+UFXdsZ8EifiuDTBZLCHv8vSnWwAYGD8FEtVD32HF0rWwvUbN9uccusistW5kGA593shlBKDprjcR4M1HK+CNbjaEySQE54rMggWAkIf9tYmG6oXybTtxb+P58MlhTvEnz7NZGg+CU2TtB8VfPdj1vCuUppiba76KD4l,iv:vuFTt9nHVkISsm/RbH0EXpH/Ky8if9ggbqSInT3kw7E=,tag:vQncWCT5ar7yXKnN09eSew==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ghcr-secrets
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    lastmodified: "2025-09-13T09:05:53Z"
    mac: ENC[AES256_GCM,data:jovi3ddAR6nfq0RN7ei8cH+62gXqswyU7Jqpodw1j/iPY1hdInsNMwQMsUBjTVoQcivapDI/bMWrsgkp8hFzQJ2s2gmmGYAP+maag1hWtbXnsRitrKDrT2CYNimHLqs98fkNzez/Wz0iJUnVFZYys2BzjBhiMs3EFKTf2Hi2is4=,iv:IwO9q+ybT1weCwTxyzbo9Y/vEdvvfCDhFtRUku3+w4w=,tag:kADPGT9b+tUOQlLDG4kcFg==,type:str]
    pgp:
        - created_at: "2025-09-13T09:05:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ//erIuIO97tgqfBjZ2hTe+pWolq1vAJSoCPAuCT1M+uLPm
            k28b9qCYrHc3LJ49ImbqZq7uPUNg/dXmmNaNsw2mXjEn8dfWWHmmuGRHXqkw25/F
            lrwliXEMq329T/VQgKWkpzFMC4qpzKuFYdhEw9ngLaNnKgF34bzzUq56GhVFTcO3
            mXzeFKLH8K8Yn6uYcHnM2RGbyZ3dm6FH9460Anri2DDdtBp6rK31uNM/I68pD8zL
            QLEMs/2Oi/kV1fvZGiKcMOufx5FtENplwG8f29vJgXJoowVWR6VTAAbLgkmSK1ZL
            y3M5G1X9RZV1YBe6VnnRp16AqlK/jt3XxQB75s5QQTDKlJBfpR+5uZzXCdESeOit
            PqqvU6eKUtLUA1BYIE69fCnnx+IrJJrt8TTWQxUZ20RVnQV0dVOFWbAWUg2F2zLF
            RcPtB6ntOIX1dEFFsUlO+EHhvBO6BryvBaj7ioDJLiPKFbN+eHCJkHJJjMwqzvuu
            /NQn+8qy2lhjUZOleAYTM+2Fmk+VrfEBIJq7Z21DyPdPNgDFx4Dt4n9Ftqgs2e3O
            /gHrd4WkR1YVVykewG9mybbUKu8FJhe7KnkuDx1VUTJQMFsqvpho2fj8NgVLC6Ki
            fvmwbXs5enSyaGmOtVGZqvZem6IzgKuJfsOtCGF8FpdfgRdhc69cvCCoYNOsKUXU
            aAEJAhBXKZ7HFC5uDW3zWnyDVAvtbA6AtSwed8YPPFAuTaAx5FHHkghUVXcWoglW
            hrxvW7HfCJDsrDG6XmiJlu8WFTHrbwuUVfc1LX/9sdlCp5LJvDojZFjkXP540Bx1
            lp8gPlNCKmaY
            =8nHr
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
