apiVersion: v1
data:
  LOKI_MINIO_PASSWORD: ENC[AES256_GCM,data:C5Xiy5AwUL9MbrirkSiSAoaJFkE=,iv:lqdgvau0BmKJcHzz5zNMhJI3UzO8RduIZi2a6OHrxC8=,tag:mrimGUgFRC08D/obNangAw==,type:str]
  LOKI_MINIO_USERNAME: ENC[AES256_GCM,data:FOchpN6FFtFlwih4wnTWgA==,iv:gLC8h2eDVyg0W4RxXuBFcz2loPsK+B1eBPVULmQJb4A=,tag:UVGws9/mIuE/Bs+7mQF1cA==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: loki-secrets
  namespace: monitoring
sops:
  lastmodified: "2025-09-11T09:36:56Z"
  mac: ENC[AES256_GCM,data:J1XIHLhzMb7ogY4WiXuj17weMNYlj6Gy7nz8N4dyeRthuGvUxydoURJ7lza/6LSBc4j4VPSTuk98FsepAVWgxUF7DbTlIE+/kBbZ7FefnBSsP/FiHtwAGLQ4g5LgbByyOkscuwiZmMJ1V+e7NZnPeV4nRIhxtOjjW+aS8E09X6E=,iv:cvdRZ12lgnrrE/jk2yDrbtO4+BM7HpLEcHH3/IHmcGI=,tag:DsJhwDTa5iFonnNz6FfeGg==,type:str]
  pgp:
    - created_at: "2025-09-11T09:36:56Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA3eMlJTqoU+cARAApbhjufQXYsHQkX3svKoy8zJKVLXopxOhBg8gmrqVGzlL
        ULjPslGSypKgV70bjoVpAC27tfzIi2FteOoNJNd/Zwi8I5z49Tt/5MPWLrEf9CGb
        VywCIG+5XcSKwOx3eNzzAlZMXqXVISn3iuDgHLl11N+J+PL/u5Y05n2r4J3LRpGD
        VWdjWkiyTMH60Tl9czkCfn0F6y1HfCuQHBpISUoOa64mMxbkMIsm1yR3VLxvVVO2
        5gQcNtcQ0s/Sf2Qa9mHzQCgZAVqhNnpa69TJB3+R6WVsZ5Gxe4F1LZWZ6S+3/tPm
        Crl6AV1lnyg+pXq5L1zAFUIfahaw96ahPNM/XLNMe1n+ndGjzWIGt5knOYb7GK4/
        5QpPciC2N5x8lPliLk3QcPSjIGWrFW9MOrira85V+lcNo9zFDuWKxxqnQCZSMgvQ
        YNU9DPrzDyvGLriaqa6fnGw1pQ0uPcgyFaGiIqftec272grCwbHtYy/CG4+rhmGq
        HLjj2ruy3qbKHbGlJhJyDZp6HsqXbb3KKvLh3wVr7znZu2tJcO/3Jv2PRFGPQl4r
        IycBt4mb2M5iKkMAJKwW5wEcSSCJTEOP9tKctb/ECkNAc/QpVMuOJj74pvYRwYqt
        MZ9H9Rk4GwzvS1zeGnkWST5GuLWKZ2RyFOjNV9Ia6DbrRoOT2ZUikSNvtVtC+BHU
        aAEJAhBdwgUCF6klWxtR/e2EV7Da92Zdwxxj2myc8vlPvw0FBXS84VbaKomxEA9E
        DY4v+AfhbRLzferpFJkGQl5h6N4oVQ5ZpfuziJhOHzixGvS9AF0+bbbviclv4dWX
        Zj/AyQOG4vbG
        =gL2B
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
