apiVersion: v1
data:
    accessKey: ENC[AES256_GCM,data:biTJiNpcjusOiNkSxEbXmQ==,iv:AtYeS/85NcrSM2OqTBA8I7QEQ1fNYuestWYkPKCZwpg=,tag:Y0fwxDRpMKeaMTkCfltV6Q==,type:str]
    secretKey: ENC[AES256_GCM,data:I/VfpaMuqYCWV8/55oGBGRA1WPU=,iv:02aKFpu/+01b5hWRiksacdjFWiJvPfhAV/jIdi5o980=,tag:VfSVi4A7RO2JprDL58ZwvA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: minio-argo-user-secrets
    namespace: default
sops:
    lastmodified: "2025-12-19T09:24:02Z"
    mac: ENC[AES256_GCM,data:uroYNfsw/gqqR7r8KDinwzUCH6aiSa2R8qyiX0nXvmVSeB3GVsKAexkjeZs1eqiMd+O+iWIPjWlQoh7pH7OD+XNzZWsJiq0js/M+XgOG40RvT2iGSUaDHnF1W9REIY2xQSqvUOK5+YWEVipYsYk6a3d8wNSajNTOjNPcXMAmv+M=,iv:sF+j6xpd37Ft7e1MA82u4KWZ90MTNIb14IuaK9oOPe4=,tag:OHSSZ2pMGTzokDjFXaH9HA==,type:str]
    pgp:
        - created_at: "2025-12-19T09:24:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3eMlJTqoU+cAQ/7B94N5uP8Dm3jGrpLRwkly5wwIxATvSSi3MshqvrubnBn
            HeSI3+bn9YM6WMYwgxvi+zpTz9pBXZewXSF4VQ2zqCLZPzq13jEmsoplfOtxk4bL
            TTCur5YXYI0E4wKrgOFyOOSGCzbTedp2OvCZSjq+UF0WiQz/bwdiTs+tc8MoepcK
            zWOqQoALxsuf0kssM+wK2oXhgvP4QKAOVuOmEKCBdYXgzhZvndSVhLt0V/ZtGWbw
            x6REw5uhfIj+at3wd5Ad0qVwgBEtMOC1o4c21vz08k4v2t18HSrEGkM0FOb51kOu
            s/qEm48sYqqtsVN1YfTroqzdiUMVuZuJ2Jgr35xwoK5poqcKMxLrHXIGJqX0ABUN
            ur3YuKUE3WqxHxjJEo2r8XlpJrryLGyVowN/BjofKcZ7omOq//TyH6WLaiMYWcSD
            NsIDViKp0Or6L9Im+39e9lUrEEswdHTPExFf7s0QDEUNwW4ytCdaIigPFjWBp7DR
            aTyDgdwTRx1ZAmEl7VvbfxQZmJdoIuRjpbxdZXOQxlGNDEWH3NYan70QSToJJjWP
            C+GM/JCtsHI9ZmdM5XH/Q/Ew3/1tvL6Nl5wrQNTAueilP7cRYzvvzaBkgckml6sW
            W6S/qJ6M1QrUpKREo73jMBnJqi3WpS+TlayhM0BgiuIDcMMA76fJUnWCsWTOK0bU
            aAEJAhBV1hZ/SpuDC777FfDfAZT7uOdFtrmz3rsCC0eX0JiP0mJWR/gOb8W/xY4P
            pr9tHPqxXmq1yKv1UAsxQ09g+n+/nlu5gaT2Pe7dEIndL200SlcaarzTv16zD9GR
            3K3FuIG1EhoI
            =SA+8
            -----END PGP MESSAGE-----
          fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
