apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:tbiq8ulxYFqxPudgAq381Q==,iv:DgRA9rSob6tWg8+nGlpN/YbC3flCYJ+6+du/NSjojd0=,tag:izm9Tr8GGE1jk0FbP106DQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5zGoxwJFDEB2KxI/8g5RBSuA4hg=,iv:zXl8Neyr8BQ6T4pASLz7+uCxAnIysteZUs8v4V7qWQI=,tag:o6c5kBZnxG/5m2o94Bjg7A==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: percona-minio-secrets
  namespace: default
sops:
  lastmodified: "2026-01-12T10:34:47Z"
  mac: ENC[AES256_GCM,data:BqE+qDufLglp4TpX9uu8RATZS1A6THVMFk7jFyIEEcgTo8beFsKoOB/vZb7Cymp/fWUC+8exwCCIcC6r8JuYNytOQ2EMkz+h33ZAmFqyD6tc/OPozJ+/DHjPe6iyHrNYitS8fHaIQOhnZdpUk4lVbgIF4x3e+H6/7Wf8OCzqaRE=,iv:3Akx2ESqEmW9RTprF4bGEywri8x7cHgnnziUANi5PRc=,tag:c+Pk0AlG1Fg5OBw1yf2M0A==,type:str]
  pgp:
    - created_at: "2026-01-12T10:34:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQILA3eMlJTqoU+cAQ/4piKv8YcAFBCO/WHG/1aG5iDmb+epGQwBkCpKNNLLpwKM
        tS28HSaqpvYvWrxt+qpQiZI4doWOAXgZHNL6c3/A++ZL7+Eswhda6QsulOYp88BK
        m4EGFFHUZlnzEnOhUuTADvZDKBbXB1qMgaqTetk3LnnBA0E7ONDddSQWVwb9fa5G
        XqytN//NXqaVtMuHS0aZccGnjGWwPcfaoxIaA+toOrmwe4WlHi98MLcA3Ro/rSqy
        0IfisFYhdME1xpc9ZKyohtdNPv1CdZdSh5heKQa41vbnqS0vHKuWPMKjSA8gAvCN
        Ve6wo6luy7HMDCYAut4lYI8BCjR2xp4RzNpTYtjj1D16MxfEtgq8v6CX3Y+XYyAy
        yf89XD6rRV5MwzjOXG/4XzKsccZ+CxBZ/ZTvMakID3Vu2pUDtiTiMMdItQ6aBMDq
        geQONotBf6Cw/dUb0SeJak2SF7jMgTOmfeQhHXSj9H1aprCJVQU4idale9AQnYMU
        Tcp3LAPL8xA2evvRSxij+3ST2oY0Q2M0+qWMdUWv3mkx/u7POURE2Ap0ZQ10NB/v
        6IEEgyGrMWRk3TWkvFZSUXVlgKfSnMv8Oigniq7UHFUGhAxZxFKX8E8L8Wcm/4ir
        6IcCsGc6ms9iL3GSWeS1B8IOlpYsgHzDRT65XutTrdaIc0kgLJS4JPDtHVJbYdRo
        AQkCENO3m+KnzpSoYtGygnWxsAMTdgRCvLUOUjQif0wpyosCAGz7h93RBGDyOX1X
        Vcr482qOd0VxL7eI5WMdVo1hRahiAYQ0OP6Uek2ZyO+9SajUaxvP6XdBKkd/Dgf1
        lwE95WM4/1k=
        =+E4i
        -----END PGP MESSAGE-----
      fp: 7B6DEB966D9BA36575FC0E0EED6E551B970D6B83
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
