apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-stack-charts.yaml
  - percona-charts.yaml
  - openebs-charts.yaml
  - certmanager-charts.yaml
  - minio-charts.yaml
  - minio-operator-ext-charts.yaml
  - grafana-charts.yaml
  - argo-charts.yaml
