apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio-operator-ext-charts
  namespace: flux-system
spec:
  interval: 5m
  url: https://benfiola.github.io/minio-operator-ext/charts
