# app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caas-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: caas-backend-dev
  template:
    metadata:
      labels:
        app: caas-backend-dev
    spec:
      containers:
        - name: caas-backend
          image: ghcr.io/alrimaal/caas-backend:1.0.3 # {"$imagepolicy": "default:caas-backend"}
          envFrom:
            - secretRef:
                name: caas-dev-secrets
            - configMapRef:
                name: caas-config
